# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "aiperf-plugin-host"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aiperf-core.workspace = true
aiperf-plugin-api.workspace = true
aiperf-plugin-sdk.workspace = true
blake3 = { workspace = true }
libc = { workspace = true }
object = { version = "0.36", features = ["read"] }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
semver = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tempfile = { workspace = true }
