# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "aiperf-test-static-extension"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[dependencies]
aiperf-dataset = { path = "../../../../aiperf-dataset" }
aiperf-endpoints = { path = "../../../../aiperf-endpoints" }
aiperf-extensions = { path = "../../../../aiperf-extensions" }
aiperf-rng = { path = "../../../../aiperf-rng" }
serde_json = "1"
