# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# MetricRecordMetadata is defined in aiperf.common.metric_records_wire, which
# itself imports from aiperf.common.models.error_models. A direct top-level
# re-export here forms a circular import when metric_records_wire is the
# first-entry module in an import chain (e.g. pytest collection ordering or
# tools that import it directly): loading models/__init__.py kicks off while
# metric_records_wire is only at line 13, before MetricRecordMetadata is
# defined, so the re-export fails and tears down both modules. Lazy-export via
# PEP 562 __getattr__ keeps `from aiperf.common.models import MetricRecordMetadata`
# working (documented public API, used in tutorials) without forcing
# metric_records_wire to finish loading before this package init.
from aiperf.common.models.base_models import AIPerfBaseModel
from aiperf.common.models.credit_models import (
    BasePhaseStats,
    CreditPhaseStats,
    PhaseRecordsStats,
    ProcessingStats,
)
from aiperf.common.models.dataset_models import (
    Audio,
    Conversation,
    ConversationMetadata,
    DatasetClientMetadata,
    DatasetMetadata,
    Image,
    InputsFile,
    Media,
    MemoryMapClientMetadata,
    SessionPayloads,
    Text,
    Turn,
    TurnMetadata,
    Video,
)
from aiperf.common.models.error_models import (
    ErrorDetails,
    ErrorDetailsCount,
    ErrorTrackingState,
    ExitErrorInfo,
)
from aiperf.common.models.export_models import (
    EndpointData,
    GpuSummary,
    JsonExportData,
    JsonMetricResult,
    TelemetryExportData,
    TelemetrySummary,
    TimesliceCollectionExportData,
    TimesliceData,
)
from aiperf.common.models.health_models import (
    CPUTimes,
    CtxSwitches,
    IOCounters,
    NumericAggregate,
    ProcessHealth,
    ProcessHealthAggregates,
)
from aiperf.common.models.progress_models import WorkerProcessingStats, WorkerStats
from aiperf.common.models.record_models import (
    BaseResponseData,
    BinaryResponse,
    EmbeddingResponseData,
    ImageDataItem,
    ImageResponseData,
    ImageRetrievalResponseData,
    InferenceServerResponse,
    MetricRecordInfo,
    MetricResult,
    MetricValue,
    ParsedResponse,
    ParsedResponseRecord,
    ProcessRecordsResult,
    ProfileResults,
    RAGSources,
    RankingsResponseData,
    RawRecordInfo,
    ReasoningResponseData,
    RequestInfo,
    RequestRecord,
    SSEField,
    SSEMessage,
    TextResponse,
    TextResponseData,
    TokenCounts,
    VideoResponseData,
)
from aiperf.common.models.sequence_distribution import (
    DistributionParser,
    SequenceLengthDistribution,
    SequenceLengthPair,
)
from aiperf.common.models.server_metrics_models import (
    BaseSeries,
    BaseServerMetricData,
    BaseTimeslice,
    CounterMetricData,
    CounterSeries,
    CounterStats,
    CounterTimeslice,
    GaugeMetricData,
    GaugeSeries,
    GaugeStats,
    GaugeTimeslice,
    HistogramMetricData,
    HistogramSeries,
    HistogramStats,
    HistogramTimeslice,
    MetricFamily,
    MetricSample,
    ProcessServerMetricsResult,
    ServerMetricData,
    ServerMetricsEndpointInfo,
    ServerMetricsEndpointSummary,
    ServerMetricsExportData,
    ServerMetricsRecord,
    ServerMetricsResults,
    ServerMetricsSummary,
    SlimRecord,
    TimeRangeFilter,
)
from aiperf.common.models.service_models import ServiceRunInfo
from aiperf.common.models.telemetry_models import (
    GpuMetadata,
    GpuMetricTimeSeries,
    GpuTelemetryData,
    GpuTelemetrySnapshot,
    ProcessTelemetryResult,
    TelemetryHierarchy,
    TelemetryRecord,
)
from aiperf.common.models.trace_models import (
    AioHttpTraceData,
    AioHttpTraceDataExport,
    BaseTraceData,
    TraceDataExport,
)
from aiperf.common.models.usage_models import Usage
from aiperf.common.models.worker_models import WorkerTaskStats

__all__ = [
    "AIPerfBaseModel",
    "AioHttpTraceData",
    "AioHttpTraceDataExport",
    "Audio",
    "BasePhaseStats",
    "BaseResponseData",
    "BaseSeries",
    "BaseServerMetricData",
    "BaseTimeslice",
    "BaseTraceData",
    "BinaryResponse",
    "CPUTimes",
    "Conversation",
    "ConversationMetadata",
    "CounterMetricData",
    "CounterSeries",
    "CounterStats",
    "CounterTimeslice",
    "CreditPhaseStats",
    "CtxSwitches",
    "DatasetClientMetadata",
    "DatasetMetadata",
    "DistributionParser",
    "EmbeddingResponseData",
    "EndpointData",
    "ErrorDetails",
    "ErrorDetailsCount",
    "ErrorTrackingState",
    "ExitErrorInfo",
    "GaugeMetricData",
    "GaugeSeries",
    "GaugeStats",
    "GaugeTimeslice",
    "GpuMetadata",
    "GpuMetricTimeSeries",
    "GpuSummary",
    "GpuTelemetryData",
    "GpuTelemetrySnapshot",
    "HistogramMetricData",
    "HistogramSeries",
    "HistogramStats",
    "HistogramTimeslice",
    "IOCounters",
    "Image",
    "ImageDataItem",
    "ImageResponseData",
    "ImageRetrievalResponseData",
    "InferenceServerResponse",
    "InputsFile",
    "JsonExportData",
    "JsonMetricResult",
    "Media",
    "MemoryMapClientMetadata",
    "MetricFamily",
    "MetricRecordInfo",
    "MetricRecordMetadata",
    "MetricResult",
    "MetricSample",
    "MetricValue",
    "NumericAggregate",
    "ParsedResponse",
    "ParsedResponseRecord",
    "PhaseRecordsStats",
    "ProcessHealth",
    "ProcessHealthAggregates",
    "ProcessRecordsResult",
    "ProcessServerMetricsResult",
    "ProcessTelemetryResult",
    "ProcessingStats",
    "ProfileResults",
    "RAGSources",
    "RankingsResponseData",
    "RawRecordInfo",
    "ReasoningResponseData",
    "RequestInfo",
    "RequestRecord",
    "SSEField",
    "SSEMessage",
    "SequenceLengthDistribution",
    "SequenceLengthPair",
    "ServerMetricData",
    "ServerMetricsEndpointInfo",
    "ServerMetricsEndpointSummary",
    "ServerMetricsExportData",
    "ServerMetricsRecord",
    "ServerMetricsResults",
    "ServerMetricsSummary",
    "ServiceRunInfo",
    "SessionPayloads",
    "SlimRecord",
    "TelemetryExportData",
    "TelemetryHierarchy",
    "TelemetryRecord",
    "TelemetrySummary",
    "Text",
    "TextResponse",
    "TextResponseData",
    "TimeRangeFilter",
    "TimesliceCollectionExportData",
    "TimesliceData",
    "TokenCounts",
    "TraceDataExport",
    "Turn",
    "TurnMetadata",
    "Usage",
    "Video",
    "VideoResponseData",
    "WorkerProcessingStats",
    "WorkerStats",
    "WorkerTaskStats",
]


# Lazy re-export of MetricRecordMetadata to avoid a circular import when
# aiperf.common.metric_records_wire is imported before this package. See the
# note at the top of this file.
def __getattr__(name: str):
    if name == "MetricRecordMetadata":
        from aiperf.common.metric_records_wire import MetricRecordMetadata

        return MetricRecordMetadata
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
