model_list:
  - model_name: gpt-4o
    litellm_params:
      model: gpt-4o
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4o-mini
    litellm_params:
      model: gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY

general_settings:
  master_key: "sk-5Sj6tKGH7u5b83A1e-9jZoLrZh-VyXpR5bbOq67EYOM"

environment_variables:
  CHATGPT_AUTH_FILE: /home/anthony/.codex/auth.json
