# Build
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "aiperf/__init__.py"

[project]
name = "aiperf"
version = "0.1.0"
description = "AIPerf is a package for performance testing of AI models"
authors = []
dependencies = [
  "pyzmq==26.4.0",
  "pydantic==2.11.4",
  "uvloop==0.21.0",
  "aiohttp==3.11.18",
  "rich==14.0.0",
  "numpy==2.2.6",
  "pillow==11.1.0",
  "soundfile==0.13.1",
  "transformers==4.52.0",
]
readme = "README.md"
requires-python = ">=3.10"
packages = [{ include = "aiperf" }]

# CLI Entrypoint
[project.scripts]
aiperf = "aiperf.cli:main"

[project.optional-dependencies]
dev = [
  "pytest>=7.0.0",
  "ruff>=0.0.0",
  "pre-commit>=4.2.0",
]


[tool.ruff]
# Base settings for ruff
line-length = 88
indent-width = 4
exclude = ["__pycache__", "build", "dist", ".venv", "venv"]

[tool.ruff.lint]
select = [
    # pycodestyle (except E501)
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
# Ignore line length errors, ruff format will handle this but
# can have some lines that are slightly over due to the way formatting works
ignore = ["E501"]

[tool.pytest.ini_options]
# Basic pytest configuration
testpaths = ["tests"]
