[project]
name = "aiperf-stock-openbench-environment"
version = "0.1.0"
requires-python = "==3.12.*"
dependencies = [
    "inspect-ai==0.3.141",
    "inspect-swe==0.2.26",
    "openai==2.30.0",
    "openbench",
    "orjson==3.11.9",
]

[tool.uv]
package = false

[tool.uv.sources]
inspect-ai = { git = "https://github.com/UKGovernmentBEIS/inspect_ai.git", rev = "bb78d82dde311b68dbfd0b49f3186b9fc13a1465" }
openbench = { git = "https://github.com/groq/openbench.git", rev = "3f190a835f7fee34ccd96e17242a36a29e0620a6" }
