/*
 * SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

//! Strict SDK-authoring gate.
//!
//! Detects prohibited bespoke scene composition and package-form scenes so the
//! migration to typed `sdk.*` / `aiperf.*` component authoring can be enforced.
//! Detection is source-oriented: it reads the authored scene (package-form or
//! native `@scene` AST) and, when available, the lowered `SceneIr` carrying
//! compiler-only SDK provenance (`sdkOrigin`). Nodes generated by an SDK factory
//! carry provenance and are exempt; raw primitives authored outside an explicit
//! `freeform { … }` block are prohibited once their scene has migrated.
//!
//! Enforcement is phased so package-form decks keep compiling until they migrate:
//!
//! - `"off"`: no detection, no diagnostics.
//! - `"report"`: detect and emit `warning` diagnostics; compilation still succeeds.
//! - `"strict"`: detect and emit `error` diagnostics; compilation fails when any
//!   prohibited signature is found (the final migrated `strict: true` build).
//!
//! The gate reports the detected signature, its source range, and the SDK
//! component that replaces it. It never rewrites authored source.

import {
  parseNativeEmbeddedScene,
  type ConnectorAst,
  type PropAssignmentAst,
  type RectAst,
  type RenderDeclarationAst,
  type SceneAst,
  type ScenePrimitiveAst,
} from "../language/index.js";
import {
  diagnostic,
  type Diagnostic,
  type RenderNodeIr,
  type Result,
  type SceneIr,
  type SourceRange,
} from "../schema/index.js";

const unknownRange: SourceRange = {
  source: "<unknown>",
  start: { offset: 0, line: 1, column: 1 },
  end: { offset: 0, line: 1, column: 1 },
};

/** Phased enforcement policy for the strict SDK-authoring gate. */
export type SdkAuthoringPolicy = "off" | "report" | "strict";

/** All phased enforcement policies, ordered from most lenient to strict. */
export const SDK_AUTHORING_POLICIES: readonly SdkAuthoringPolicy[] = [
  "off",
  "report",
  "strict",
] as const;

/** One detected prohibited authoring signature with its SDK replacement. */
export type SdkAuthoringSignature = Readonly<{
  /** Stable diagnostic code, e.g. `SDK_AUTHORING_PACKAGE_FORM`. */
  code: string;
  /** Human-readable signature name (what was detected). */
  signature: string;
  /** SDK component that should replace the bespoke composition. */
  replacement: string;
  /** Owning slide / scene id for diagnostics. */
  slideId: string;
  /** Source range of the offending declaration or node. */
  sourceRange: SourceRange;
  /** Optional extra context (capability id, geometry, …). */
  detail?: string;
}>;

/**
 * One scene to check.
 *
 * `rawScene` is the authored scene value (`EmbeddedSceneSource` for native
 * bodies, or a package-form `SceneAst` carrying `roots`). `scene` is the lowered
 * `SceneIr`; when present, its nodes may carry `sdkOrigin` provenance used to
 * exempt SDK-generated structure from the bespoke-signature detectors.
 */
export type SdkAuthoringSceneInput = Readonly<{
  slideId: string;
  rawScene?: unknown;
  scene?: SceneIr | undefined;
  sourceRange?: SourceRange | undefined;
}>;

/** Options controlling the strict SDK-authoring gate. */
export type SdkAuthoringOptions = Readonly<{
  /** Enforcement policy; defaults to `"strict"` when called directly. */
  policy?: SdkAuthoringPolicy;
}>;

// ---------------------------------------------------------------------------
// Signature catalog: prohibited capability → SDK replacement.
// ---------------------------------------------------------------------------

type SignatureSpec = Readonly<{ code: string; signature: string; replacement: string }>;

/** The canonical chrome / header geometry deduped by `sdk.header` (95 scenes). */
const HEADER_CHROME_GEOMETRY = Object.freeze({
  x: 18,
  y: 16,
  width: 664,
  height: 44,
});

/**
 * Prohibited raw capabilities and the SDK component that replaces each one.
 *
 * Unique illustration primitives (`core.circle`, `core.ellipse`, `layout.pad`,
 * `core.text`) are intentionally absent: they are permitted inside an explicit
 * `freeform` block and carry no reusable structural meaning on their own.
 */
const PRIMITIVE_SIGNATURES: Readonly<Record<string, SignatureSpec>> = {
  "core.panel": {
    code: "SDK_AUTHORING_RAW_PANEL",
    signature: "raw panel chrome",
    replacement: "sdk.panel",
  },
  "core.header": {
    code: "SDK_AUTHORING_RAW_HEADER",
    signature: "raw header chrome",
    replacement: "sdk.header",
  },
  "core.note": {
    code: "SDK_AUTHORING_RAW_NOTE",
    signature: "raw note chrome",
    replacement: "sdk.note",
  },
  "core.chip": {
    code: "SDK_AUTHORING_RAW_CHIP",
    signature: "raw chip chrome",
    replacement: "sdk.chip",
  },
  "core.callout": {
    code: "SDK_AUTHORING_RAW_CALLOUT",
    signature: "raw callout chrome",
    replacement: "sdk.callout",
  },
  "core.bracket": {
    code: "SDK_AUTHORING_RAW_BRACKET",
    signature: "raw bracket chrome",
    replacement: "sdk.bracket",
  },
  "core.divider": {
    code: "SDK_AUTHORING_RAW_DIVIDER",
    signature: "raw divider chrome",
    replacement: "sdk.divider",
  },
  "core.connector": {
    code: "SDK_AUTHORING_RAW_EDGE",
    signature: "raw connector edge",
    replacement: "sdk.edge",
  },
  "core.route": {
    code: "SDK_AUTHORING_RAW_EDGE",
    signature: "raw route edge",
    replacement: "sdk.edge",
  },
  "core.arrow": {
    code: "SDK_AUTHORING_RAW_EDGE",
    signature: "raw arrow edge",
    replacement: "sdk.edge",
  },
  "core.elbow": {
    code: "SDK_AUTHORING_RAW_EDGE",
    signature: "raw elbow edge",
    replacement: "sdk.edge",
  },
  "core.fan-out": {
    code: "SDK_AUTHORING_RAW_FAN",
    signature: "manual fan-out tree",
    replacement: "sdk.fanOut",
  },
  "core.fan-in": {
    code: "SDK_AUTHORING_RAW_FAN",
    signature: "manual fan-in tree",
    replacement: "sdk.fanIn",
  },
  "layout.stack": {
    code: "SDK_AUTHORING_RAW_LAYOUT",
    signature: "manual stack placement",
    replacement: "sdk.stack",
  },
  "layout.grid": {
    code: "SDK_AUTHORING_RAW_LAYOUT",
    signature: "manual grid placement",
    replacement: "sdk.grid",
  },
  "layout.rail": {
    code: "SDK_AUTHORING_RAW_LAYOUT",
    signature: "manual rail placement",
    replacement: "sdk.rail",
  },
  "core.lane": {
    code: "SDK_AUTHORING_RAW_LAYOUT",
    signature: "manual lane placement",
    replacement: "sdk.lane",
  },
  "core.band": {
    code: "SDK_AUTHORING_RAW_LAYOUT",
    signature: "manual band placement",
    replacement: "sdk.band",
  },
  "core.swimlane": {
    code: "SDK_AUTHORING_RAW_LAYOUT",
    signature: "manual swimlane placement",
    replacement: "sdk.swimlane",
  },
  "core.stepper": {
    code: "SDK_AUTHORING_RAW_LAYOUT",
    signature: "manual stepper placement",
    replacement: "sdk.stepper",
  },
  "motion.signal": {
    code: "SDK_AUTHORING_RAW_SIGNAL",
    signature: "raw motion signal",
    replacement: "sdk.signal",
  },
  "motion.pulse": {
    code: "SDK_AUTHORING_RAW_PULSE",
    signature: "raw pulse overlay",
    replacement: "sdk.pulse",
  },
};

const RAW_RECT_SIGNATURE: SignatureSpec = {
  code: "SDK_AUTHORING_RAW_RECT_PANEL",
  signature: "raw rect + text panel signature",
  replacement: "sdk.card / sdk.panel",
};

const PULSE_PROP_SIGNATURE: SignatureSpec = {
  code: "SDK_AUTHORING_RAW_PULSE",
  signature: "pulse-flag overlay",
  replacement: "sdk.pulse",
};

const PIPELINE_SIGNATURE: SignatureSpec = {
  code: "SDK_AUTHORING_MANUAL_PIPELINE",
  signature: "manual connector chain",
  replacement: "sdk.pipeline",
};

const FLOW_SIGNATURE: SignatureSpec = {
  code: "SDK_AUTHORING_MANUAL_FLOW",
  signature: "painted-path + motion-signal pair",
  replacement: "sdk.flow",
};

const DUP_HEADER_SIGNATURE: SignatureSpec = {
  code: "SDK_AUTHORING_DUP_HEADER",
  signature: "duplicated header geometry (18,16,664,44)",
  replacement: "sdk.header",
};

const PACKAGE_FORM_SIGNATURE: SignatureSpec = {
  code: "SDK_AUTHORING_PACKAGE_FORM",
  signature: "package-form @scene { roots: … }",
  replacement: "native sdk.* / aiperf.* authoring",
};

// ---------------------------------------------------------------------------
// Raw-scene classification.
// ---------------------------------------------------------------------------

type RawSceneKind =
  | Readonly<{ kind: "none" }>
  | Readonly<{ kind: "package"; sourceRange: SourceRange }>
  | Readonly<{ kind: "native"; scene: SceneAst; sourceRange: SourceRange }>
  | Readonly<{ kind: "unparsable"; sourceRange: SourceRange }>;

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function rangeOf(value: unknown, fallback: SourceRange): SourceRange {
  if (isRecord(value) && isRecord(value.sourceMap)) {
    const map = value.sourceMap as Partial<SourceRange>;
    if (
      typeof map.source === "string" &&
      isRecord(map.start) &&
      isRecord(map.end)
    ) {
      return value.sourceMap as SourceRange;
    }
  }
  return fallback;
}

function classifyRawScene(
  rawScene: unknown,
  fallback: SourceRange,
): RawSceneKind {
  if (!isRecord(rawScene)) {
    return { kind: "none" };
  }
  const sourceRange = rangeOf(rawScene, fallback);

  // Package-form SceneAst preserves the authored `roots` array; native scenes
  // never carry it. `parseEmbeddedSceneSource` converts package bodies to this
  // shape before the compiler sees them.
  if (rawScene.kind === "scene") {
    if (Array.isArray(rawScene.roots)) {
      return { kind: "package", sourceRange };
    }
    return { kind: "native", scene: rawScene as unknown as SceneAst, sourceRange };
  }

  if (rawScene.kind === "embedded-scene-source") {
    if (rawScene.form === "package") {
      return { kind: "package", sourceRange };
    }
    if (rawScene.form === "native" && typeof rawScene.body === "string") {
      const parsed = parseNativeEmbeddedScene(
        rawScene.body,
        sourceRange.source,
      );
      if (parsed.ok) {
        return { kind: "native", scene: parsed.value, sourceRange };
      }
      return { kind: "unparsable", sourceRange };
    }
  }

  return { kind: "none" };
}

// ---------------------------------------------------------------------------
// Native AST bespoke-signature detection (outside `freeform` blocks).
// ---------------------------------------------------------------------------

function propScalar(
  props: readonly PropAssignmentAst[],
  name: string,
): string | number | boolean | undefined {
  const prop = props.find((entry) => entry.name === name);
  if (prop === undefined || prop.value.kind !== "literal") {
    return undefined;
  }
  return prop.value.value;
}

function hasPulseFlag(props: readonly PropAssignmentAst[]): boolean {
  return propScalar(props, "pulse") === true;
}

function makeSignature(
  spec: SignatureSpec,
  slideId: string,
  sourceRange: SourceRange,
  detail?: string,
): SdkAuthoringSignature {
  return detail === undefined
    ? {
        code: spec.code,
        signature: spec.signature,
        replacement: spec.replacement,
        slideId,
        sourceRange,
      }
    : {
        code: spec.code,
        signature: spec.signature,
        replacement: spec.replacement,
        slideId,
        sourceRange,
        detail,
      };
}

function detectRectSignature(
  node: RectAst,
  slideId: string,
): SdkAuthoringSignature {
  return makeSignature(RAW_RECT_SIGNATURE, slideId, node.sourceMap, node.id);
}

function detectConnectorSignature(
  node: ConnectorAst,
  slideId: string,
): SdkAuthoringSignature {
  return makeSignature(
    PRIMITIVE_SIGNATURES["core.connector"]!,
    slideId,
    node.sourceMap,
    node.id,
  );
}

function detectPrimitiveSignatures(
  node: ScenePrimitiveAst,
  slideId: string,
): SdkAuthoringSignature[] {
  const out: SdkAuthoringSignature[] = [];
  const spec = PRIMITIVE_SIGNATURES[node.capability];
  if (spec !== undefined) {
    out.push(makeSignature(spec, slideId, node.sourceMap, node.id));
  }
  if (hasPulseFlag(node.props)) {
    out.push(makeSignature(PULSE_PROP_SIGNATURE, slideId, node.sourceMap, node.id));
  }
  return out;
}

/** Declarations that count as painted paths for the `sdk.flow` pairing. */
function isPaintedPath(node: RenderDeclarationAst): boolean {
  if (node.kind === "connector") {
    return true;
  }
  if (node.kind === "scene-primitive") {
    return (
      node.capability === "core.route" ||
      node.capability === "core.arrow" ||
      node.capability === "core.elbow"
    );
  }
  return false;
}

function isMotionSignal(node: RenderDeclarationAst): boolean {
  return node.kind === "scene-primitive" && node.capability === "motion.signal";
}

function detectNativeBespoke(
  scene: SceneAst,
  slideId: string,
): SdkAuthoringSignature[] {
  const signatures: SdkAuthoringSignature[] = [];
  const declarations = scene.renderDeclarations;

  let connectorCount = 0;
  let firstConnectorRange: SourceRange | undefined;
  let paintedPathCount = 0;
  let motionSignalCount = 0;
  let motionSignalRange: SourceRange | undefined;

  for (const declaration of declarations) {
    if (isPaintedPath(declaration)) {
      paintedPathCount += 1;
    }
    if (isMotionSignal(declaration)) {
      motionSignalCount += 1;
      motionSignalRange = motionSignalRange ?? declaration.sourceMap;
    }

    switch (declaration.kind) {
      case "rect":
        signatures.push(detectRectSignature(declaration, slideId));
        break;
      case "connector":
        connectorCount += 1;
        firstConnectorRange = firstConnectorRange ?? declaration.sourceMap;
        signatures.push(detectConnectorSignature(declaration, slideId));
        break;
      case "scene-primitive":
        signatures.push(...detectPrimitiveSignatures(declaration, slideId));
        if (
          declaration.capability === "core.route" ||
          declaration.capability === "core.elbow"
        ) {
          connectorCount += 1;
          firstConnectorRange = firstConnectorRange ?? declaration.sourceMap;
        }
        break;
      case "component-invocation":
        // Component invocations (`sdk.*`, `aiperf.*`, or opaque) are the
        // migration target and are always permitted.
        break;
    }
  }

  // Aggregate structural signatures: a chain of raw edges is a pipeline, and a
  // painted path paired with a motion signal is a flow.
  if (connectorCount >= 3 && firstConnectorRange !== undefined) {
    signatures.push(
      makeSignature(
        PIPELINE_SIGNATURE,
        slideId,
        firstConnectorRange,
        `${connectorCount} raw edges`,
      ),
    );
  }
  if (paintedPathCount >= 1 && motionSignalCount >= 1) {
    signatures.push(
      makeSignature(
        FLOW_SIGNATURE,
        slideId,
        motionSignalRange ?? firstConnectorRange ?? unknownRange,
      ),
    );
  }

  return signatures;
}

// ---------------------------------------------------------------------------
// IR / provenance structural detection (non-SDK nodes only).
// ---------------------------------------------------------------------------

function nodeCapability(node: RenderNodeIr): string {
  return node.capabilityId ?? node.capability ?? node.kind;
}

function childrenOf(node: RenderNodeIr): readonly RenderNodeIr[] {
  if (node.kind === "group" || node.kind === "component") {
    return node.children;
  }
  return [];
}

function isHeaderChromeGeometry(node: RenderNodeIr): boolean {
  const { geometry } = node;
  return (
    geometry.x === HEADER_CHROME_GEOMETRY.x &&
    geometry.y === HEADER_CHROME_GEOMETRY.y &&
    geometry.width === HEADER_CHROME_GEOMETRY.width &&
    geometry.height === HEADER_CHROME_GEOMETRY.height
  );
}

function hasPulseStyle(node: RenderNodeIr): boolean {
  const pulse = (node.style as Record<string, unknown>).pulse;
  return pulse === true;
}

function detectIrStructural(
  scene: SceneIr,
  slideId: string,
): SdkAuthoringSignature[] {
  const signatures: SdkAuthoringSignature[] = [];

  const walk = (node: RenderNodeIr): void => {
    // Nodes generated by an SDK factory carry provenance and are exempt.
    if (node.sdkOrigin === undefined) {
      const capability = nodeCapability(node);
      if (capability === "core.header" && isHeaderChromeGeometry(node)) {
        signatures.push(
          makeSignature(DUP_HEADER_SIGNATURE, slideId, node.sourceMap, node.id),
        );
      }
      if (capability === "motion.pulse" || hasPulseStyle(node)) {
        signatures.push(
          makeSignature(PULSE_PROP_SIGNATURE, slideId, node.sourceMap, node.id),
        );
      }
    }
    for (const child of childrenOf(node)) {
      walk(child);
    }
  };

  for (const root of scene.roots) {
    walk(root);
  }
  return signatures;
}

// ---------------------------------------------------------------------------
// Public detection + validation entry points.
// ---------------------------------------------------------------------------

function dedupeSignatures(
  signatures: readonly SdkAuthoringSignature[],
): SdkAuthoringSignature[] {
  const seen = new Set<string>();
  const out: SdkAuthoringSignature[] = [];
  for (const signature of signatures) {
    const key = `${signature.code}|${signature.slideId}|${signature.sourceRange.start.offset}|${signature.sourceRange.end.offset}|${signature.detail ?? ""}`;
    if (seen.has(key)) {
      continue;
    }
    seen.add(key);
    out.push(signature);
  }
  return out;
}

/**
 * Detects prohibited authoring signatures in one scene.
 *
 * A package-form scene reports a single wholesale signature; enumerating its
 * internals would be redundant since the whole scene must migrate. Native
 * scenes are scanned for raw primitives authored outside `freeform` blocks, and
 * the lowered `SceneIr` (when provided) is scanned for non-SDK structural
 * signatures using compiler-only provenance.
 */
export function detectSdkAuthoringSignatures(
  input: SdkAuthoringSceneInput,
): SdkAuthoringSignature[] {
  const fallback = input.sourceRange ?? input.scene?.sourceMap ?? unknownRange;
  const raw = classifyRawScene(input.rawScene, fallback);

  if (raw.kind === "package") {
    return [
      makeSignature(PACKAGE_FORM_SIGNATURE, input.slideId, raw.sourceRange),
    ];
  }

  const signatures: SdkAuthoringSignature[] = [];
  if (raw.kind === "native") {
    signatures.push(...detectNativeBespoke(raw.scene, input.slideId));
  }
  if (input.scene !== undefined) {
    signatures.push(...detectIrStructural(input.scene, input.slideId));
  }
  return dedupeSignatures(signatures);
}

function signatureToDiagnostic(
  signature: SdkAuthoringSignature,
  severity: "error" | "warning",
): Diagnostic {
  const detail =
    signature.detail !== undefined ? ` ("${signature.detail}")` : "";
  return diagnostic(
    signature.code,
    severity,
    `Prohibited ${signature.signature}${detail} in "${signature.slideId}"; author with ${signature.replacement}.`,
    signature.sourceRange,
    `Replace with ${signature.replacement} (unique illustration primitives belong in an explicit freeform { … } block).`,
  );
}

/**
 * Runs the strict SDK-authoring gate over one or more scenes.
 *
 * Enforcement is phased through `options.policy` (default `"strict"`). `"off"`
 * skips detection entirely, `"report"` surfaces warnings without failing, and
 * `"strict"` fails when any prohibited signature is found.
 */
export function validateSdkAuthoring(
  scenes: SdkAuthoringSceneInput | readonly SdkAuthoringSceneInput[],
  options: SdkAuthoringOptions = {},
): Result<void> {
  const policy = options.policy ?? "strict";
  if (policy === "off") {
    return { ok: true, value: undefined, diagnostics: [] };
  }

  const inputs = Array.isArray(scenes)
    ? (scenes as readonly SdkAuthoringSceneInput[])
    : [scenes as SdkAuthoringSceneInput];

  const signatures = inputs.flatMap((input) =>
    detectSdkAuthoringSignatures(input),
  );

  const severity = policy === "strict" ? "error" : "warning";
  const diagnostics = signatures.map((signature) =>
    signatureToDiagnostic(signature, severity),
  );

  if (policy === "strict" && signatures.length > 0) {
    return { ok: false, diagnostics };
  }
  return { ok: true, value: undefined, diagnostics };
}
