# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""DataFrame construction and figure enrichment helpers for the dashboard."""

import logging
import math
from typing import Any

import pandas as pd
import plotly.graph_objects as go

_logger = logging.getLogger(__name__)


def extract_metric_value(run, metric_name: str, stat: str = "p50") -> float | None:
    """
    Extract a metric value from a run with specified stat.

    Args:
        run: RunData object
        metric_name: Name of the metric (e.g., 'time_to_first_token')
        stat: Statistic to extract (e.g., 'p50', 'avg', 'max')

    Returns:
        Metric value or None if not available
    """
    metric = run.get_metric(metric_name)
    if metric is None:
        return None

    if hasattr(metric, "stats"):
        # MetricResult object
        return getattr(metric.stats, stat, None)
    elif isinstance(metric, dict):
        # Dict format
        return metric.get(stat)

    return None


def _convert_to_numeric(value: Any, context: str = "") -> float | int | None:
    """
    Convert a value to numeric type (int or float) with error handling.

    Args:
        value: Value to convert (could be str, int, float, None, etc.)
        context: Context string for error logging (e.g., "metric=latency, stat=p50")

    Returns:
        Numeric value (int or float) or None if conversion fails or value is None
    """
    if value is None:
        return None

    if isinstance(value, (int, float)):
        if isinstance(value, float) and (math.isnan(value) or math.isinf(value)):
            return value
        return value

    if isinstance(value, str):
        value = value.strip()
        if not value:
            return None

    try:
        if isinstance(value, str) and "." not in value:
            return int(value)
        return float(value)
    except (ValueError, TypeError):
        _logger.warning(f"Could not convert value to numeric: {value!r} ({context})")
        return None


def _match_trace_point_to_run_idx(
    trace: Any,
    i: int,
    x_val: float,
    y_val: float,
    *,
    df: pd.DataFrame,
    x_metric: str,
    y_metric: str,
) -> dict:
    """Build a single customdata entry for a trace point by matching it to a DataFrame row.

    Uses coordinate-based matching with float tolerance so both single-trace and
    multi-trace (grouped) plots resolve back to the correct run_idx.
    """
    matches = df[
        (abs(df[x_metric] - x_val) < 0.001) & (abs(df[y_metric] - y_val) < 0.001)
    ]

    if matches.empty:
        # No match — keep original customdata if present, else empty.
        if (
            hasattr(trace, "customdata")
            and trace.customdata is not None
            and i < len(trace.customdata)
        ):
            return trace.customdata[i]
        return {}

    run_idx = int(matches.iloc[0]["run_idx"])

    existing_data = None
    if (
        hasattr(trace, "customdata")
        and trace.customdata is not None
        and i < len(trace.customdata)
    ):
        existing_data = trace.customdata[i]

    if isinstance(existing_data, str):
        return {"text": existing_data, "run_idx": run_idx}
    if isinstance(existing_data, dict):
        existing_data["run_idx"] = run_idx
        return existing_data
    return {"run_idx": run_idx}


def add_run_idx_to_figure(fig: go.Figure, df: pd.DataFrame) -> go.Figure:
    """
    Post-process figure to add run_idx to customdata for config viewer.

    This adapter ensures that plots generated by core PlotGenerator can work
    with the config modal click handler. It uses coordinate-based matching to
    handle both single-trace and multi-trace (grouped) plots correctly.

    Args:
        fig: Plotly Figure object from PlotGenerator
        df: DataFrame with run_idx column and metric columns

    Returns:
        Updated Figure with run_idx enriched in customdata
    """
    if "run_idx" not in df.columns or df.empty:
        return fig

    # Identify metric columns (exclude metadata)
    metric_cols = [
        c
        for c in df.columns
        if c not in ["model", "concurrency", "run_idx", "run_name"]
    ]

    if len(metric_cols) < 2:
        return fig

    x_metric, y_metric = metric_cols[0], metric_cols[1]

    for trace in fig.data:
        # Skip traces without x/y data
        if not hasattr(trace, "x") or not hasattr(trace, "y"):
            continue

        # Skip shadow traces (hoverinfo='skip')
        if hasattr(trace, "hoverinfo") and trace.hoverinfo == "skip":
            continue

        # Create customdata from scratch if it doesn't exist
        new_customdata = [
            _match_trace_point_to_run_idx(
                trace,
                i,
                x_val,
                y_val,
                df=df,
                x_metric=x_metric,
                y_metric=y_metric,
            )
            for i, (x_val, y_val) in enumerate(zip(trace.x, trace.y, strict=True))
        ]

        if new_customdata:
            trace.customdata = new_customdata

    return fig


def _build_run_row(
    run,
    idx: int,
    *,
    x_metric: str,
    x_stat: str,
    x_val: Any,
    y_metric: str,
    y_stat: str,
    y_val: Any,
) -> dict:
    """Build a single DataFrame row dict for a run with valid x/y values."""
    return {
        x_metric: _convert_to_numeric(x_val, f"x_metric={x_metric}, stat={x_stat}"),
        y_metric: _convert_to_numeric(y_val, f"y_metric={y_metric}, stat={y_stat}"),
        "model": run.metadata.model or "Unknown",
        "concurrency": _convert_to_numeric(run.metadata.concurrency, "concurrency")
        or 0,
        "run_idx": idx,
        "run_name": run.metadata.run_name,
        "experiment_type": run.metadata.experiment_type,
        "experiment_group": run.metadata.experiment_group,
    }


def _log_excluded_runs(
    excluded_runs: list[str], total_runs: int, included: int
) -> list[str]:
    """Emit warnings about excluded runs and return user-visible warning strings."""
    if not excluded_runs:
        return []
    warning = f"{len(excluded_runs)} of {total_runs} runs excluded (missing metrics)"
    excluded_preview = ", ".join(excluded_runs[:5])
    if len(excluded_runs) > 5:
        excluded_preview += " ..."
    _logger.warning(
        f"{len(excluded_runs)} of {total_runs} runs excluded due to missing metrics. "
        f"Excluded: {excluded_preview}. Plotting with {included} runs."
    )
    return [warning]


def _coerce_numeric_columns(
    df: pd.DataFrame, *, x_metric: str, y_metric: str
) -> list[str]:
    """Coerce metric/concurrency columns to numeric in-place and return NaN warnings."""
    df[x_metric] = pd.to_numeric(df[x_metric], errors="coerce")
    df[y_metric] = pd.to_numeric(df[y_metric], errors="coerce")
    df["concurrency"] = pd.to_numeric(df["concurrency"], errors="coerce")
    df["run_idx"] = df["run_idx"].astype(int)

    x_nan_count = df[x_metric].isna().sum()
    y_nan_count = df[y_metric].isna().sum()
    if x_nan_count > 0 or y_nan_count > 0:
        return [
            f"Type conversion: {x_nan_count} invalid {x_metric} values, "
            f"{y_nan_count} invalid {y_metric} values (converted to NaN)"
        ]
    return []


def runs_to_dataframe(
    runs: list,
    *,
    x_metric: str,
    x_stat: str,
    y_metric: str,
    y_stat: str,
) -> dict:
    """
    Convert list of RunData to DataFrame for plotting.

    Args:
        runs: List of RunData objects
        x_metric: Name of x-axis metric
        x_stat: Requested statistic for x-axis (p50, p90, avg, etc.)
        y_metric: Name of y-axis metric
        y_stat: Requested statistic for y-axis

    Returns:
        Dict with keys:
            - df: DataFrame with columns: x_metric, y_metric, model, concurrency, run_idx, run_name
            - x_stat_actual: Stat used for x-axis (same as x_stat)
            - y_stat_actual: Stat used for y-axis (same as y_stat)
            - warnings: List of warning messages
    """
    data: list[dict] = []
    excluded_runs: list[str] = []

    for idx, run in enumerate(runs):
        x_val = extract_metric_value(run, x_metric, x_stat)
        y_val = extract_metric_value(run, y_metric, y_stat)

        if x_val is not None and y_val is not None:
            data.append(
                _build_run_row(
                    run,
                    idx,
                    x_metric=x_metric,
                    x_stat=x_stat,
                    x_val=x_val,
                    y_metric=y_metric,
                    y_stat=y_stat,
                    y_val=y_val,
                )
            )
        else:
            excluded_runs.append(f"{run.metadata.run_name or f'run_{idx}'}")

    warnings = _log_excluded_runs(excluded_runs, len(runs), len(data))

    df = pd.DataFrame(data)
    if not df.empty:
        warnings.extend(
            _coerce_numeric_columns(df, x_metric=x_metric, y_metric=y_metric)
        )

    return {
        "df": df,
        "x_stat_actual": x_stat,
        "y_stat_actual": y_stat,
        "warnings": list(dict.fromkeys(warnings)),
    }


def prepare_timeseries_dataframe(df: pd.DataFrame) -> tuple[pd.DataFrame, str]:
    """
    Prepare DataFrame for time-series plotting by ensuring x-axis column exists.

    Handles the case where request_number column is missing and DataFrame
    uses default RangeIndex. Converts index to a proper column to avoid
    KeyError when plotting functions access df[x_col].

    Args:
        df: DataFrame with per-request data

    Returns:
        Tuple of (prepared_df, x_column_name) where:
        - prepared_df: DataFrame with guaranteed x-axis column
        - x_column_name: Name of the x-axis column to use
    """
    if "request_number" in df.columns:
        return df, "request_number"

    # Check if index has a meaningful name
    if df.index.name and df.index.name != "index":
        # Reset index to make it a column
        df_copy = df.reset_index()
        return df_copy, df.index.name

    # Default RangeIndex case: convert index to request_number column
    df_copy = df.copy()
    df_copy["request_number"] = df_copy.index
    return df_copy, "request_number"
