# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aiperf-workload
rules:
- apiGroups: ["aiperf.nvidia.com"]
  resources: ["aiperfjobs/status"]
  verbs: ["get", "patch", "update"]
- apiGroups: ["aiperf.nvidia.com"]
  resources: ["aiperfjobs"]
  verbs: ["get", "patch"]
