# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""
Plot package for AIPerf profiling results.

This package provides tools for plotting and analyzing AIPerf profiling data,
including data loading, plot generation, and various output modes (PNG, HTML, dashboard).
"""

__version__ = "0.1.0"
from aiperf.plot.cli_runner import (
    run_plot_controller,
)
from aiperf.plot.config import (
    PlotConfig,
    logger,
)
from aiperf.plot.constants import (
    ALL_STAT_KEYS,
    AVAILABLE_STATS,
    DARK_THEME_COLORS,
    DEFAULT_OUTPUT_DIR,
    DEFAULT_PERCENTILE,
    DEFAULT_PERCENTILES,
    DEFAULT_PLOT_DPI,
    DEFAULT_PLOT_HEIGHT,
    DEFAULT_PLOT_WIDTH,
    DEFAULT_PNG_OUTPUT_DIR,
    DERIVED_METRIC_DIRECTIONS,
    LIGHT_THEME_COLORS,
    NON_METRIC_KEYS,
    NVIDIA_BORDER_DARK,
    NVIDIA_BORDER_LIGHT,
    NVIDIA_CARD_BG,
    NVIDIA_DARK,
    NVIDIA_DARK_BG,
    NVIDIA_GOLD,
    NVIDIA_GRAY,
    NVIDIA_GREEN,
    NVIDIA_TEXT_LIGHT,
    NVIDIA_WHITE,
    OUTLIER_RED,
    PLOT_FONT_FAMILY,
    PLOT_LOG_FILE,
    PROFILE_EXPORT_AIPERF_JSON,
    PROFILE_EXPORT_GPU_TELEMETRY_JSONL,
    PROFILE_EXPORT_JSONL,
    PROFILE_EXPORT_TIMESLICES_CSV,
    PlotMode,
    PlotTheme,
)
from aiperf.plot.core import (
    DEFAULT_IGNORE_PARAMS,
    DataLoader,
    DataSource,
    DerivedMetricCalculator,
    ExperimentClassificationConfig,
    MetricSpec,
    ModeDetector,
    PlotGenerator,
    PlotSpec,
    PlotType,
    PlotTypeHandlerFactory,
    PlotTypeHandlerProtocol,
    RunData,
    RunMetadata,
    Style,
    TimeSlicePlotSpec,
    VisualizationMode,
    aggregate_gpu_telemetry,
    auto_select_group_by,
    auto_select_label_by,
    calculate_rolling_percentiles,
    calculate_throughput_events,
    detect_directional_outliers,
    detect_swept_parameters,
    flatten_config,
    get_nvidia_color_scheme,
    prepare_request_timeseries,
    prepare_timeslice_metrics,
    validate_request_uniformity,
)
from aiperf.plot.exceptions import (
    DataLoadError,
    ModeDetectionError,
    PlotError,
    PlotGenerationError,
)
from aiperf.plot.exporters import (
    BaseExporter,
    BasePNGExporter,
    MultiRunPNGExporter,
    SingleRunPNGExporter,
)
from aiperf.plot.handlers import (
    AreaHandler,
    BaseMultiRunHandler,
    BaseSingleRunHandler,
    DualAxisHandler,
    HistogramHandler,
    ParetoHandler,
    ScatterHandler,
    ScatterLineHandler,
    ScatterWithPercentilesHandler,
    TimeSliceHandler,
)
from aiperf.plot.logging import (
    setup_console_only_logging,
    setup_plot_logging,
)
from aiperf.plot.metric_names import (
    get_aggregated_metrics,
    get_all_metric_display_names,
    get_gpu_metrics,
    get_metric_display_name,
    get_request_metrics,
    get_timeslice_metrics,
)
from aiperf.plot.plot_controller import (
    PlotController,
)

__all__ = [
    "ALL_STAT_KEYS",
    "AVAILABLE_STATS",
    "AreaHandler",
    "BaseExporter",
    "BaseMultiRunHandler",
    "BasePNGExporter",
    "BaseSingleRunHandler",
    "DARK_THEME_COLORS",
    "DEFAULT_IGNORE_PARAMS",
    "DEFAULT_OUTPUT_DIR",
    "DEFAULT_PERCENTILE",
    "DEFAULT_PERCENTILES",
    "DEFAULT_PLOT_DPI",
    "DEFAULT_PLOT_HEIGHT",
    "DEFAULT_PLOT_WIDTH",
    "DEFAULT_PNG_OUTPUT_DIR",
    "DERIVED_METRIC_DIRECTIONS",
    "DataLoadError",
    "DataLoader",
    "DataSource",
    "DerivedMetricCalculator",
    "DualAxisHandler",
    "ExperimentClassificationConfig",
    "HistogramHandler",
    "LIGHT_THEME_COLORS",
    "MetricSpec",
    "ModeDetectionError",
    "ModeDetector",
    "MultiRunPNGExporter",
    "NON_METRIC_KEYS",
    "NVIDIA_BORDER_DARK",
    "NVIDIA_BORDER_LIGHT",
    "NVIDIA_CARD_BG",
    "NVIDIA_DARK",
    "NVIDIA_DARK_BG",
    "NVIDIA_GOLD",
    "NVIDIA_GRAY",
    "NVIDIA_GREEN",
    "NVIDIA_TEXT_LIGHT",
    "NVIDIA_WHITE",
    "OUTLIER_RED",
    "PLOT_FONT_FAMILY",
    "PLOT_LOG_FILE",
    "PROFILE_EXPORT_AIPERF_JSON",
    "PROFILE_EXPORT_GPU_TELEMETRY_JSONL",
    "PROFILE_EXPORT_JSONL",
    "PROFILE_EXPORT_TIMESLICES_CSV",
    "ParetoHandler",
    "PlotConfig",
    "PlotController",
    "PlotError",
    "PlotGenerationError",
    "PlotGenerator",
    "PlotMode",
    "PlotSpec",
    "PlotTheme",
    "PlotType",
    "PlotTypeHandlerFactory",
    "PlotTypeHandlerProtocol",
    "RunData",
    "RunMetadata",
    "ScatterHandler",
    "ScatterLineHandler",
    "ScatterWithPercentilesHandler",
    "SingleRunPNGExporter",
    "Style",
    "TimeSliceHandler",
    "TimeSlicePlotSpec",
    "VisualizationMode",
    "aggregate_gpu_telemetry",
    "auto_select_group_by",
    "auto_select_label_by",
    "calculate_rolling_percentiles",
    "calculate_throughput_events",
    "detect_directional_outliers",
    "detect_swept_parameters",
    "flatten_config",
    "get_aggregated_metrics",
    "get_all_metric_display_names",
    "get_gpu_metrics",
    "get_metric_display_name",
    "get_nvidia_color_scheme",
    "get_request_metrics",
    "get_timeslice_metrics",
    "logger",
    "prepare_request_timeseries",
    "prepare_timeslice_metrics",
    "run_plot_controller",
    "setup_console_only_logging",
    "setup_plot_logging",
    "validate_request_uniformity",
]
