// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Compact vocabulary shared by native coding-corpus template renderers.

pub(super) const MODULES: &[&str] = &[
    "auth",
    "cache",
    "config",
    "database",
    "events",
    "handler",
    "logger",
    "metrics",
    "middleware",
    "pipeline",
    "processor",
    "registry",
    "router",
    "scheduler",
    "serializer",
    "service",
    "storage",
    "transport",
    "validator",
    "worker",
    "gateway",
    "inference",
    "tokenizer",
    "model_registry",
    "telemetry",
    "health_check",
];

pub(super) const CLASSES: &[&str] = &[
    "RequestHandler",
    "DataProcessor",
    "EventEmitter",
    "CacheManager",
    "ConnectionPool",
    "TaskScheduler",
    "MessageBroker",
    "StateManager",
    "ConfigLoader",
    "MetricsCollector",
    "RateLimiter",
    "CircuitBreaker",
    "BatchProcessor",
    "StreamReader",
    "SessionStore",
    "HealthMonitor",
    "WorkerPool",
    "ProtocolAdapter",
    "InferenceEngine",
    "BatchScheduler",
];

pub(super) const METHODS: &[&str] = &[
    "process",
    "handle",
    "validate",
    "transform",
    "execute",
    "initialize",
    "configure",
    "dispatch",
    "resolve",
    "serialize",
    "decode",
    "publish",
    "aggregate",
    "schedule",
    "allocate",
    "release",
    "flush",
    "authenticate",
    "checkpoint",
    "rollback",
    "reconcile",
    "prefetch",
    "retry",
    "persist",
    "drain",
    "forward",
    "evaluate",
];

pub(super) const VARS: &[&str] = &[
    "result",
    "data",
    "config",
    "context",
    "payload",
    "response",
    "request",
    "buffer",
    "cursor",
    "offset",
    "count",
    "batch",
    "chunk",
    "token",
    "record",
    "value",
    "state",
    "timeout",
    "retries",
    "capacity",
    "endpoint",
    "session",
    "trace_id",
    "tenant_id",
    "batch_size",
    "worker_id",
];

pub(super) const TYPES: &[&str] = &[
    "str",
    "int",
    "float",
    "bool",
    "bytes",
    "dict[str, object]",
    "list[str]",
    "Sequence[str]",
    "Mapping[str, object]",
    "Optional[str]",
];

pub(super) const ROUTES: &[&str] = &[
    "/api/v1/users",
    "/api/v1/items",
    "/api/v1/orders",
    "/api/v1/auth/login",
    "/api/v2/search",
    "/health",
    "/ready",
    "/metrics",
    "/api/v1/webhooks",
    "/api/v1/projects/{project_id}/runs",
];

pub(super) const TABLES: &[&str] = &[
    "users",
    "orders",
    "items",
    "sessions",
    "audit_log",
    "migrations",
    "api_keys",
    "rate_limits",
    "notifications",
    "job_queue",
];

pub(super) const ERRORS: &[&str] = &[
    "connection refused",
    "timeout exceeded",
    "permission denied",
    "resource not found",
    "invalid argument",
    "out of memory",
    "deadlock detected",
    "rate limit exceeded",
    "authentication failed",
    "schema validation error",
    "serialization error",
    "missing required field",
    "duplicate key",
    "constraint violation",
    "connection pool exhausted",
    "circuit breaker open",
];

pub(super) const CUDA_ERRORS: &[&str] = &[
    "CUDA out of memory. Tried to allocate 2.00 GiB",
    "Expected all tensors to be on the same device",
    "NCCL communicator was aborted on rank 0",
    "cuDNN error: CUDNN_STATUS_NOT_SUPPORTED",
    "FlashAttention only supports Ampere GPUs or newer",
    "CUDA error: device-side assert triggered",
];

pub(super) const MODELS: &[&str] = &[
    "meta-llama/Llama-3.1-8B",
    "meta-llama/Llama-3.1-70B",
    "mistralai/Mixtral-8x7B-v0.1",
    "google/gemma-2-9b",
    "Qwen/Qwen2.5-72B",
    "nvidia/Llama-3.1-Nemotron-70B-Instruct",
];

pub(super) const COMMANDS: &[&str] = &[
    "git diff HEAD~1",
    "docker compose up -d",
    "kubectl get pods -n default",
    "cargo test --workspace",
    "go test -v ./...",
    "npm test",
    "pytest -xvs tests/",
    "ruff check .",
    "curl -s http://localhost:8080/health",
    "kubectl logs -f deploy/api --tail=100",
    "terraform plan -out=tfplan",
    "redis-cli INFO memory",
];

pub(super) const FILES: &[&str] = &[
    "src/main.py",
    "src/config.py",
    "tests/test_main.py",
    "pkg/api/server.go",
    "internal/service/worker.go",
    "src/lib.rs",
    "src/handler.rs",
    "src/index.ts",
    "src/services/auth.service.ts",
    "Dockerfile",
    "pyproject.toml",
    ".github/workflows/ci.yml",
    "kubernetes/deployment.yaml",
];

pub(super) const PROMPT_VERBS: &[&str] = &[
    "implement",
    "debug",
    "refactor",
    "optimize",
    "review",
    "test",
    "document",
    "migrate",
    "instrument",
    "harden",
];
