# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Integration checks for generated AIPerf config schema maintenance."""

import copy
import json
from pathlib import Path
from typing import Any

import pytest
from jsonschema import Draft202012Validator
from pydantic import ValidationError

from aiperf.config import AIPerfConfig
from tools.generate_config_schema import ConfigSchemaGenerator

REPO_ROOT = Path(__file__).resolve().parents[3]
GENERATOR_PATH = REPO_ROOT / "tools" / "generate_config_schema.py"
SCHEMA_PATH = (
    REPO_ROOT / "src" / "aiperf" / "config" / "schema" / "aiperf-config.schema.json"
)


def _generated_schema() -> dict[str, Any]:
    result = ConfigSchemaGenerator().generate()
    return json.loads(result.files[0].content)


def _schema_error_messages(schema: dict[str, Any], config: dict[str, Any]) -> list[str]:
    validator = Draft202012Validator(schema)
    return [error.message for error in validator.iter_errors(config)]


def _minimal_benchmark_config(**benchmark_overrides: Any) -> dict[str, Any]:
    benchmark: dict[str, Any] = {
        "models": "llama-test",
        "endpoint": {"urls": ["http://localhost:8000/v1/chat/completions"]},
        "datasets": [
            {
                "name": "main",
                "type": "synthetic",
                "entries": 1,
                "prompts": {"isl": {"value": 512}, "osl": {"value": 128}},
            }
        ],
        "phases": [
            {
                "name": "profiling",
                "type": "concurrency",
                "requests": 1,
                "concurrency": 1,
            }
        ],
    }
    benchmark.update(benchmark_overrides)
    return {"benchmark": benchmark}


def _assert_schema_accepts(schema: dict[str, Any], config: dict[str, Any]) -> None:
    assert _schema_error_messages(schema, config) == []


def test_config_schema_generator_is_integrated_with_dev_workflow() -> None:
    assert GENERATOR_PATH.exists(), (
        "tools/generate_config_schema.py must generate the config schema"
    )
    generator_source = GENERATOR_PATH.read_text(encoding="utf-8")
    assert 'CONFIG_DIR = Path("src/aiperf/config")' in generator_source
    assert 'SCHEMA_FILE = SCHEMA_DIR / "aiperf-config.schema.json"' in generator_source
    assert "config_v2" not in generator_source

    makefile_source = (REPO_ROOT / "Makefile").read_text(encoding="utf-8")
    assert "generate-config-schema" in makefile_source
    assert "check-config-schema" in makefile_source
    assert "python -m tools.generate_config_schema --check" in makefile_source

    pre_commit_source = (REPO_ROOT / ".pre-commit-config.yaml").read_text(
        encoding="utf-8"
    )
    assert "id: generate-config-schema" in pre_commit_source
    assert (
        "^src/aiperf/config/.*\\.py$|^tools/generate_config_schema\\.py$"
        in pre_commit_source
    )

    schema_source = SCHEMA_PATH.read_text(encoding="utf-8")
    assert "Auto-generated by tools/generate_config_schema.py" in schema_source


def test_generated_schema_accepts_runtime_scalar_prompt_distributions() -> None:
    schema = _generated_schema()
    config = _minimal_benchmark_config(
        datasets=[
            {
                "name": "main",
                "type": "synthetic",
                "entries": 1,
                "prompts": {"isl": 512, "osl": 128},
            }
        ]
    )

    parsed = AIPerfConfig.model_validate(copy.deepcopy(config))

    assert parsed.benchmark.datasets[0].prompts is not None
    assert parsed.benchmark.datasets[0].prompts.isl.expected_value == 512
    assert parsed.benchmark.datasets[0].prompts.osl.expected_value == 128
    _assert_schema_accepts(schema, config)


def test_generated_schema_rejects_benchmark_missing_dataset_like_runtime() -> None:
    schema = _generated_schema()
    config = _minimal_benchmark_config()
    del config["benchmark"]["datasets"]

    with pytest.raises(ValidationError):
        AIPerfConfig.model_validate(copy.deepcopy(config))

    assert _schema_error_messages(schema, config) != []


def test_generated_schema_accepts_runtime_single_dict_phases_shorthand() -> None:
    schema = _generated_schema()
    config = _minimal_benchmark_config(
        phases={"type": "concurrency", "requests": 1, "concurrency": 1}
    )

    parsed = AIPerfConfig.model_validate(copy.deepcopy(config))

    assert len(parsed.benchmark.phases) == 1
    assert parsed.benchmark.phases[0].name == "profiling"
    _assert_schema_accepts(schema, config)
