// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Golden byte-parity tests for the timeslice sink.
//!
//! The expected `timeslices.{json,csv}` bytes are generated by driving the real
//! Python serializers (`timeslice_metrics_json_exporter._generate_content` /
//! `timeslice_metrics_csv_exporter._generate_content` via
//! `native_report._project_native_timeslices` → `_legacy_stats` → `to_json_result`)
//! over the same synthetic slice values, then pinned here. The single deviation
//! is the Python JSON's outer `input_config` object, which the native report
//! cannot carry (see the module docs); the pinned JSON is the exact per-slice
//! payload minus that key.

use std::collections::BTreeMap;

use super::*;
use crate::metrics_core::report::{
    MetricEntry, MetricSeries, ReportCounterStats, ReportDistributionStats, ReportTimeslice,
};
use crate::metrics_core::{AccumulatorSummary, NativeReport};

/// Build a distribution stats block with finite values.
fn dist(
    count: usize,
    avg: f64,
    min: f64,
    max: f64,
    std: Option<f64>,
    pcts: &[(&str, f64)],
) -> ReportStats {
    ReportStats::Distribution(ReportDistributionStats {
        count: Some(count),
        avg: Some(ReportValue::Finite(avg)),
        min: Some(ReportValue::Finite(min)),
        max: Some(ReportValue::Finite(max)),
        std: std.map(ReportValue::Finite),
        percentiles: pcts
            .iter()
            .map(|(key, value)| (key.to_string(), ReportValue::Finite(*value)))
            .collect(),
    })
}

/// Build a counter stats block (`total` drives avg/min/max/sum in the compatibility shape).
fn counter(total: f64, rate: f64) -> ReportStats {
    ReportStats::Counter(ReportCounterStats {
        total: ReportValue::Finite(total),
        rate: Some(ReportValue::Finite(rate)),
    })
}

/// Build one timeslice.
fn slice(start_ns: i64, end_ns: i64, complete: bool, stats: ReportStats) -> ReportTimeslice {
    ReportTimeslice {
        start_ns,
        end_ns,
        complete,
        stats,
    }
}

/// Build a single-series metric entry with the given timeslices.
fn entry(
    unit: &str,
    metric_type: &'static str,
    aggregate: ReportStats,
    timeslices: Vec<ReportTimeslice>,
) -> MetricEntry {
    MetricEntry {
        metric_type,
        unit: unit.to_string(),
        group: "default",
        higher_is_better: false,
        series: vec![MetricSeries {
            labels: None,
            endpoint_url: None,
            stats: aggregate,
            timeslices,
        }],
    }
}

/// Two-slice report: slice 0 complete, slice 1 partial, plus an INTERNAL metric
/// (`credit_drop_latency`) that must be filtered out of both exports.
fn two_slice_report() -> NativeReport {
    let mut metrics: BTreeMap<String, MetricEntry> = BTreeMap::new();

    metrics.insert(
        "output_sequence_length".to_string(),
        entry(
            "tokens",
            "distribution",
            dist(10, 128.0, 100.0, 150.0, Some(12.0), &[("p50", 128.0)]),
            vec![
                slice(
                    1000,
                    2000,
                    true,
                    dist(10, 128.0, 100.0, 150.0, Some(12.0), &[("p50", 128.0)]),
                ),
                slice(
                    2000,
                    3000,
                    false,
                    dist(4, 130.0, 110.0, 140.0, Some(8.0), &[("p50", 130.0)]),
                ),
            ],
        ),
    );

    metrics.insert(
        "request_count".to_string(),
        entry(
            "requests",
            "counter",
            counter(14.0, 4.5),
            vec![
                slice(1000, 2000, true, counter(10.0, 5.0)),
                slice(2000, 3000, false, counter(4.0, 4.0)),
            ],
        ),
    );

    metrics.insert(
        "request_latency".to_string(),
        entry(
            "ms",
            "distribution",
            dist(14, 13.0, 8.0, 22.0, Some(3.0), &[]),
            vec![
                slice(
                    1000,
                    2000,
                    true,
                    dist(
                        10,
                        12.5,
                        8.0,
                        20.0,
                        Some(3.25),
                        // Deliberately scrambled input order to prove canonical
                        // p1,p5,p10,p50,p99 output ordering (not BTreeMap lexical).
                        &[
                            ("p99", 20.0),
                            ("p1", 8.0),
                            ("p10", 11.0),
                            ("p5", 9.5),
                            ("p50", 12.0),
                        ],
                    ),
                ),
                slice(
                    2000,
                    3000,
                    false,
                    dist(4, 15.0, 9.0, 22.0, None, &[("p50", 15.0)]),
                ),
            ],
        ),
    );

    // INTERNAL metric: present with timeslices, must never reach either file.
    metrics.insert(
        "credit_drop_latency".to_string(),
        entry(
            "ms",
            "distribution",
            dist(4, 1.0, 1.0, 2.0, None, &[]),
            vec![
                slice(
                    1000,
                    2000,
                    true,
                    dist(3, 1.0, 1.0, 1.0, Some(0.0), &[("p50", 1.0)]),
                ),
                slice(2000, 3000, false, dist(1, 2.0, 2.0, 2.0, None, &[])),
            ],
        ),
    );

    let mut report = NativeReport::new(&AccumulatorSummary::new(), None);
    report.metrics = metrics;
    report
}

const EXPECTED_JSON: &str = r#"{
  "timeslices": [
    {
      "start_ns": 1000,
      "end_ns": 2000,
      "output_sequence_length": {
        "unit": "tokens",
        "avg": 128.0,
        "p50": 128.0,
        "min": 100.0,
        "max": 150.0,
        "std": 12.0,
        "count": 10
      },
      "request_count": {
        "unit": "requests",
        "avg": 10.0,
        "min": 10.0,
        "max": 10.0,
        "sum": 10.0
      },
      "request_latency": {
        "unit": "ms",
        "avg": 12.5,
        "p1": 8.0,
        "p5": 9.5,
        "p10": 11.0,
        "p50": 12.0,
        "p99": 20.0,
        "min": 8.0,
        "max": 20.0,
        "std": 3.25,
        "count": 10
      }
    },
    {
      "start_ns": 2000,
      "end_ns": 3000,
      "is_complete": false,
      "output_sequence_length": {
        "unit": "tokens",
        "avg": 130.0,
        "p50": 130.0,
        "min": 110.0,
        "max": 140.0,
        "std": 8.0,
        "count": 4
      },
      "request_count": {
        "unit": "requests",
        "avg": 4.0,
        "min": 4.0,
        "max": 4.0,
        "sum": 4.0
      },
      "request_latency": {
        "unit": "ms",
        "avg": 15.0,
        "p50": 15.0,
        "min": 9.0,
        "max": 22.0,
        "count": 4
      }
    }
  ]
}"#;

/// Exact Python `csv.writer` output (CRLF terminators, `.2f` values). `count` is
/// intentionally absent; INTERNAL `credit_drop_latency` is filtered.
fn expected_csv() -> String {
    let rows = [
        "Timeslice,Start_NS,End_NS,Metric,Unit,Stat,Value",
        "0,1000,2000,Output Sequence Length,tokens,avg,128.00",
        "0,1000,2000,Output Sequence Length,tokens,min,100.00",
        "0,1000,2000,Output Sequence Length,tokens,max,150.00",
        "0,1000,2000,Output Sequence Length,tokens,p50,128.00",
        "0,1000,2000,Output Sequence Length,tokens,std,12.00",
        "0,1000,2000,Request Count,requests,avg,10.00",
        "0,1000,2000,Request Count,requests,min,10.00",
        "0,1000,2000,Request Count,requests,max,10.00",
        "0,1000,2000,Request Count,requests,sum,10.00",
        "0,1000,2000,Request Latency,ms,avg,12.50",
        "0,1000,2000,Request Latency,ms,min,8.00",
        "0,1000,2000,Request Latency,ms,max,20.00",
        "0,1000,2000,Request Latency,ms,p1,8.00",
        "0,1000,2000,Request Latency,ms,p5,9.50",
        "0,1000,2000,Request Latency,ms,p10,11.00",
        "0,1000,2000,Request Latency,ms,p50,12.00",
        "0,1000,2000,Request Latency,ms,p99,20.00",
        "0,1000,2000,Request Latency,ms,std,3.25",
        "1,2000,3000,Output Sequence Length,tokens,avg,130.00",
        "1,2000,3000,Output Sequence Length,tokens,min,110.00",
        "1,2000,3000,Output Sequence Length,tokens,max,140.00",
        "1,2000,3000,Output Sequence Length,tokens,p50,130.00",
        "1,2000,3000,Output Sequence Length,tokens,std,8.00",
        "1,2000,3000,Request Count,requests,avg,4.00",
        "1,2000,3000,Request Count,requests,min,4.00",
        "1,2000,3000,Request Count,requests,max,4.00",
        "1,2000,3000,Request Count,requests,sum,4.00",
        "1,2000,3000,Request Latency,ms,avg,15.00",
        "1,2000,3000,Request Latency,ms,min,9.00",
        "1,2000,3000,Request Latency,ms,max,22.00",
        "1,2000,3000,Request Latency,ms,p50,15.00",
    ];
    let mut out = String::new();
    for row in rows {
        out.push_str(row);
        out.push_str("\r\n");
    }
    out
}

/// Unique per-test scratch directory under the OS temp dir.
fn scratch(name: &str) -> std::path::PathBuf {
    let dir = std::env::temp_dir().join(format!("aiperf_ts_test_{}_{}", std::process::id(), name));
    let _ = std::fs::remove_dir_all(&dir);
    dir
}

/// The frontend registry projection reproducing the two-slice report's expected
/// filtering and headers: `credit_drop_latency` is the registered INTERNAL tag
/// dropped from both files; the retained metrics carry their `MetricRegistry`
/// Title-Case headers; no metric is scalar-tier. This is the exact shape
/// `_timeslice_frontend_projection` supplies on the product path.
fn registry_timeslice(json: bool, csv: bool, stem: Option<String>) -> TimesliceExportConfig {
    let header_map = [
        ("output_sequence_length", "Output Sequence Length"),
        ("request_count", "Request Count"),
        ("request_latency", "Request Latency"),
    ]
    .iter()
    .map(|(tag, header)| ((*tag).to_string(), (*header).to_string()))
    .collect();
    let filtered_tags = ["credit_drop_latency"]
        .iter()
        .map(|tag| (*tag).to_string())
        .collect();
    TimesliceExportConfig {
        json,
        csv,
        stem,
        input_config: Value::Null,
        header_map,
        filtered_tags,
        scalar_tags: Default::default(),
    }
}

fn config(json: bool, csv: bool) -> ExportConfig {
    ExportConfig {
        timeslice: registry_timeslice(json, csv, None),
        ..ExportConfig::default()
    }
}

#[test]
fn json_and_csv_match_python_golden() {
    let dir = scratch("golden");
    let report = two_slice_report();

    TimesliceExporter
        .export(&report, &dir, &config(true, true))
        .unwrap();

    let json = std::fs::read_to_string(dir.join("profile_export_aiperf_timeslices.json")).unwrap();
    assert_eq!(
        json, EXPECTED_JSON,
        "timeslice JSON must match Python bytes"
    );

    let csv = std::fs::read_to_string(dir.join("profile_export_aiperf_timeslices.csv")).unwrap();
    assert_eq!(csv, expected_csv(), "timeslice CSV must match Python bytes");

    std::fs::remove_dir_all(&dir).unwrap();
}

#[test]
fn json_only_gating_skips_csv() {
    let dir = scratch("json_only");
    TimesliceExporter
        .export(&two_slice_report(), &dir, &config(true, false))
        .unwrap();

    assert!(dir.join("profile_export_aiperf_timeslices.json").exists());
    assert!(!dir.join("profile_export_aiperf_timeslices.csv").exists());
    std::fs::remove_dir_all(&dir).unwrap();
}

#[test]
fn custom_stem_names_both_files() {
    let dir = scratch("stem");
    let cfg = ExportConfig {
        timeslice: registry_timeslice(true, true, Some("run_0001".to_string())),
        ..ExportConfig::default()
    };
    TimesliceExporter
        .export(&two_slice_report(), &dir, &cfg)
        .unwrap();

    assert!(dir.join("run_0001_timeslices.json").exists());
    assert!(dir.join("run_0001_timeslices.csv").exists());
    std::fs::remove_dir_all(&dir).unwrap();
}

#[test]
fn no_timeslices_writes_nothing() {
    // A report whose metrics carry empty timeslice vectors: the Python exporter
    // raises DataExporterDisabled and no file is created.
    let dir = scratch("empty");
    let mut report = NativeReport::new(&AccumulatorSummary::new(), None);
    let mut metrics = BTreeMap::new();
    metrics.insert(
        "request_count".to_string(),
        entry("requests", "counter", counter(1.0, 1.0), Vec::new()),
    );
    report.metrics = metrics;

    TimesliceExporter
        .export(&report, &dir, &config(true, true))
        .unwrap();

    // Nothing written; the directory is created but holds no timeslice files.
    assert!(!dir.join("profile_export_aiperf_timeslices.json").exists());
    assert!(!dir.join("profile_export_aiperf_timeslices.csv").exists());
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn partial_only_slice_emits_is_complete_false() {
    let dir = scratch("partial");
    let mut report = NativeReport::new(&AccumulatorSummary::new(), None);
    let mut metrics = BTreeMap::new();
    metrics.insert(
        "request_count".to_string(),
        entry(
            "requests",
            "counter",
            counter(4.0, 4.0),
            vec![slice(5000, 6000, false, counter(4.0, 4.0))],
        ),
    );
    report.metrics = metrics;

    TimesliceExporter
        .export(&report, &dir, &config(true, false))
        .unwrap();

    let json = std::fs::read_to_string(dir.join("profile_export_aiperf_timeslices.json")).unwrap();
    let expected = "{\n  \"timeslices\": [\n    {\n      \"start_ns\": 5000,\n      \"end_ns\": 6000,\n      \"is_complete\": false,\n      \"request_count\": {\n        \"unit\": \"requests\",\n        \"avg\": 4.0,\n        \"min\": 4.0,\n        \"max\": 4.0,\n        \"sum\": 4.0\n      }\n    }\n  ]\n}";
    assert_eq!(json, expected);
    std::fs::remove_dir_all(&dir).unwrap();
}

#[test]
fn frontend_input_config_is_wrapped_after_timeslices() {
    // A non-null `input_config` projection is spliced verbatim after the
    // `timeslices` array, in `TimesliceCollectionExportData` field order; the CSV
    // is unaffected.
    let dir = scratch("input_config");
    let cfg = ExportConfig {
        timeslice: TimesliceExportConfig {
            input_config: serde_json::json!({"endpoint": {"model_names": ["m"]}}),
            ..registry_timeslice(true, true, None)
        },
        ..ExportConfig::default()
    };
    TimesliceExporter
        .export(&two_slice_report(), &dir, &cfg)
        .unwrap();

    let json = std::fs::read_to_string(dir.join("profile_export_aiperf_timeslices.json")).unwrap();
    assert!(
        json.ends_with("  ],\n  \"input_config\": {\n    \"endpoint\": {\n      \"model_names\": [\n        \"m\"\n      ]\n    }\n  }\n}"),
        "input_config must be wrapped after the timeslices array:\n{json}"
    );
    // The CSV never carries input_config.
    let csv = std::fs::read_to_string(dir.join("profile_export_aiperf_timeslices.csv")).unwrap();
    assert!(!csv.contains("input_config"));

    std::fs::remove_dir_all(&dir).unwrap();
}

#[test]
fn disabled_config_is_not_enabled() {
    assert!(!TimesliceExporter.enabled(&ExportConfig::default()));
    assert!(TimesliceExporter.enabled(&config(true, false)));
    assert!(TimesliceExporter.enabled(&config(false, true)));
}
