// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! The generation-1 boundary ownership table.
//!
//! Every item that crosses the host/plugin boundary is enumerated here with the
//! facts a reviewer needs to reason about it without reading the call site:
//! which crate owns the declaration, what it takes and returns, who allocates
//! the returned storage, who drops it, the panic policy in force, and whether
//! it runs at startup or on the request hot path.
//!
//! The table is the machine-readable half of
//! `docs/specs/plugin-api-ownership.md`. The `check-plugin-api-ownership`
//! binary compares the two and fails when a row is missing from the spec, so a
//! new boundary item cannot land undocumented.

/// The precondition that makes every `alloc owner = plugin` /
/// `drop owner = host` row in [`GENERATION_1_SURFACE`] sound.
///
/// Library residency guarantees the drop glue is still mapped when the host
/// runs it; it says nothing about which allocator the free lands in. Rows that
/// transfer plugin-allocated storage to the host therefore additionally require
/// one global allocator across every loaded artifact. This constant is the
/// stated rule, not its enforcement: the loader that checks it lands with the
/// allocator provider.
pub const SHARED_ALLOCATOR_PRECONDITION: &str = "\
Every boundary row with alloc_owner = plugin and drop_owner = host requires \
that the host binary and every plugin cdylib link the same allocator. The \
aiperf binary installs mimalloc through aiperf-allocator-provider; a plugin \
must declare the same provider as its #[global_allocator] before the host \
loads it. A cdylib that allocates from a different allocator produces heap \
corruption when the host drops the transferred value, because the free is \
issued to an allocator that never owned the block.";

/// Who allocates or drops the storage a boundary item names.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StorageOwner {
    /// The plugin library allocates or drops it. Plugin libraries stay resident
    /// for the whole process, so plugin-owned storage outlives every host value
    /// derived from it.
    Plugin,
    /// The host allocates or drops it.
    Host,
    /// The item transfers no storage: it borrows, copies, or returns a unit.
    None,
}

impl StorageOwner {
    /// The lowercase label used in the spec table.
    pub const fn label(&self) -> &'static str {
        match self {
            Self::Plugin => "plugin",
            Self::Host => "host",
            Self::None => "none",
        }
    }
}

/// When a boundary item is called relative to a benchmark run.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CallPhase {
    /// Called during load, registration, and plan validation, before any
    /// request is issued.
    Startup,
    /// Called per request or per token while a phase is running.
    HotPath,
}

impl CallPhase {
    /// The lowercase label used in the spec table.
    pub const fn label(&self) -> &'static str {
        match self {
            Self::Startup => "startup",
            Self::HotPath => "hot-path",
        }
    }
}

/// One boundary item and the ownership facts that govern it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct OwnershipRow {
    /// Fully qualified path of the item, exactly as the spec table names it.
    pub item: &'static str,
    /// The crate whose source declares the item.
    pub owning_crate: &'static str,
    /// Argument types in declaration order, or `()` for none.
    pub argument_types: &'static str,
    /// Return type, or `()`.
    pub return_type: &'static str,
    /// Who allocates the storage the item yields.
    pub allocation_owner: StorageOwner,
    /// Who drops that storage.
    pub drop_owner: StorageOwner,
    /// Whether the item is compiled under `panic = abort`.
    pub panic_abort: bool,
    /// When the item is called.
    pub phase: CallPhase,
}

/// The complete generation-1 boundary surface.
///
/// Every row is `panic = abort` and every row is startup-phase: generation 1
/// deliberately crosses the boundary only during load and registration, so no
/// per-request or per-token call pays a boundary cost yet.
///
/// Rows whose allocation owner is [`StorageOwner::Plugin`] and whose drop owner
/// is [`StorageOwner::Host`] are sound only under
/// [`SHARED_ALLOCATOR_PRECONDITION`].
pub const GENERATION_1_SURFACE: &[OwnershipRow] = &[
    OwnershipRow {
        item: "aiperf_plugin_entry_v1",
        owning_crate: "plugin (generated by aiperf-plugin-sdk-macros)",
        argument_types: "()",
        return_type: "PluginDeclarationV1",
        allocation_owner: StorageOwner::Plugin,
        drop_owner: StorageOwner::Plugin,
        panic_abort: true,
        phase: CallPhase::Startup,
    },
    OwnershipRow {
        item: "PluginDeclarationV1::package",
        owning_crate: "aiperf-plugin-api",
        argument_types: "()",
        return_type: "&'static PluginPackageDescriptor",
        allocation_owner: StorageOwner::Plugin,
        drop_owner: StorageOwner::Plugin,
        panic_abort: true,
        phase: CallPhase::Startup,
    },
    OwnershipRow {
        item: "PluginDeclarationV1::extension",
        owning_crate: "aiperf-plugin-api",
        argument_types: "()",
        return_type: "&'static dyn AIPerfExtension",
        allocation_owner: StorageOwner::Plugin,
        drop_owner: StorageOwner::Plugin,
        panic_abort: true,
        phase: CallPhase::Startup,
    },
    OwnershipRow {
        item: "AIPerfExtension::register",
        owning_crate: "aiperf-plugin-api",
        argument_types: "&self, &mut PluginRegistrar<'_>",
        return_type: "Result<(), ExtensionError>",
        allocation_owner: StorageOwner::Plugin,
        drop_owner: StorageOwner::Host,
        panic_abort: true,
        phase: CallPhase::Startup,
    },
    OwnershipRow {
        item: "PluginRegistrar::package",
        owning_crate: "aiperf-plugin-api",
        argument_types: "&self",
        return_type: "&'static PluginPackageDescriptor",
        allocation_owner: StorageOwner::None,
        drop_owner: StorageOwner::None,
        panic_abort: true,
        phase: CallPhase::Startup,
    },
    OwnershipRow {
        item: "PluginRegistrar::observed",
        owning_crate: "aiperf-plugin-api",
        argument_types: "&self",
        return_type: "&[RegistryId]",
        allocation_owner: StorageOwner::None,
        drop_owner: StorageOwner::None,
        panic_abort: true,
        phase: CallPhase::Startup,
    },
    OwnershipRow {
        item: "PluginRegistrar::record_registration",
        owning_crate: "aiperf-plugin-api",
        argument_types: "&mut self, RegistryId",
        return_type: "Result<(), ExtensionError>",
        allocation_owner: StorageOwner::Plugin,
        drop_owner: StorageOwner::Host,
        panic_abort: true,
        phase: CallPhase::Startup,
    },
    OwnershipRow {
        item: "PluginRegistrar::describe",
        owning_crate: "aiperf-plugin-api",
        argument_types: "&self, RegistryId",
        return_type: "PluginCategoryDescriptor",
        allocation_owner: StorageOwner::Plugin,
        drop_owner: StorageOwner::Host,
        panic_abort: true,
        phase: CallPhase::Startup,
    },
    OwnershipRow {
        item: "RegistryId::new",
        owning_crate: "aiperf-plugin-api",
        argument_types: "&str, u8",
        return_type: "Result<RegistryId, RegistryIdError>",
        allocation_owner: StorageOwner::Host,
        drop_owner: StorageOwner::Host,
        panic_abort: true,
        phase: CallPhase::Startup,
    },
    OwnershipRow {
        item: "RegistryId::as_str",
        owning_crate: "aiperf-plugin-api",
        argument_types: "&self",
        return_type: "&str",
        allocation_owner: StorageOwner::None,
        drop_owner: StorageOwner::None,
        panic_abort: true,
        phase: CallPhase::Startup,
    },
    OwnershipRow {
        item: "PluginPackageDescriptor::from_authored",
        owning_crate: "aiperf-plugin-api",
        argument_types: "&str, &'static str, &'static str",
        return_type: "Result<PluginPackageDescriptor, RegistryIdError>",
        allocation_owner: StorageOwner::Plugin,
        drop_owner: StorageOwner::Plugin,
        panic_abort: true,
        phase: CallPhase::Startup,
    },
    OwnershipRow {
        item: "PluginCategoryDescriptor::new",
        owning_crate: "aiperf-plugin-api",
        argument_types: "RegistryId, &'static PluginPackageDescriptor",
        return_type: "PluginCategoryDescriptor",
        allocation_owner: StorageOwner::Plugin,
        drop_owner: StorageOwner::Host,
        panic_abort: true,
        phase: CallPhase::Startup,
    },
    OwnershipRow {
        item: "PluginSourceApiVersion::parse",
        owning_crate: "aiperf-plugin-api",
        argument_types: "&str",
        return_type: "Result<PluginSourceApiVersion, SourceApiVersionError>",
        allocation_owner: StorageOwner::None,
        drop_owner: StorageOwner::None,
        panic_abort: true,
        phase: CallPhase::Startup,
    },
    OwnershipRow {
        item: "PluginSourceApiVersion::is_compatible_with",
        owning_crate: "aiperf-plugin-api",
        argument_types: "&self, &PluginSourceApiVersion",
        return_type: "bool",
        allocation_owner: StorageOwner::None,
        drop_owner: StorageOwner::None,
        panic_abort: true,
        phase: CallPhase::Startup,
    },
    OwnershipRow {
        item: "ExtensionError::reason",
        owning_crate: "aiperf-plugin-api",
        argument_types: "&self",
        return_type: "&str",
        allocation_owner: StorageOwner::None,
        drop_owner: StorageOwner::None,
        panic_abort: true,
        phase: CallPhase::Startup,
    },
];

/// Render the surface as the fixed-width text table the guard binary prints.
///
/// The rendering is deterministic so a diff of two runs is a diff of the
/// boundary, not of formatting.
pub fn render_surface_table(rows: &[OwnershipRow]) -> String {
    const HEADERS: [&str; 8] = [
        "item",
        "owning crate",
        "arguments",
        "returns",
        "alloc",
        "drop",
        "panic=abort",
        "phase",
    ];

    let mut cells: Vec<[String; 8]> = Vec::with_capacity(rows.len() + 1);
    cells.push(HEADERS.map(str::to_owned));
    for row in rows {
        cells.push([
            row.item.to_owned(),
            row.owning_crate.to_owned(),
            row.argument_types.to_owned(),
            row.return_type.to_owned(),
            row.allocation_owner.label().to_owned(),
            row.drop_owner.label().to_owned(),
            if row.panic_abort { "yes" } else { "no" }.to_owned(),
            row.phase.label().to_owned(),
        ]);
    }

    let mut widths = [0_usize; 8];
    for record in &cells {
        for (column, value) in record.iter().enumerate() {
            widths[column] = widths[column].max(value.chars().count());
        }
    }

    let mut rendered = String::new();
    for record in &cells {
        for (column, value) in record.iter().enumerate() {
            let padding = widths[column] - value.chars().count();
            rendered.push_str(value);
            if column + 1 < record.len() {
                rendered.extend(std::iter::repeat_n(' ', padding + 2));
            }
        }
        rendered.push('\n');
    }
    rendered
}
