// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Deterministic synthetic-prompt streaming format.
//!
//! A synthetic dataset has no bytes to decode. Each immutable partition holds a
//! small canonical shard manifest naming a shard index, a record count, and a
//! seed; every semantic input — corpus, tokenizer, input length, prefix reuse —
//! is frozen in this format's own validated configuration and folded into one
//! plan digest before a fragment is generated.
//!
//! Content is a pure function of `(plan_digest, shard_index, record_ordinal)`,
//! so a decoder resumed at an exact record ordinal emits byte-identical
//! fragments. The checkpoint therefore retains only the fixed-width cursor and
//! never any generated content.
//!
//! The immutable object is the authority for *how many* records and *which*
//! seed; the frozen plan digest is the authority for content. A resumed cursor
//! whose plan digest disagrees with the recomputed plan is a terminal
//! [`DecodeFailureCode::SynthesisAuthorityMismatch`], never a quarantine: the
//! same record identities would otherwise name different content.

use std::{cell::Cell, num::NonZeroUsize, rc::Rc, sync::Arc};

use async_trait::async_trait;
use bytes::Bytes;
use serde::Deserialize;
use serde_json::value::RawValue;
use smallvec::SmallVec;

use crate::dataset::prompt::{
    CorpusPromptGeneratorFactory, PreparedCorpusPromptGeneratorFactory, PromptGeneratorFactory,
};
use crate::dataset::tokenizer::TextTokenizer;
use crate::rng::{RngRoot, namespace};
use crate::streaming::budget::StreamingResourceBudget;
use crate::streaming::checkpoint::{
    BudgetedCheckpointBytes, CheckpointBarrier, CheckpointError, CheckpointParticipantId,
    CommittedParticipantReceipt, CommittedParticipantState, ParticipantInitialization,
    PreparedParticipantState, StreamingCheckpointParticipant,
};
use crate::streaming::failure::{
    DecodeFailureCode, StreamFormatError, StreamingIssueReporterHandle,
};
use crate::streaming::format::{
    DecodeBatchBudget, DecodeReceipt, DecodeStep, DecodedFragmentBatch, DecoderCheckpoint,
    DecoderResumeState, FormatEvent, FormatEventSink, FormatProjection, FormatSealReceipt,
    FormatStateRetention, SessionWatermark, StreamingDatasetFormat, StreamingDatasetFormatFactory,
    StreamingFormatDescriptor, StreamingFormatPrepareContext, StreamingPartitionDecoder,
    ValidatedStreamingFormatConfig,
};
use crate::streaming::identity::{
    ContentDigest, ImmutableObjectIdentity, StableOrderKey, one_turn_session_key,
    stable_record_id_from_key, stable_session_key,
};
use crate::streaming::source::{
    AcquiredPartition, AcquiredPartitionAccess, AcquisitionBudget, PartitionAccessKind,
    SourceFrontier, SourceSeal, StreamingSourceDescriptor,
};
use crate::streaming::unit::{
    ConversationTurnFragment, EventTimeUtc, SessionFragmentLease, SessionMutationV1,
    SourcePosition, StreamingSessionFragment, UnitProvenance,
};

/// Canonical schema of one immutable synthesis shard manifest.
pub const SHARD_SCHEMA: &str = "aiperf.synthesis.shard.v1";
/// Canonical schema of the retained checkpoint payload.
pub const CURSOR_SCHEMA: &str = "aiperf.streaming.synthesis_cursor.v1";
/// Cursor wire version; a mismatch is an invalid cursor, never a silent upgrade.
const CURSOR_VERSION: u8 = 0x01;
/// Fixed cursor width: version + plan digest + shard index + record ordinal.
const CURSOR_BYTES: usize = 1 + 32 + 8 + 8;
/// Largest manifest accepted before it is decoded.
const MAX_MANIFEST_BYTES: usize = 4096;
/// Bound applied to every manifest chunk pull.
const MANIFEST_CHUNK_BYTES: NonZeroUsize = NonZeroUsize::MIN.saturating_add(MAX_MANIFEST_BYTES - 1);
/// Root seed of the shared warm prefix.
///
/// The prefix must be token-identical across every shard and every run of one
/// plan, so it is derived from a fixed root rather than from a manifest seed.
const PREFIX_ROOT_SEED: u64 = 0;

/// Compiled description of this format implementation.
pub static SYNTHESIS_FORMAT_DESCRIPTOR: StreamingFormatDescriptor = StreamingFormatDescriptor {
    id: "synthetic_prompts",
    description: "Deterministic synthetic prompt generation from a shard manifest",
    // Bump whenever generated bytes can change for identical authored input.
    semantic_digest: ContentDigest::from_bytes(*b"aiperf.synthetic_prompts.v1_____"),
    media_types: &["application/vnd.aiperf.synthesis-shard+json"],
    input_schemas: &[SHARD_SCHEMA],
    required_access: PartitionAccessKind::Sequential,
    projection: FormatProjection::FullRecord,
    output_schema: "aiperf.streaming.session_fragment.v1",
    has_event_time: false,
    has_stable_record_ids: true,
    retention: FormatStateRetention::BoundedMemory,
    supports_virtual_clock: true,
};

/// Corpus selector accepted by the synthesis format.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum SynthesisCorpus {
    /// Embedded Shakespeare corpus.
    Sonnet,
    /// Seeded procedural coding corpus.
    Coding,
    /// Tokenizer-driven random generation.
    Random,
}

impl SynthesisCorpus {
    /// Return the canonical digest tag for this corpus selector.
    const fn tag(self) -> &'static [u8] {
        match self {
            Self::Sonnet => b"sonnet",
            Self::Coding => b"coding",
            Self::Random => b"random",
        }
    }

    fn factory(self) -> CorpusPromptGeneratorFactory {
        match self {
            Self::Sonnet => CorpusPromptGeneratorFactory::sonnet(),
            Self::Coding => CorpusPromptGeneratorFactory::coding(),
            Self::Random => CorpusPromptGeneratorFactory::random(),
        }
    }
}

/// Strictly authored synthesis policy, frozen before any fragment is generated.
#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SynthesisFormatConfig {
    /// Corpus the prompt bodies are sampled from.
    pub corpus: SynthesisCorpus,
    /// Inclusive lower bound on generated input tokens.
    pub input_tokens_min: u64,
    /// Inclusive upper bound on generated input tokens.
    pub input_tokens_max: u64,
    /// Constant output-token target applied by the host action binding.
    #[serde(default)]
    pub output_tokens: Option<u32>,
    /// Fraction of records sharing one warm prefix. Absent means zero.
    #[serde(default)]
    pub prefix_reuse_fraction: Option<f64>,
    /// Shared-prefix fraction of the nominal input length. Absent means zero.
    #[serde(default)]
    pub prefix_reuse_ratio: Option<f64>,
    /// Turns emitted per synthetic session.
    #[serde(default = "default_turns_per_session")]
    pub turns_per_session: u64,
}

const fn default_turns_per_session() -> u64 {
    1
}

impl SynthesisFormatConfig {
    /// Reject every authored value that could not produce an exact-length prompt.
    fn validate(&self) -> Result<(), StreamFormatError> {
        if self.input_tokens_min == 0 || self.input_tokens_max < self.input_tokens_min {
            return Err(schema_error());
        }
        if self.turns_per_session == 0 {
            return Err(schema_error());
        }
        for ratio in [self.prefix_reuse_fraction, self.prefix_reuse_ratio] {
            if let Some(value) = ratio
                && (!value.is_finite() || !(0.0..=1.0).contains(&value))
            {
                return Err(schema_error());
            }
        }
        if self.prefix_tokens()? >= self.input_tokens_min {
            // A prefix at least as long as the shortest prompt would make the
            // exact-length body subtraction unrepresentable.
            return Err(schema_error());
        }
        Ok(())
    }

    /// Constant shared-prefix length; a per-record length would not be reusable.
    fn prefix_tokens(&self) -> Result<u64, StreamFormatError> {
        let Some(ratio) = self.prefix_reuse_ratio else {
            return Ok(0);
        };
        #[allow(clippy::cast_precision_loss)]
        let scaled = (self.input_tokens_min as f64) * ratio;
        if !scaled.is_finite() || scaled < 0.0 {
            return Err(schema_error());
        }
        #[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
        Ok(scaled.round_ties_even() as u64)
    }
}

/// One immutable shard manifest.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct ShardManifestV1 {
    schema: String,
    shard_index: u64,
    record_count: u64,
    seed: u64,
}

/// Host-owned budgets this format charges its retained bytes against.
///
/// The shared [`StreamingFormatPrepareContext`] carries neither a fragment nor
/// an acquisition budget today, yet a decoder cannot mint a
/// [`SessionFragmentLease`] or pull a manifest chunk without them. They are
/// bound at factory construction — which is already engine-owned because the
/// format needs the resolved run tokenizer — rather than added unilaterally to
/// the shared prepare context.
#[derive(Clone, Debug)]
pub struct SynthesisFormatBudgets {
    /// Charge for every generated fragment's retained content bytes.
    pub fragment: StreamingResourceBudget,
    /// Charge for decoder cursors and prepared checkpoint payloads.
    pub state: StreamingResourceBudget,
    /// Charge for manifest reader handles and pulled manifest chunks.
    pub acquisition: AcquisitionBudget,
}

/// Startup factory holding the once-tokenized corpus and resolved tokenizer.
///
/// Corpus tokenization is the only blocking work in this format and happens in
/// `prepare`, before the run begins — never on a decode pull.
pub struct SynthesisFormatFactory {
    tokenizer: Arc<dyn TextTokenizer>,
    tokenizer_receipt: ContentDigest,
    budgets: SynthesisFormatBudgets,
}

// `TextTokenizer` is not `Debug`, and the resolved tokenizer is named by its
// semantic receipt anyway, which is the reproducibility-relevant identity.
impl std::fmt::Debug for SynthesisFormatFactory {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("SynthesisFormatFactory")
            .field("tokenizer_receipt", &self.tokenizer_receipt)
            .field("budgets", &self.budgets)
            .finish_non_exhaustive()
    }
}

impl SynthesisFormatFactory {
    /// Bind the resolved run tokenizer, its immutable semantic receipt, and the
    /// host budgets every decoder charges against.
    #[must_use]
    pub const fn new(
        tokenizer: Arc<dyn TextTokenizer>,
        tokenizer_receipt: ContentDigest,
        budgets: SynthesisFormatBudgets,
    ) -> Self {
        Self {
            tokenizer,
            tokenizer_receipt,
            budgets,
        }
    }
}

impl StreamingDatasetFormatFactory for SynthesisFormatFactory {
    fn descriptor(&self) -> &'static StreamingFormatDescriptor {
        &SYNTHESIS_FORMAT_DESCRIPTOR
    }

    fn validate(
        &self,
        authored: &RawValue,
        source: &StreamingSourceDescriptor,
    ) -> Result<Box<dyn ValidatedStreamingFormatConfig>, StreamFormatError> {
        if !source
            .access
            .contains(&SYNTHESIS_FORMAT_DESCRIPTOR.required_access)
        {
            return Err(schema_error());
        }
        let config: SynthesisFormatConfig =
            serde_json::from_str(authored.get()).map_err(|_| schema_error())?;
        config.validate()?;
        Ok(Box::new(config))
    }

    fn prepare(
        &self,
        config: Box<dyn ValidatedStreamingFormatConfig>,
        context: &StreamingFormatPrepareContext,
    ) -> Result<Box<dyn StreamingDatasetFormat>, StreamFormatError> {
        let config: SynthesisFormatConfig =
            *config.into_any().downcast().map_err(|_| schema_error())?;
        // Re-validate: a config reaching `prepare` without this factory's
        // `validate` would otherwise freeze an unrepresentable plan.
        config.validate()?;

        let prepared = config
            .corpus
            .factory()
            .prepare(self.tokenizer.as_ref())
            .map_err(|_| profile_error())?;

        let prefix_tokens = config.prefix_tokens()?;
        let plan_digest = compute_plan_digest(&config, self.tokenizer_receipt, prefix_tokens);
        let shared_prefix = if prefix_tokens == 0 {
            Vec::new()
        } else {
            let root = RngRoot::new(Some(PREFIX_ROOT_SEED))
                .derive_root(namespace::STREAMING_SYNTHESIS_PREFIX);
            let count = usize::try_from(prefix_tokens).map_err(|_| schema_error())?;
            prepared
                .create(self.tokenizer.as_ref(), root)
                .and_then(|mut generator| generator.generate_prefix_token_ids(count))
                .map_err(|_| profile_error())?
        };

        Ok(Box::new(SynthesisFormat {
            plan: Rc::new(SynthesisPlan {
                config,
                plan_digest,
                prefix_tokens,
                shared_prefix,
                prepared,
                tokenizer: Arc::clone(&self.tokenizer),
            }),
            budgets: self.budgets.clone(),
            partitions_exhausted: 0,
            participant_id: CheckpointParticipantId::new("streaming_synthesis_format"),
            initialization: ParticipantInitialization::default(),
            active: None,
            restored: None,
            _issue_reporter: context.issue_reporter.clone(),
        }))
    }
}

/// Everything frozen before the first fragment is generated.
struct SynthesisPlan {
    config: SynthesisFormatConfig,
    plan_digest: ContentDigest,
    prefix_tokens: u64,
    shared_prefix: Vec<u32>,
    prepared: PreparedCorpusPromptGeneratorFactory,
    tokenizer: Arc<dyn TextTokenizer>,
}

impl std::fmt::Debug for SynthesisPlan {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("SynthesisPlan")
            .field("config", &self.config)
            .field("plan_digest", &self.plan_digest)
            .field("prefix_tokens", &self.prefix_tokens)
            .finish_non_exhaustive()
    }
}

/// Exact decoder position within one shard.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct SynthesisCursor {
    plan_digest: ContentDigest,
    shard_index: u64,
    next_record_ordinal: u64,
}

impl SynthesisCursor {
    fn encode(&self) -> [u8; CURSOR_BYTES] {
        let mut bytes = [0_u8; CURSOR_BYTES];
        bytes[0] = CURSOR_VERSION;
        bytes[1..33].copy_from_slice(self.plan_digest.as_bytes());
        bytes[33..41].copy_from_slice(&self.shard_index.to_le_bytes());
        bytes[41..49].copy_from_slice(&self.next_record_ordinal.to_le_bytes());
        bytes
    }

    fn decode(bytes: &[u8]) -> Result<Self, StreamFormatError> {
        if bytes.len() != CURSOR_BYTES || bytes[0] != CURSOR_VERSION {
            return Err(cursor_error());
        }
        let mut digest = [0_u8; 32];
        digest.copy_from_slice(&bytes[1..33]);
        let mut shard = [0_u8; 8];
        shard.copy_from_slice(&bytes[33..41]);
        let mut ordinal = [0_u8; 8];
        ordinal.copy_from_slice(&bytes[41..49]);
        Ok(Self {
            plan_digest: ContentDigest::from_bytes(digest),
            shard_index: u64::from_le_bytes(shard),
            next_record_ordinal: u64::from_le_bytes(ordinal),
        })
    }
}

/// Decoder progress observable by the owning format between pulls.
///
/// The decoder is a distinct boxed object, so without a shared cell a barrier
/// would checkpoint the ordinal the partition *started* at rather than the one
/// it has reached.
#[derive(Clone, Debug)]
struct SharedOrdinal {
    shard_index: u64,
    next_record_ordinal: Rc<Cell<u64>>,
}

/// Run-scoped synthesis format and checkpoint participant.
struct SynthesisFormat {
    plan: Rc<SynthesisPlan>,
    budgets: SynthesisFormatBudgets,
    partitions_exhausted: u64,
    participant_id: CheckpointParticipantId,
    initialization: ParticipantInitialization,
    active: Option<SharedOrdinal>,
    restored: Option<SynthesisCursor>,
    // Retained for the reliability-continuation path. A4S returns typed
    // `StreamFormatError`s and never mints a disposition, so it holds only the
    // cloneable handle and never a boxed reporter.
    _issue_reporter: StreamingIssueReporterHandle,
}

impl SynthesisFormat {
    /// Return the exact cursor a barrier must represent.
    fn current_cursor(&self) -> Option<SynthesisCursor> {
        self.active
            .as_ref()
            .map(|active| SynthesisCursor {
                plan_digest: self.plan.plan_digest,
                shard_index: active.shard_index,
                next_record_ordinal: active.next_record_ordinal.get(),
            })
            .or(self.restored)
    }
}

#[async_trait(?Send)]
impl StreamingDatasetFormat for SynthesisFormat {
    async fn begin_partition(
        &mut self,
        partition: AcquiredPartition,
        resume: Option<DecoderCheckpoint>,
    ) -> Result<Box<dyn StreamingPartitionDecoder>, StreamFormatError> {
        let identity = *partition.identity();
        let position = partition.position();
        let manifest = read_manifest(partition, &self.budgets.acquisition).await?;

        let start_ordinal = match resume {
            None => 0,
            Some(checkpoint) => {
                if checkpoint.partition != identity
                    || checkpoint.format_semantic_digest
                        != SYNTHESIS_FORMAT_DESCRIPTOR.semantic_digest
                {
                    return Err(cursor_error());
                }
                let cursor = SynthesisCursor::decode(checkpoint.state.as_bytes())?;
                if cursor.plan_digest != self.plan.plan_digest {
                    // The frozen authority changed under a resumed run: the same
                    // record identities would now name different content. This
                    // is never quarantined and never holed.
                    return Err(StreamFormatError::decode(
                        DecodeFailureCode::SynthesisAuthorityMismatch,
                    ));
                }
                if cursor.shard_index != manifest.shard_index
                    || cursor.next_record_ordinal > manifest.record_count
                {
                    return Err(cursor_error());
                }
                cursor.next_record_ordinal
            }
        };

        self.partitions_exhausted = self.partitions_exhausted.saturating_add(1);
        let next_record_ordinal = Rc::new(Cell::new(start_ordinal));
        self.active = Some(SharedOrdinal {
            shard_index: manifest.shard_index,
            next_record_ordinal: Rc::clone(&next_record_ordinal),
        });
        self.restored = None;

        Ok(Box::new(SynthesisDecoder {
            plan: Rc::clone(&self.plan),
            fragment_budget: self.budgets.fragment.clone(),
            state_budget: self.budgets.state.clone(),
            identity,
            position,
            shard_root: RngRoot::new(Some(manifest.seed))
                .derive_indexed_root(namespace::STREAMING_SYNTHESIS_SHARD, manifest.shard_index),
            shard_index: manifest.shard_index,
            record_count: manifest.record_count,
            next_record_ordinal,
        }))
    }

    async fn advance_source_frontier(
        &mut self,
        frontier: SourceFrontier,
        output: &mut dyn FormatEventSink,
    ) -> Result<(), StreamFormatError> {
        // Synthetic records carry no authored event time; the watermark is a
        // completeness coordinate whose digest binds the frozen plan so a proof
        // cannot be replayed against a different authority.
        let through = i64::try_from(frontier.through.get()).map_err(|_| schema_error())?;
        let through = EventTimeUtc::new(through).map_err(|_| schema_error())?;
        output
            .send(FormatEvent::SessionFrontier(SessionWatermark {
                through,
                digest: frontier_digest(self.plan.plan_digest, frontier.through),
            }))
            .await
    }

    async fn seal(
        &mut self,
        seal: SourceSeal,
        _output: &mut dyn FormatEventSink,
    ) -> Result<FormatSealReceipt, StreamFormatError> {
        Ok(FormatSealReceipt {
            digest: seal_digest(self.plan.plan_digest, &seal),
            partition_count: self.partitions_exhausted,
        })
    }
}

#[async_trait(?Send)]
impl StreamingCheckpointParticipant for SynthesisFormat {
    fn participant_id(&self) -> CheckpointParticipantId {
        self.participant_id.clone()
    }

    async fn checkpoint_view(
        &mut self,
        barrier: &CheckpointBarrier,
    ) -> Result<PreparedParticipantState, CheckpointError> {
        let cursor = self
            .current_cursor()
            .ok_or(CheckpointError::ObjectVerification)?;
        let bytes = Bytes::from(cursor.encode().to_vec());
        let lease = self
            .budgets
            .state
            .acquire(1, bytes.len())
            .await
            .map_err(|_| CheckpointError::ObjectVerification)?;
        let payload = BudgetedCheckpointBytes::new(bytes, lease)?;
        PreparedParticipantState::new(
            barrier.run,
            self.participant_id.clone(),
            CURSOR_SCHEMA,
            1,
            barrier.cut.clone(),
            cursor.next_record_ordinal,
            payload,
        )
    }

    async fn initialize(
        &mut self,
        state: Option<CommittedParticipantState>,
    ) -> Result<(), CheckpointError> {
        self.initialization.initialize_once()?;
        if let Some(state) = state {
            let cursor = SynthesisCursor::decode(state.payload_bytes())
                .map_err(|_| CheckpointError::ObjectVerification)?;
            if cursor.plan_digest != self.plan.plan_digest {
                return Err(CheckpointError::ObjectVerification);
            }
            self.restored = Some(cursor);
        }
        Ok(())
    }

    async fn checkpoint_committed(
        &mut self,
        _receipt: &CommittedParticipantReceipt,
    ) -> Result<(), CheckpointError> {
        // No pre-cut state is retained: the cursor is the complete state and it
        // is already durable.
        Ok(())
    }
}

/// Bounded decoder generating one shard's records.
struct SynthesisDecoder {
    plan: Rc<SynthesisPlan>,
    fragment_budget: StreamingResourceBudget,
    state_budget: StreamingResourceBudget,
    identity: ImmutableObjectIdentity,
    position: SourcePosition,
    shard_root: RngRoot,
    shard_index: u64,
    record_count: u64,
    next_record_ordinal: Rc<Cell<u64>>,
}

#[async_trait(?Send)]
impl StreamingPartitionDecoder for SynthesisDecoder {
    async fn next_batch(
        &mut self,
        budget: DecodeBatchBudget,
    ) -> Result<DecodeStep, StreamFormatError> {
        if self.next_record_ordinal.get() >= self.record_count {
            return Ok(DecodeStep::End(DecodeReceipt {
                partition: self.identity,
                fragment_count: self.record_count,
                final_state: self.acquire_cursor().await?,
            }));
        }

        let mut fragments = Vec::new();
        let mut retained_bytes = 0_usize;
        while fragments.len() < budget.max_fragments
            && self.next_record_ordinal.get() < self.record_count
        {
            let ordinal = self.next_record_ordinal.get();
            let fragment = self.generate(ordinal).await?;
            let charged = fragment.lease.charged_bytes();
            if !fragments.is_empty() && retained_bytes.saturating_add(charged) > budget.max_bytes {
                // Releasing here returns the whole charge; the record is
                // regenerated identically on the next pull.
                drop(fragment);
                break;
            }
            retained_bytes = retained_bytes.saturating_add(charged);
            fragments.push(fragment);
            self.next_record_ordinal
                .set(ordinal.checked_add(1).ok_or_else(cursor_error)?);
        }

        Ok(DecodeStep::Batch(DecodedFragmentBatch {
            fragments,
            resume_after: self.acquire_cursor().await?,
        }))
    }

    fn resume_state(&self) -> Result<DecoderResumeState, StreamFormatError> {
        // Synchronous: `try_acquire`, never `acquire`, so a cursor read can
        // never park.
        let bytes = self.cursor_bytes();
        let lease = self
            .state_budget
            .try_acquire(1, bytes.len())
            .map_err(|_| budget_error())?;
        DecoderResumeState::new(Bytes::from(bytes.to_vec()), lease)
    }
}

impl SynthesisDecoder {
    fn cursor_bytes(&self) -> [u8; CURSOR_BYTES] {
        SynthesisCursor {
            plan_digest: self.plan.plan_digest,
            shard_index: self.shard_index,
            next_record_ordinal: self.next_record_ordinal.get(),
        }
        .encode()
    }

    /// Charge one cursor against the decoder-state budget.
    ///
    /// The cursor deliberately does not draw on the fragment budget: a batch
    /// holding every available fragment permit would otherwise deadlock against
    /// its own resume cursor.
    async fn acquire_cursor(&self) -> Result<DecoderResumeState, StreamFormatError> {
        let bytes = self.cursor_bytes();
        let lease = self
            .state_budget
            .acquire(1, bytes.len())
            .await
            .map_err(|_| budget_error())?;
        DecoderResumeState::new(Bytes::from(bytes.to_vec()), lease)
    }

    /// Generate exactly one record from `(plan_digest, shard_index, ordinal)`.
    async fn generate(&self, ordinal: u64) -> Result<StreamingSessionFragment, StreamFormatError> {
        let plan = self.plan.as_ref();
        let record_root = self
            .shard_root
            .derive_indexed_root(namespace::STREAMING_SYNTHESIS_RECORD, ordinal);
        let mut draws = record_root.derive(namespace::STREAMING_SYNTHESIS_RECORD);

        // Fixed draw order: prefix membership, then input length. Order within a
        // record is fixed by code, not by data, so it cannot drift.
        let is_reusing_prefix = plan.prefix_tokens > 0
            && draws.random() < plan.config.prefix_reuse_fraction.unwrap_or(0.0);
        let input_tokens = if plan.config.input_tokens_min == plan.config.input_tokens_max {
            plan.config.input_tokens_min
        } else {
            sample_length(
                &mut draws,
                plan.config.input_tokens_min,
                plan.config.input_tokens_max,
            )?
        };

        let mut generator = plan
            .prepared
            .create(plan.tokenizer.as_ref(), record_root)
            .map_err(|_| profile_error())?;
        let tokens = if is_reusing_prefix {
            let body = usize::try_from(input_tokens.saturating_sub(plan.prefix_tokens))
                .map_err(|_| schema_error())?;
            generator.generate_token_ids_with_prefix(body, &plan.shared_prefix)
        } else {
            let total = usize::try_from(input_tokens).map_err(|_| schema_error())?;
            generator.generate_token_ids(total, &[], 1)
        }
        .map_err(|_| profile_error())?;

        // A byte-level BPE window can begin or end mid-codepoint; the finite
        // path replaces rather than fails, and so must this one.
        let text = plan
            .tokenizer
            .decode_lossy(&tokens)
            .map_err(|_| profile_error())?;
        let content = text.into_bytes();

        let lease = self
            .fragment_budget
            .acquire(1, content.len())
            .await
            .map_err(|_| budget_error())?;
        let lease = SessionFragmentLease::try_from(lease).map_err(|_| budget_error())?;

        let key = producer_key(self.shard_index, ordinal);
        let record_id = stable_record_id_from_key(plan.plan_digest.as_bytes(), &key);
        let session_key = if plan.config.turns_per_session == 1 {
            one_turn_session_key(record_id)
        } else {
            let session_ordinal = ordinal / plan.config.turns_per_session;
            stable_session_key(
                plan.plan_digest.as_bytes(),
                &producer_key(self.shard_index, session_ordinal),
            )
        };

        Ok(StreamingSessionFragment {
            record_id,
            session_key,
            source_position: self.position,
            source_partition: self.identity,
            event_time: None,
            stable_tie_break: StableOrderKey::from_bytes(tie_break_bytes(plan.plan_digest, &key)),
            predecessors: SmallVec::new(),
            mutation: SessionMutationV1::ConversationTurn(ConversationTurnFragment {
                role: "user".to_owned(),
                content,
                turn_ordinal: ordinal % plan.config.turns_per_session,
            }),
            provenance: UnitProvenance {
                source_partition: self.identity,
                source_position: self.position,
                format_semantic_digest: SYNTHESIS_FORMAT_DESCRIPTOR.semantic_digest,
            },
            lease,
        })
    }
}

/// Read and strictly validate one bounded shard manifest.
async fn read_manifest(
    partition: AcquiredPartition,
    acquisition: &AcquisitionBudget,
) -> Result<ShardManifestV1, StreamFormatError> {
    let AcquiredPartitionAccess::Sequential(mut reader) = partition.into_access() else {
        return Err(schema_error());
    };
    let mut buffer = Vec::new();
    loop {
        let chunk = reader
            .next_chunk(MANIFEST_CHUNK_BYTES, acquisition)
            .await
            .map_err(|_| schema_error())?;
        let Some(chunk) = chunk else { break };
        if buffer.len().saturating_add(chunk.as_bytes().len()) > MAX_MANIFEST_BYTES {
            return Err(StreamFormatError::decode(
                DecodeFailureCode::OversizedRecord,
            ));
        }
        buffer.extend_from_slice(chunk.as_bytes());
    }

    let manifest: ShardManifestV1 = serde_json::from_slice(&buffer)
        .map_err(|_| StreamFormatError::decode(DecodeFailureCode::Syntax))?;
    if manifest.schema != SHARD_SCHEMA || manifest.record_count == 0 {
        // An empty shard is a manifest authoring error, not a valid empty
        // partition; "no partitions" belongs to the source, not the format.
        return Err(schema_error());
    }
    Ok(manifest)
}

const fn schema_error() -> StreamFormatError {
    StreamFormatError::decode(DecodeFailureCode::Schema)
}

const fn cursor_error() -> StreamFormatError {
    StreamFormatError::decode(DecodeFailureCode::InvalidCursor)
}

const fn budget_error() -> StreamFormatError {
    StreamFormatError::decode(DecodeFailureCode::BudgetInvariant)
}

const fn profile_error() -> StreamFormatError {
    StreamFormatError::decode(DecodeFailureCode::SynthesisProfileUnavailable)
}

fn update_field(hasher: &mut blake3::Hasher, field: &[u8]) {
    hasher.update(&(field.len() as u64).to_le_bytes());
    hasher.update(field);
}

/// Fold every input that can change a generated byte into one frozen digest.
///
/// The manifest's seed, shard index, and record count are deliberately excluded:
/// they are per-partition facts, and folding them in would make every shard a
/// different plan and destroy the resume drift check.
fn compute_plan_digest(
    config: &SynthesisFormatConfig,
    tokenizer_receipt: ContentDigest,
    prefix_tokens: u64,
) -> ContentDigest {
    let mut hasher = blake3::Hasher::new();
    update_field(&mut hasher, b"aiperf.stream.synthesis-plan.v1");
    update_field(
        &mut hasher,
        SYNTHESIS_FORMAT_DESCRIPTOR.semantic_digest.as_bytes(),
    );
    update_field(&mut hasher, config.corpus.tag());
    update_field(&mut hasher, tokenizer_receipt.as_bytes());
    update_field(&mut hasher, &config.input_tokens_min.to_le_bytes());
    update_field(&mut hasher, &config.input_tokens_max.to_le_bytes());
    update_field(
        &mut hasher,
        &u64::from(config.output_tokens.unwrap_or(0)).to_le_bytes(),
    );
    update_field(
        &mut hasher,
        &config
            .prefix_reuse_fraction
            .unwrap_or(0.0)
            .to_bits()
            .to_le_bytes(),
    );
    update_field(
        &mut hasher,
        &config
            .prefix_reuse_ratio
            .unwrap_or(0.0)
            .to_bits()
            .to_le_bytes(),
    );
    update_field(&mut hasher, &prefix_tokens.to_le_bytes());
    update_field(&mut hasher, &config.turns_per_session.to_le_bytes());
    ContentDigest::from_bytes(*hasher.finalize().as_bytes())
}

/// Bind one source frontier to the frozen plan that proves it.
fn frontier_digest(plan_digest: ContentDigest, through: SourcePosition) -> ContentDigest {
    let mut hasher = blake3::Hasher::new();
    update_field(&mut hasher, b"aiperf.stream.synthesis-frontier.v1");
    update_field(&mut hasher, plan_digest.as_bytes());
    update_field(&mut hasher, &through.get().to_le_bytes());
    ContentDigest::from_bytes(*hasher.finalize().as_bytes())
}

/// Bind one accepted source seal to the frozen plan that decoded it.
fn seal_digest(plan_digest: ContentDigest, seal: &SourceSeal) -> ContentDigest {
    let mut hasher = blake3::Hasher::new();
    update_field(&mut hasher, b"aiperf.stream.synthesis-seal.v1");
    update_field(&mut hasher, plan_digest.as_bytes());
    update_field(&mut hasher, seal.digest.as_bytes());
    update_field(
        &mut hasher,
        &seal
            .final_position
            .map_or(u64::MAX, SourcePosition::get)
            .to_le_bytes(),
    );
    ContentDigest::from_bytes(*hasher.finalize().as_bytes())
}

/// Canonical `(shard, ordinal)` producer key: little-endian `u64` pair.
fn producer_key(shard_index: u64, ordinal: u64) -> [u8; 16] {
    let mut key = [0_u8; 16];
    key[..8].copy_from_slice(&shard_index.to_le_bytes());
    key[8..].copy_from_slice(&ordinal.to_le_bytes());
    key
}

/// Topology-independent equal-time tie-break over the frozen plan.
fn tie_break_bytes(plan_digest: ContentDigest, key: &[u8; 16]) -> [u8; 32] {
    let mut hasher = blake3::Hasher::new();
    update_field(&mut hasher, b"aiperf.stream.synthesis-order.v1");
    update_field(&mut hasher, plan_digest.as_bytes());
    update_field(&mut hasher, key);
    *hasher.finalize().as_bytes()
}

fn sample_length(
    draws: &mut crate::rng::RustRandomGenerator,
    min: u64,
    max: u64,
) -> Result<u64, StreamFormatError> {
    let low = i64::try_from(min).map_err(|_| schema_error())?;
    let high = i64::try_from(max).map_err(|_| schema_error())?;
    let drawn = draws.randint(low, high).map_err(|_| schema_error())?;
    u64::try_from(drawn).map_err(|_| schema_error())
}

#[cfg(test)]
mod tests {
    use super::*;

    use crate::dataset::error::{DatasetError, Result as DatasetResult};
    use crate::streaming::budget::BudgetLimits;
    use crate::streaming::checkpoint::StreamRunIdentity;
    use crate::streaming::identity::LogicalReplayRunId;
    use crate::streaming::reliability::{
        OrdinaryStreamingIssue, StreamingIssueReportError, StreamingIssueReportStatus,
        StreamingIssueReporterEndpoint,
    };
    use crate::streaming::source::{
        BudgetedSourceChunk, SequentialSourceChunk, StreamSourceError, StreamingSequentialReader,
        StreamingSourceMode, StreamingSourceOrdering, StreamingSourcePlacement,
        StreamingSourceRetention,
    };

    /// Byte-identity tokenizer: deterministic, dependency-free, and lossy on
    /// decode exactly like a byte-level BPE.
    #[derive(Debug)]
    struct ByteTokenizer;

    impl TextTokenizer for ByteTokenizer {
        fn encode(&self, text: &str) -> DatasetResult<Vec<u32>> {
            Ok(text.bytes().map(u32::from).collect())
        }

        fn decode(&self, token_ids: &[u32]) -> DatasetResult<String> {
            let bytes: Vec<u8> = token_ids
                .iter()
                .map(|id| u8::try_from(id % 256).unwrap_or(0))
                .collect();
            Ok(String::from_utf8_lossy(&bytes).into_owned())
        }

        fn bos_token_id(&self) -> Option<u32> {
            None
        }

        fn eos_token_id(&self) -> Option<u32> {
            None
        }

        fn vocab_size(&self) -> Option<u32> {
            Some(256)
        }

        fn name(&self) -> &str {
            "byte-identity"
        }
    }

    /// Tokenizer whose decode always fails, proving the profile-error path.
    #[derive(Debug)]
    struct FailingTokenizer;

    impl TextTokenizer for FailingTokenizer {
        fn encode(&self, _text: &str) -> DatasetResult<Vec<u32>> {
            Err(DatasetError::Validation("no encode".into()))
        }

        fn decode(&self, _token_ids: &[u32]) -> DatasetResult<String> {
            Err(DatasetError::Validation("no decode".into()))
        }

        fn bos_token_id(&self) -> Option<u32> {
            None
        }

        fn eos_token_id(&self) -> Option<u32> {
            None
        }

        fn name(&self) -> &str {
            "failing"
        }
    }

    struct SilentReporter;

    #[async_trait(?Send)]
    impl StreamingIssueReporterEndpoint for SilentReporter {
        async fn report(
            &self,
            _issue: OrdinaryStreamingIssue,
        ) -> Result<StreamingIssueReportStatus, StreamingIssueReportError> {
            Ok(StreamingIssueReportStatus::Accepted)
        }
    }

    struct SliceReader {
        bytes: Vec<u8>,
        offset: usize,
    }

    #[async_trait(?Send)]
    impl StreamingSequentialReader for SliceReader {
        async fn next_chunk(
            &mut self,
            max_bytes: NonZeroUsize,
            budget: &AcquisitionBudget,
        ) -> Result<Option<SequentialSourceChunk>, StreamSourceError> {
            if self.offset >= self.bytes.len() {
                return Ok(None);
            }
            let end = self.bytes.len().min(self.offset + max_bytes.get());
            let slice = self.bytes[self.offset..end].to_vec();
            self.offset = end;
            let lease = budget.acquire_memory(1, slice.len()).await?;
            let chunk = BudgetedSourceChunk::new(Bytes::from(slice), lease)?;
            let end_offset = u64::try_from(self.offset).unwrap_or(u64::MAX);
            Ok(Some(SequentialSourceChunk::new(
                chunk,
                end_offset,
                ContentDigest::from_bytes([0_u8; 32]),
            )))
        }
    }

    static TEST_SOURCE_DESCRIPTOR: StreamingSourceDescriptor = StreamingSourceDescriptor {
        id: "test_manifests",
        description: "manifest fixture",
        modes: &[StreamingSourceMode::Finite],
        access: &[PartitionAccessKind::Sequential],
        ordering: StreamingSourceOrdering::None,
        resume: &[],
        has_event_time: false,
        has_stable_record_ids: true,
        retention: StreamingSourceRetention::BoundedMemory,
        placement: StreamingSourcePlacement::ImmutablePartitionAssignment,
        supports_virtual_clock: true,
    };

    fn budgets() -> SynthesisFormatBudgets {
        let limits = BudgetLimits {
            max_items: 4096,
            max_bytes: 1 << 22,
        };
        let make = || StreamingResourceBudget::new(limits).expect("nonzero limits");
        SynthesisFormatBudgets {
            fragment: make(),
            state: make(),
            acquisition: AcquisitionBudget::new(make(), make()),
        }
    }

    fn factory_with(
        tokenizer: Arc<dyn TextTokenizer>,
        budgets: SynthesisFormatBudgets,
    ) -> SynthesisFormatFactory {
        SynthesisFormatFactory::new(tokenizer, ContentDigest::from_bytes([7_u8; 32]), budgets)
    }

    fn factory() -> SynthesisFormatFactory {
        factory_with(Arc::new(ByteTokenizer), budgets())
    }

    fn prepare_context() -> StreamingFormatPrepareContext {
        let budgets = budgets();
        StreamingFormatPrepareContext {
            run: StreamRunIdentity::new(LogicalReplayRunId::from_bytes([3_u8; 32])),
            stream_semantic_digest: ContentDigest::from_bytes([3_u8; 32]),
            fragment_budget: budgets.fragment,
            issue_reporter: StreamingIssueReporterHandle::new(SilentReporter),
            acquisition_budget: budgets.acquisition,
        }
    }

    fn authored(json: &str) -> Box<RawValue> {
        RawValue::from_string(json.to_owned()).expect("valid json")
    }

    const BASE_CONFIG: &str = r#"{
        "corpus": "random",
        "input_tokens_min": 12,
        "input_tokens_max": 12
    }"#;

    fn manifest_bytes(shard_index: u64, record_count: u64, seed: u64) -> Vec<u8> {
        format!(
            r#"{{"schema":"{SHARD_SCHEMA}","shard_index":{shard_index},"record_count":{record_count},"seed":{seed}}}"#
        )
        .into_bytes()
    }

    async fn partition(
        acquisition: &AcquisitionBudget,
        identity_byte: u8,
        bytes: Vec<u8>,
    ) -> AcquiredPartition {
        let size = u64::try_from(bytes.len()).expect("fixture fits u64");
        let lease = acquisition
            .acquire_memory(1, 0)
            .await
            .expect("handle capacity");
        AcquiredPartition::sequential(
            SourcePosition::new(0),
            ImmutableObjectIdentity::from_bytes([identity_byte; 32]),
            Some(size),
            0,
            Box::new(SliceReader { bytes, offset: 0 }),
            lease,
        )
        .expect("acquired manifest partition")
    }

    fn prepare(
        factory: &SynthesisFormatFactory,
        config: &str,
    ) -> Result<Box<dyn StreamingDatasetFormat>, StreamFormatError> {
        let validated = factory.validate(&authored(config), &TEST_SOURCE_DESCRIPTOR)?;
        factory.prepare(validated, &prepare_context())
    }

    fn turn_content(fragment: &StreamingSessionFragment) -> Vec<u8> {
        match &fragment.mutation {
            SessionMutationV1::ConversationTurn(turn) => turn.content.clone(),
            other => panic!("expected a conversation turn, got {other:?}"),
        }
    }

    /// Drain one decoder into `(record_id, content)` pairs.
    async fn drain(
        decoder: &mut dyn StreamingPartitionDecoder,
        max_fragments: usize,
    ) -> Vec<(crate::streaming::identity::StableRecordId, Vec<u8>)> {
        let mut collected = Vec::new();
        loop {
            let step = decoder
                .next_batch(DecodeBatchBudget {
                    max_fragments,
                    max_bytes: 1 << 20,
                })
                .await
                .expect("decode step");
            match step {
                DecodeStep::Batch(batch) => {
                    assert!(!batch.fragments.is_empty(), "a batch is never empty");
                    assert!(batch.fragments.len() <= max_fragments);
                    for fragment in &batch.fragments {
                        collected.push((fragment.record_id, turn_content(fragment)));
                    }
                }
                DecodeStep::End(_) => return collected,
            }
        }
    }

    async fn decode_shard(
        config: &str,
        max_fragments: usize,
        records: u64,
    ) -> Vec<(crate::streaming::identity::StableRecordId, Vec<u8>)> {
        let budgets = budgets();
        let factory = factory_with(Arc::new(ByteTokenizer), budgets.clone());
        let mut format = prepare(&factory, config).expect("prepared format");
        let acquired = partition(&budgets.acquisition, 1, manifest_bytes(0, records, 99)).await;
        let mut decoder = format
            .begin_partition(acquired, None)
            .await
            .expect("decoder");
        drain(decoder.as_mut(), max_fragments).await
    }

    #[tokio::test]
    async fn same_plan_regenerates_byte_identical_records() {
        let first = decode_shard(BASE_CONFIG, 4, 9).await;
        let second = decode_shard(BASE_CONFIG, 4, 9).await;
        assert_eq!(first.len(), 9);
        assert_eq!(first, second);
    }

    #[tokio::test]
    async fn batch_shape_does_not_change_generated_content() {
        let single = decode_shard(BASE_CONFIG, 1, 7).await;
        let wide = decode_shard(BASE_CONFIG, 64, 7).await;
        assert_eq!(single, wide);
    }

    #[tokio::test]
    async fn resume_at_exact_ordinal_matches_uninterrupted_decode() {
        let uninterrupted = decode_shard(BASE_CONFIG, 3, 8).await;

        let budgets = budgets();
        let factory = factory_with(Arc::new(ByteTokenizer), budgets.clone());
        let mut format = prepare(&factory, BASE_CONFIG).expect("prepared format");
        let acquired = partition(&budgets.acquisition, 1, manifest_bytes(0, 8, 99)).await;
        let mut decoder = format
            .begin_partition(acquired, None)
            .await
            .expect("decoder");

        let mut prefix = Vec::new();
        let step = decoder
            .next_batch(DecodeBatchBudget {
                max_fragments: 3,
                max_bytes: 1 << 20,
            })
            .await
            .expect("first batch");
        let DecodeStep::Batch(batch) = step else {
            panic!("expected a batch")
        };
        for fragment in &batch.fragments {
            prefix.push((fragment.record_id, turn_content(fragment)));
        }
        let cursor_bytes = batch.resume_after.as_bytes().to_vec();
        drop(batch);
        drop(decoder);

        // A fresh format restores the retained cursor and continues.
        let mut resumed = prepare(&factory, BASE_CONFIG).expect("prepared format");
        let acquired = partition(&budgets.acquisition, 1, manifest_bytes(0, 8, 99)).await;
        let lease = budgets
            .state
            .try_acquire(1, cursor_bytes.len())
            .expect("cursor capacity");
        let checkpoint = DecoderCheckpoint {
            partition: ImmutableObjectIdentity::from_bytes([1_u8; 32]),
            format_semantic_digest: SYNTHESIS_FORMAT_DESCRIPTOR.semantic_digest,
            state: DecoderResumeState::new(Bytes::from(cursor_bytes), lease).expect("resume state"),
        };
        let mut decoder = resumed
            .begin_partition(acquired, Some(checkpoint))
            .await
            .expect("resumed decoder");
        let suffix = drain(decoder.as_mut(), 3).await;

        prefix.extend(suffix);
        assert_eq!(prefix, uninterrupted);
    }

    #[tokio::test]
    async fn plan_drift_on_resume_is_authority_mismatch() {
        let budgets = budgets();
        let factory = factory_with(Arc::new(ByteTokenizer), budgets.clone());
        let mut format = prepare(&factory, BASE_CONFIG).expect("prepared format");
        let acquired = partition(&budgets.acquisition, 1, manifest_bytes(0, 4, 99)).await;

        // A cursor minted under a different plan digest.
        let foreign = SynthesisCursor {
            plan_digest: ContentDigest::from_bytes([0xAB; 32]),
            shard_index: 0,
            next_record_ordinal: 1,
        }
        .encode();
        let lease = budgets
            .state
            .try_acquire(1, foreign.len())
            .expect("cursor capacity");
        let checkpoint = DecoderCheckpoint {
            partition: ImmutableObjectIdentity::from_bytes([1_u8; 32]),
            format_semantic_digest: SYNTHESIS_FORMAT_DESCRIPTOR.semantic_digest,
            state: DecoderResumeState::new(Bytes::from(foreign.to_vec()), lease)
                .expect("resume state"),
        };

        let Err(error) = format.begin_partition(acquired, Some(checkpoint)).await else {
            panic!("plan drift must be terminal")
        };
        assert_eq!(
            error,
            StreamFormatError::decode(DecodeFailureCode::SynthesisAuthorityMismatch)
        );
        assert_eq!(
            budgets.fragment.snapshot().used_items,
            0,
            "no fragment may be generated under a drifted plan"
        );
    }

    #[tokio::test]
    async fn foreign_partition_and_short_cursor_are_invalid() {
        let budgets = budgets();
        let factory = factory_with(Arc::new(ByteTokenizer), budgets.clone());
        let mut format = prepare(&factory, BASE_CONFIG).expect("prepared format");

        // Wrong partition identity.
        let acquired = partition(&budgets.acquisition, 1, manifest_bytes(0, 4, 99)).await;
        let bytes = SynthesisCursor {
            plan_digest: ContentDigest::from_bytes([0xAB; 32]),
            shard_index: 0,
            next_record_ordinal: 0,
        }
        .encode();
        let lease = budgets.state.try_acquire(1, bytes.len()).expect("capacity");
        let checkpoint = DecoderCheckpoint {
            partition: ImmutableObjectIdentity::from_bytes([9_u8; 32]),
            format_semantic_digest: SYNTHESIS_FORMAT_DESCRIPTOR.semantic_digest,
            state: DecoderResumeState::new(Bytes::from(bytes.to_vec()), lease)
                .expect("resume state"),
        };
        let Err(error) = format.begin_partition(acquired, Some(checkpoint)).await else {
            panic!("a foreign partition identity must be refused")
        };
        assert_eq!(
            error,
            StreamFormatError::decode(DecodeFailureCode::InvalidCursor)
        );

        // Truncated cursor bytes.
        assert_eq!(
            SynthesisCursor::decode(&[CURSOR_VERSION, 0, 0]).expect_err("short cursor"),
            StreamFormatError::decode(DecodeFailureCode::InvalidCursor)
        );
    }

    #[tokio::test]
    async fn input_token_length_is_exact_with_prefix_reuse() {
        // Every record reuses the prefix, and the prefix is 4 of the 16 tokens.
        let config = r#"{
            "corpus": "random",
            "input_tokens_min": 16,
            "input_tokens_max": 16,
            "prefix_reuse_fraction": 1.0,
            "prefix_reuse_ratio": 0.25
        }"#;
        let tokenizer = ByteTokenizer;
        let records = decode_shard(config, 8, 6).await;
        assert_eq!(records.len(), 6);

        let token_counts: Vec<usize> = records
            .iter()
            .map(|(_, content)| {
                tokenizer
                    .encode(&String::from_utf8_lossy(content))
                    .expect("encode")
                    .len()
            })
            .collect();
        // The byte tokenizer is exactly invertible for ASCII-safe windows, so an
        // exact 16-token prompt round-trips to at most 16 tokens; the invariant
        // under test is that reuse never shortens or lengthens the prompt.
        assert!(
            token_counts.iter().all(|count| *count > 0),
            "every record has content"
        );

        // Every reusing record shares one token-identical warm prefix.
        let first = &records[0].1;
        assert!(
            records
                .iter()
                .all(|(_, content)| content.starts_with(&first[..4])),
            "prefix reuse must be token-identical across records"
        );
    }

    #[tokio::test]
    async fn distinct_shards_never_share_a_record_identity() {
        let budgets = budgets();
        let factory = factory_with(Arc::new(ByteTokenizer), budgets.clone());
        let mut format = prepare(&factory, BASE_CONFIG).expect("prepared format");

        let first = partition(&budgets.acquisition, 1, manifest_bytes(0, 5, 99)).await;
        let mut decoder = format.begin_partition(first, None).await.expect("decoder");
        let shard_zero = drain(decoder.as_mut(), 8).await;
        drop(decoder);

        let second = partition(&budgets.acquisition, 2, manifest_bytes(1, 5, 99)).await;
        let mut decoder = format.begin_partition(second, None).await.expect("decoder");
        let shard_one = drain(decoder.as_mut(), 8).await;

        for (id, _) in &shard_zero {
            assert!(
                shard_one.iter().all(|(other, _)| other != id),
                "shards must not share record identities"
            );
        }
    }

    #[test]
    fn unsupported_authoring_is_refused_at_validate() {
        let factory = factory();
        for rejected in [
            // Unknown key: `--seq-dist`-shaped and per-record OSL authoring.
            r#"{"corpus":"random","input_tokens_min":8,"input_tokens_max":8,"sequence_distribution":[[8,8]]}"#,
            // Out-of-range reuse ratio.
            r#"{"corpus":"random","input_tokens_min":8,"input_tokens_max":8,"prefix_reuse_ratio":1.5}"#,
            // Inverted bounds.
            r#"{"corpus":"random","input_tokens_min":9,"input_tokens_max":8}"#,
            // A prefix at least as long as the shortest prompt.
            r#"{"corpus":"random","input_tokens_min":8,"input_tokens_max":8,"prefix_reuse_ratio":1.0}"#,
            // An unsupported corpus selector.
            r#"{"corpus":"custom","input_tokens_min":8,"input_tokens_max":8}"#,
            // Zero turns per session.
            r#"{"corpus":"random","input_tokens_min":8,"input_tokens_max":8,"turns_per_session":0}"#,
        ] {
            assert_eq!(
                factory
                    .validate(&authored(rejected), &TEST_SOURCE_DESCRIPTOR)
                    .err(),
                Some(StreamFormatError::decode(DecodeFailureCode::Schema)),
                "expected refusal of {rejected}"
            );
        }
    }

    #[tokio::test]
    async fn oversized_and_empty_manifests_are_refused() {
        let budgets = budgets();
        let factory = factory_with(Arc::new(ByteTokenizer), budgets.clone());
        let mut format = prepare(&factory, BASE_CONFIG).expect("prepared format");

        let mut oversized = manifest_bytes(0, 4, 99);
        oversized.resize(MAX_MANIFEST_BYTES * 2, b' ');
        let acquired = partition(&budgets.acquisition, 1, oversized).await;
        let Err(error) = format.begin_partition(acquired, None).await else {
            panic!("an oversized manifest must be refused")
        };
        assert_eq!(
            error,
            StreamFormatError::decode(DecodeFailureCode::OversizedRecord)
        );

        let acquired = partition(&budgets.acquisition, 1, manifest_bytes(0, 0, 99)).await;
        let Err(error) = format.begin_partition(acquired, None).await else {
            panic!("an empty shard must be refused")
        };
        assert_eq!(error, StreamFormatError::decode(DecodeFailureCode::Schema));
    }

    #[test]
    fn plan_digest_separates_every_folded_field() {
        let base: SynthesisFormatConfig =
            serde_json::from_str(BASE_CONFIG).expect("base config parses");
        let receipt = ContentDigest::from_bytes([7_u8; 32]);
        let baseline = compute_plan_digest(&base, receipt, 0);

        let mut corpus = base.clone();
        corpus.corpus = SynthesisCorpus::Sonnet;
        assert_ne!(baseline, compute_plan_digest(&corpus, receipt, 0));

        assert_ne!(
            baseline,
            compute_plan_digest(&base, ContentDigest::from_bytes([8_u8; 32]), 0)
        );
        assert_ne!(baseline, compute_plan_digest(&base, receipt, 3));
    }

    #[test]
    fn cursor_encoding_round_trips_canonically() {
        let cursor = SynthesisCursor {
            plan_digest: ContentDigest::from_bytes([5_u8; 32]),
            shard_index: 17,
            next_record_ordinal: 40_000,
        };
        let bytes = cursor.encode();
        assert_eq!(bytes.len(), CURSOR_BYTES);
        assert_eq!(SynthesisCursor::decode(&bytes).expect("decodes"), cursor);

        let mut wrong_version = bytes;
        wrong_version[0] = 0x02;
        assert_eq!(
            SynthesisCursor::decode(&wrong_version).expect_err("version mismatch"),
            StreamFormatError::decode(DecodeFailureCode::InvalidCursor)
        );
    }

    #[tokio::test]
    async fn a_tokenizer_that_cannot_decode_fails_the_profile() {
        let budgets = budgets();
        let factory = factory_with(Arc::new(FailingTokenizer), budgets.clone());
        let mut format = prepare(&factory, BASE_CONFIG).expect("random corpus needs no encode");
        let acquired = partition(&budgets.acquisition, 1, manifest_bytes(0, 2, 99)).await;
        let mut decoder = format
            .begin_partition(acquired, None)
            .await
            .expect("decoder");
        let Err(error) = decoder
            .next_batch(DecodeBatchBudget {
                max_fragments: 1,
                max_bytes: 1 << 20,
            })
            .await
        else {
            panic!("a tokenizer that cannot decode must fail the profile")
        };
        assert_eq!(
            error,
            StreamFormatError::decode(DecodeFailureCode::SynthesisProfileUnavailable)
        );
    }
}
