// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import type { GraphEdge, GraphNode, GraphScene } from "../../domain/architecture";
import { evidence } from "../helpers";

const fullAudience = {
  visibility: ["executive", "developer", "maintainer"],
  autoExpandDepth: { executive: 1, developer: 2, maintainer: 3 },
};

const fullSceneAudience = {
  visibility: ["executive", "developer", "maintainer"],
  defaultDepth: { executive: 1, developer: 2, maintainer: 3 },
};

const journeyNodeIds = [
  "node.journey.python-config-load",
  "node.journey.config-v2-resolution",
  "node.journey.authored-request-projection",
  "node.journey.runner-spawn",
  "node.journey.strict-jsonl-validation",
  "node.journey.frozen-runner-application",
  "node.journey.workload-preparation",
  "node.journey.scheduling-or-graph-ir",
  "node.journey.dataset-materialization",
  "node.journey.endpoint-binding",
  "node.journey.http-grpc-dynamo-dispatch",
  "node.journey.observer-callbacks",
  "node.journey.metrics-and-reporting",
  "node.journey.result-returned-to-python",
] as const;

const graphNodesRaw = [
  ...journeyNodeIds.map((id, index) => ({
    id,
    tier: 0 as const,
    parentId: null,
    childIds: [],
    owner: index === 0 || index === 1 || index === 2 || index === 13 ? "python" : "rust",
    status: { state: "built", delivery: "unconditional" },
    flavors: [
      "native_http",
      "native_grpc",
      "online_mock",
      "dynamo_offline",
      "dynamo_online",
    ],
    title: {
      executive: id.replace("node.journey.", "").replaceAll("-", " "),
      developer: `Journey step ${index + 1}`,
      maintainer: id,
    },
    summary: {
      executive: "Tier-0 journey step in the canonical Python-to-result flow.",
      developer: "Represents one required journey stage in the graph-first atlas.",
      maintainer: "Source-grounded sequence from Config-v2 through Rust execution and report return.",
    },
    evidence: [evidence("docs/superpowers/specs/2026-07-12-architecture-atlas-graph-first-redesign.md")],
    seamPorts: [
      { id: `${id}.in`, name: "in", channel: "control" },
      { id: `${id}.out`, name: "out", channel: "control" },
    ],
    audience: fullAudience,
    footnotes: [],
  })),
  {
    id: "node.runtime-composition",
    tier: 1,
    parentId: "node.journey.scheduling-or-graph-ir",
    childIds: ["node.clock-seam", "node.request-sink-seam", "node.dynamo-online-library-seam"],
    owner: "rust",
    status: { state: "built", delivery: "unconditional" },
    flavors: ["native_http", "native_grpc", "online_mock", "dynamo_offline"],
    title: {
      executive: "Runtime composition",
      developer: "Rust runtime composition",
      maintainer: "Runner, aiperf, and seam composition",
    },
    summary: {
      executive: "Shows how the runner composes one execution runtime.",
      developer: "Captures Clock and RequestSink seams feeding online and offline branches.",
      maintainer: "Grounded in aiperf-runner and aiperf runtime composition code paths.",
    },
    evidence: [evidence("crates/aiperf-runner/src/lib.rs"), evidence("crates/aiperf/src/run.rs")],
    seamPorts: [
      { id: "port.runtime.in", name: "entry", channel: "control" },
      { id: "port.runtime.out", name: "dispatch", channel: "request_data" },
    ],
    audience: fullAudience,
    footnotes: [],
  },
  {
    id: "node.runner-protocol-registries",
    tier: 1,
    parentId: "node.journey.strict-jsonl-validation",
    childIds: ["node.dynamo-online-runner-pair"],
    owner: "rust",
    status: { state: "built", delivery: "unconditional" },
    flavors: ["native_http", "native_grpc", "online_mock", "dynamo_offline"],
    title: {
      executive: "Runner protocol and registries",
      developer: "Protocol-v2 and registry freeze",
      maintainer: "protocol_v2 + RunnerApplication registries",
    },
    summary: {
      executive: "Validates authored requests against executable capabilities.",
      developer: "Protocol-v2 validate/execute uses the same frozen registry graph.",
      maintainer: "Covers protocol_v2 decoder and registry factory wiring in runner.",
    },
    evidence: [evidence("crates/aiperf-runner/src/protocol_v2.rs"), evidence("crates/aiperf-runner/src/registry.rs")],
    seamPorts: [
      { id: "port.runner.in", name: "request", channel: "control" },
      { id: "port.runner.out", name: "prepared", channel: "request_data" },
    ],
    audience: fullAudience,
    footnotes: [],
  },
  {
    id: "node.scheduling-phase-lifecycle",
    tier: 1,
    parentId: "node.journey.scheduling-or-graph-ir",
    childIds: [],
    owner: "rust",
    status: { state: "built", delivery: "unconditional" },
    flavors: ["native_http", "native_grpc", "online_mock", "dynamo_offline"],
    title: {
      executive: "Scheduling and phase lifecycle",
      developer: "Scheduling policy and phases",
      maintainer: "ScheduledRuntime + ClockPhaseOrchestrator",
    },
    summary: {
      executive: "Controls arrivals, admission, and phase transitions.",
      developer: "Combines workload issuance with phase escalation and adaptive controls.",
      maintainer: "Grounded in aiperf-timing and aiperf scheduled runtime execution.",
    },
    evidence: [evidence("crates/aiperf/src/scheduled.rs"), evidence("crates/aiperf-timing/src/phase/mod.rs")],
    seamPorts: [
      { id: "port.schedule.in", name: "prepared-work", channel: "request_data" },
      { id: "port.schedule.out", name: "dispatch", channel: "request_data" },
    ],
    audience: fullAudience,
    footnotes: [],
  },
  {
    id: "node.dataset-segment-pipeline",
    tier: 1,
    parentId: "node.journey.dataset-materialization",
    childIds: [],
    owner: "rust",
    status: { state: "built", delivery: "unconditional" },
    flavors: ["native_http", "native_grpc", "online_mock", "dynamo_offline"],
    title: {
      executive: "Dataset and segment pipeline",
      developer: "Dataset composition and segment storage",
      maintainer: "aiperf-dataset loader/compose/materialize chain",
    },
    summary: {
      executive: "Builds repeatable request content from authored data.",
      developer: "Composes loader output into dense content-addressed segment handles.",
      maintainer: "Shares segment store across scheduled, graph, and offline materializers.",
    },
    evidence: [evidence("crates/aiperf-dataset/src/compose.rs"), evidence("crates/aiperf-dataset/src/segment.rs")],
    seamPorts: [
      { id: "port.dataset.in", name: "authored-data", channel: "request_data" },
      { id: "port.dataset.out", name: "materialized-turns", channel: "request_data" },
    ],
    audience: fullAudience,
    footnotes: [],
  },
  {
    id: "node.endpoint-bindings-transports",
    tier: 1,
    parentId: "node.journey.endpoint-binding",
    childIds: [],
    owner: "rust",
    status: { state: "built", delivery: "unconditional" },
    flavors: ["native_http", "native_grpc", "online_mock"],
    title: {
      executive: "Endpoint bindings and HTTP/gRPC transports",
      developer: "Endpoint registry and native transports",
      maintainer: "EndpointFactory + Hyper/Tonic transport seams",
    },
    summary: {
      executive: "Maps one runtime to multiple inference protocol families.",
      developer: "Prepared endpoint bindings dispatch over native HTTP or gRPC transports.",
      maintainer: "Covers endpoint factories, readiness rules, and transport observer callbacks.",
    },
    evidence: [evidence("crates/aiperf-endpoints/src/registry.rs"), evidence("crates/aiperf-transport-http/src/lib.rs"), evidence("crates/aiperf-transport-grpc/src/lib.rs")],
    seamPorts: [
      { id: "port.endpoint.in", name: "prepared-endpoint", channel: "request_data" },
      { id: "port.endpoint.out", name: "transport-dispatch", channel: "request_data" },
    ],
    audience: fullAudience,
    footnotes: [],
  },
  {
    id: "node.graph-ir-execution",
    tier: 1,
    parentId: "node.journey.scheduling-or-graph-ir",
    childIds: [],
    owner: "rust",
    status: { state: "built", delivery: "unconditional" },
    flavors: ["native_http", "online_mock", "dynamo_offline"],
    title: {
      executive: "Graph-IR execution",
      developer: "Graph workload and runtime",
      maintainer: "aiperf-graph compile and execute path",
    },
    summary: {
      executive: "Executes branching traces with explicit admission and failure policy.",
      developer: "Compiles DAG/WEKA/Dynamo traces and dispatches with worker-local execution.",
      maintainer: "Supports drive_real and drive_sim_with_source on the shared graph engine.",
    },
    evidence: [evidence("crates/aiperf-graph/src/input.rs"), evidence("crates/aiperf-graph/src/runtime.rs")],
    seamPorts: [
      { id: "port.graph.in", name: "graph-plan", channel: "request_data" },
      { id: "port.graph.out", name: "graph-dispatch", channel: "request_data" },
    ],
    audience: fullAudience,
    footnotes: [],
  },
  {
    id: "node.metrics-telemetry",
    tier: 1,
    parentId: "node.journey.metrics-and-reporting",
    childIds: [],
    owner: "rust",
    status: { state: "built", delivery: "unconditional" },
    flavors: ["native_http", "native_grpc", "online_mock", "dynamo_offline"],
    title: {
      executive: "Metrics and telemetry",
      developer: "Metrics accumulator and telemetry producers",
      maintainer: "aiperf-metrics with GPU/server/network producer leaves",
    },
    summary: {
      executive: "Converts execution observations into reportable evidence.",
      developer: "Request observer events and side-channel telemetry merge into native-v2 reporting.",
      maintainer: "Maintains IO-free metrics kernels and producer-to-seam dependency direction.",
    },
    evidence: [evidence("crates/aiperf-metrics/src/accumulator.rs"), evidence("crates/aiperf-gpu-telemetry/src/lib.rs")],
    seamPorts: [
      { id: "port.metrics.in", name: "observer-events", channel: "telemetry" },
      { id: "port.metrics.out", name: "native-report", channel: "report_result" },
    ],
    audience: fullAudience,
    footnotes: [],
  },
  {
    id: "node.accuracy-evaluator-hosting",
    tier: 1,
    parentId: "node.journey.metrics-and-reporting",
    childIds: [],
    owner: "rust",
    status: { state: "built", delivery: "runtime_conditional" },
    flavors: ["native_http"],
    title: {
      executive: "Accuracy and evaluator hosting",
      developer: "Legacy evaluators and provider host",
      maintainer: "AccuracyEvaluator/AgenticHarness + provider protocol v2 host",
    },
    summary: {
      executive: "Combines quality scoring paths with runtime execution evidence.",
      developer: "Keeps legacy evaluator semantics and bounded provider-hosted canaries explicit.",
      maintainer: "Separates legacy Python evaluator paths from provider-neutral host foundations.",
    },
    evidence: [evidence("crates/aiperf/src/accuracy.rs"), evidence("crates/aiperf/src/evaluation.rs")],
    seamPorts: [
      { id: "port.accuracy.in", name: "inference-turns", channel: "request_data" },
      { id: "port.accuracy.out", name: "score-results", channel: "report_result" },
    ],
    audience: fullAudience,
    footnotes: [
      {
        executive: "Legacy and migration details remain subordinate footnotes.",
        developer: "Legacy evaluator providers are retained while bounded provider-host migration continues.",
        maintainer: "Pinned Harbor/BrowserGym/MCPMark and stock evaluator-root attestation are tracked as migration footnotes.",
      },
    ],
  },
  {
    id: "node.crate-dependency-topology",
    tier: 1,
    parentId: "node.journey.frozen-runner-application",
    childIds: [],
    owner: "rust",
    status: { state: "built", delivery: "unconditional" },
    flavors: ["native_http", "native_grpc", "online_mock", "dynamo_offline"],
    title: {
      executive: "Crate dependency topology",
      developer: "Workspace dependency topology",
      maintainer: "Cargo crate graph and dependency directions",
    },
    summary: {
      executive: "Shows major dependency boundaries in the Rust workspace.",
      developer: "Tracks runner, runtime, graph, transport, metrics, and dataset crate relationships.",
      maintainer: "Validated against Cargo metadata for source-grounded dependency claims.",
    },
    evidence: [evidence("AGENTS.md"), evidence("apps/architecture-atlas/src/domain/integrity.ts")],
    seamPorts: [
      { id: "port.crates.in", name: "workspace-manifests", channel: "control" },
      { id: "port.crates.out", name: "validated-topology", channel: "report_result" },
    ],
    audience: fullAudience,
    footnotes: [],
  },
  {
    id: "node.clock-seam",
    tier: 2,
    parentId: "node.runtime-composition",
    childIds: [],
    owner: "rust",
    status: { state: "built", delivery: "unconditional" },
    flavors: ["native_http", "native_grpc", "online_mock", "dynamo_offline"],
    title: {
      executive: "Clock seam",
      developer: "Clock trait seam",
      maintainer: "Clock with RealClock and SimClock",
    },
    summary: {
      executive: "Provides shared timing semantics.",
      developer: "Injects real or virtual time into scheduling and transport.",
      maintainer: "Clock::now_ns/sleep/is_virtual with SimClock controls on concrete type.",
    },
    evidence: [evidence("crates/aiperf-clock/src/clock.rs"), evidence("crates/aiperf-clock/src/sim_clock.rs")],
    seamPorts: [{ id: "port.clock.out", name: "time", channel: "control" }],
    audience: fullAudience,
    footnotes: [],
  },
  {
    id: "node.request-sink-seam",
    tier: 2,
    parentId: "node.runtime-composition",
    childIds: [],
    owner: "rust",
    status: { state: "built", delivery: "unconditional" },
    flavors: ["native_http", "native_grpc", "online_mock", "dynamo_offline"],
    title: {
      executive: "Transport seam",
      developer: "RequestSink seam",
      maintainer: "RequestSink/RequestObserver/Dispatchable",
    },
    summary: {
      executive: "Carries dispatch and observation through one seam.",
      developer: "Normalizes arrival, tokens, usage, and terminal callbacks.",
      maintainer: "loadgen-core sink seam used by HTTP, gRPC, and Dynamo offline.",
    },
    evidence: [evidence("crates/loadgen-core/src/sink.rs")],
    seamPorts: [{ id: "port.sink.out", name: "observer", channel: "telemetry" }],
    audience: fullAudience,
    footnotes: [],
  },
  {
    id: "node.dynamo-online-library-seam",
    tier: 3,
    parentId: "node.runtime-composition",
    childIds: [],
    owner: "rust",
    status: { state: "built", delivery: "library_seam" },
    flavors: ["dynamo_online"],
    title: {
      executive: "Dynamo online library seam",
      developer: "Built library seam for online replay",
      maintainer: "run_scheduled_backend_online",
    },
    summary: {
      executive: "The shared library seam already exists.",
      developer: "Dynamo online is implemented at the aiperf library seam.",
      maintainer: "Built at crates/aiperf/src/dynamo_offline.rs::run_scheduled_backend_online.",
    },
    evidence: [
      {
        path: "crates/aiperf/src/dynamo_offline.rs",
        symbol: "run_scheduled_backend_online",
        role: "source",
      },
    ],
    seamPorts: [{ id: "port.dynamo.online.library", name: "online-replay", channel: "request_data" }],
    audience: fullAudience,
    footnotes: [],
  },
  {
    id: "node.dynamo-online-runner-pair",
    tier: 3,
    parentId: "node.runner-protocol-registries",
    childIds: [],
    owner: "rust",
    status: { state: "planned", delivery: "runner_pair" },
    flavors: ["dynamo_online"],
    title: {
      executive: "Dynamo online runner pair",
      developer: "Planned runner backend/pair",
      maintainer: "Planned aiperf-runner dynamo_online pair",
    },
    summary: {
      executive: "Runner integration remains planned and explicitly unbuilt.",
      developer: "This node tracks planned runner backend/pair registration for Dynamo online.",
      maintainer: "Must remain planned with design evidence until runner pair exists in source.",
    },
    evidence: [
      {
        path: "docs/superpowers/specs/2026-07-12-architecture-atlas-graph-first-redesign.md",
        role: "design",
      },
    ],
    seamPorts: [{ id: "port.dynamo.online.runner", name: "planned-runner-pair", channel: "control" }],
    audience: fullAudience,
    footnotes: [],
  },
];

export const graphNodes = graphNodesRaw as unknown as GraphNode[];

const graphEdgesRaw = [
  ...journeyNodeIds.slice(0, -1).map((id, index) => {
    const next = journeyNodeIds[index + 1];
    return {
      id: `edge.journey.${index + 1}`,
      source: { nodeId: id, portId: `${id}.out` },
      target: { nodeId: next, portId: `${next}.in` },
      channel: "control",
      status: { state: "built", delivery: "unconditional" },
      flavors: [
        "native_http",
        "native_grpc",
        "online_mock",
        "dynamo_offline",
        "dynamo_online",
      ],
      protocol: "Journey control transition",
      evidence: [evidence("docs/superpowers/specs/2026-07-12-architecture-atlas-graph-first-redesign.md")],
      footnotes: [],
    };
  }),
  {
    id: "edge.runtime.dispatch.metrics",
    source: { nodeId: "node.runtime-composition", portId: "port.runtime.out" },
    target: { nodeId: "node.metrics-telemetry", portId: "port.metrics.in" },
    channel: "telemetry",
    status: { state: "built", delivery: "unconditional" },
    flavors: ["native_http", "native_grpc", "online_mock", "dynamo_offline"],
    protocol: "RequestObserver callbacks",
    evidence: [evidence("crates/loadgen-core/src/sink.rs")],
    footnotes: [],
  },
  {
    id: "edge.dataset.to.endpoint",
    source: { nodeId: "node.dataset-segment-pipeline", portId: "port.dataset.out" },
    target: { nodeId: "node.endpoint-bindings-transports", portId: "port.endpoint.in" },
    channel: "request_data",
    status: { state: "built", delivery: "unconditional" },
    flavors: ["native_http", "native_grpc", "online_mock", "dynamo_offline"],
    protocol: "Materialized request payloads",
    evidence: [evidence("crates/aiperf-dataset/src/materialize.rs")],
    footnotes: [],
  },
  {
    id: "edge.metrics.to.result",
    source: { nodeId: "node.metrics-telemetry", portId: "port.metrics.out" },
    target: {
      nodeId: "node.journey.result-returned-to-python",
      portId: "node.journey.result-returned-to-python.in",
    },
    channel: "report_result",
    status: { state: "built", delivery: "unconditional" },
    flavors: ["native_http", "native_grpc", "online_mock", "dynamo_offline"],
    protocol: "native-v2 report payload",
    evidence: [evidence("crates/aiperf-metrics/src/report.rs")],
    footnotes: [],
  },
  {
    id: "edge.dynamo.online.runner.plan",
    source: { nodeId: "node.dynamo-online-library-seam", portId: "port.dynamo.online.library" },
    target: { nodeId: "node.dynamo-online-runner-pair", portId: "port.dynamo.online.runner" },
    channel: "control",
    status: { state: "planned", delivery: "runner_pair" },
    flavors: ["dynamo_online"],
    protocol: "Planned runner pair registration path",
    evidence: [
      {
        path: "docs/superpowers/specs/2026-07-12-architecture-atlas-graph-first-redesign.md",
        role: "design",
      },
    ],
    footnotes: [],
  },
];

export const graphEdges = graphEdgesRaw as unknown as GraphEdge[];

const graphScenesRaw = [
  {
    id: "scene.runtime-composition",
    title: "Runtime composition",
    rustScene: true,
    nodeIds: ["node.runtime-composition", "node.clock-seam", "node.request-sink-seam", "node.dynamo-online-library-seam"],
    edgeIds: ["edge.runtime.dispatch.metrics", "edge.dynamo.online.runner.plan"],
    audience: fullSceneAudience,
  },
  {
    id: "scene.runner-protocol-registries",
    title: "Runner protocol and registries",
    rustScene: true,
    nodeIds: ["node.runner-protocol-registries", "node.dynamo-online-runner-pair"],
    edgeIds: ["edge.dynamo.online.runner.plan"],
    audience: fullSceneAudience,
  },
  {
    id: "scene.scheduling-phase-lifecycle",
    title: "Scheduling and phase lifecycle",
    rustScene: true,
    nodeIds: ["node.scheduling-phase-lifecycle", "node.journey.scheduling-or-graph-ir"],
    edgeIds: ["edge.journey.8"],
    audience: fullSceneAudience,
  },
  {
    id: "scene.dataset-segment-pipeline",
    title: "Dataset and segment pipeline",
    rustScene: true,
    nodeIds: ["node.dataset-segment-pipeline", "node.journey.dataset-materialization"],
    edgeIds: ["edge.journey.9", "edge.dataset.to.endpoint"],
    audience: fullSceneAudience,
  },
  {
    id: "scene.endpoint-bindings-transports",
    title: "Endpoint bindings and HTTP/gRPC transports",
    rustScene: true,
    nodeIds: ["node.endpoint-bindings-transports", "node.journey.endpoint-binding"],
    edgeIds: ["edge.journey.10", "edge.dataset.to.endpoint"],
    audience: fullSceneAudience,
  },
  {
    id: "scene.graph-ir-execution",
    title: "Graph-IR execution",
    rustScene: true,
    nodeIds: ["node.graph-ir-execution", "node.journey.scheduling-or-graph-ir"],
    edgeIds: ["edge.journey.8"],
    audience: fullSceneAudience,
  },
  {
    id: "scene.metrics-telemetry",
    title: "Metrics and telemetry",
    rustScene: true,
    nodeIds: ["node.metrics-telemetry", "node.journey.metrics-and-reporting"],
    edgeIds: ["edge.journey.13", "edge.runtime.dispatch.metrics", "edge.metrics.to.result"],
    audience: fullSceneAudience,
  },
  {
    id: "scene.accuracy-evaluator-hosting",
    title: "Accuracy and evaluator hosting",
    rustScene: true,
    nodeIds: ["node.accuracy-evaluator-hosting", "node.metrics-telemetry"],
    edgeIds: ["edge.metrics.to.result"],
    audience: fullSceneAudience,
  },
  {
    id: "scene.crate-dependency-topology",
    title: "Crate dependency topology",
    rustScene: true,
    nodeIds: ["node.crate-dependency-topology", "node.runner-protocol-registries", "node.runtime-composition", "node.graph-ir-execution"],
    edgeIds: ["edge.runtime.dispatch.metrics", "edge.dataset.to.endpoint"],
    audience: fullSceneAudience,
  },
];

export const graphScenes = graphScenesRaw as unknown as GraphScene[];
