/*
 * SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

import type {
  RenderNodeIr,
  SceneIr,
  SdkOriginIr,
} from "../schema/ir.js";

/** Compiler-only provenance for nodes generated by SDK expansion. */
export type SdkOrigin = SdkOriginIr;

/** Attaches SDK provenance to a render node (compiler-only metadata). */
export function attachSdkOrigin<T extends RenderNodeIr>(
  node: T,
  origin: SdkOrigin,
): T {
  return { ...node, sdkOrigin: origin };
}

/** Removes compiler-only SDK provenance from a render node. */
export function stripSdkOrigin<T extends RenderNodeIr>(node: T): T {
  if (node.sdkOrigin === undefined) {
    return node;
  }

  const { sdkOrigin: _removed, ...rest } = node;
  return rest as T;
}

/** Recursively strips SDK provenance from every node in a scene tree. */
export function stripSdkOriginsFromScene(scene: SceneIr): SceneIr {
  return {
    ...scene,
    roots: scene.roots.map(stripSdkOriginsFromNode),
    responsive: scene.responsive.map((variant) => ({
      ...variant,
      roots: variant.roots.map(stripSdkOriginsFromNode),
    })),
  };
}

function stripSdkOriginsFromNode(node: RenderNodeIr): RenderNodeIr {
  const stripped = stripSdkOrigin(node);
  if (stripped.kind === "group" || stripped.kind === "component") {
    return {
      ...stripped,
      children: stripped.children.map(stripSdkOriginsFromNode),
    };
  }
  return stripped;
}
