// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import type { ArchitectureComponent, ArchitectureEdge } from "../domain/architecture";
import { copy, evidence } from "./helpers";

export const dataPlaneComponents: ArchitectureComponent[] = [
  {
    id: "component.dataset-pipeline",
    kind: "component",
    owner: "rust",
    lifecycleBand: "validation",
    status: "built",
    title: copy("Request content supply", "Typed dataset pipeline", "Loader, composer, sampler, tokenizer, fetch seams"),
    summary: copy(
      "Turns reusable content into controlled, repeatable request populations.",
      "Loads, composes, validates, and samples conversations, raw requests, media, and token arrays.",
      "aiperf-dataset owns registry-selected loaders, endpoint-driven compose validation, remote cache, and tokenizer traits.",
    ),
    evidence: [evidence("crates/dataset/src/lib.rs"), evidence("crates/dataset/src/compose.rs")],
    modes: ["online_http", "online_grpc", "dynamo_offline", "online_mock"],
    contracts: ["DatasetLoader", "SamplerFactory", "Tokenizer"],
    crateIds: ["crate.aiperf-dataset"],
  },
  {
    id: "component.segment-store",
    kind: "component",
    owner: "rust",
    lifecycleBand: "validation",
    status: "built",
    title: copy("Deduplicated prompt memory", "Content-addressed segment store", "Prefix-dependent BLAKE3 dense Handle store"),
    summary: copy(
      "Reuses shared conversation prefixes without changing their meaning.",
      "Interns prompt and response segments, then reconstructs exact context through dense handles.",
      "Segment hashes fold parent identity; materialization clones pre-serialized bytes rather than serializing per request.",
    ),
    evidence: [evidence("crates/dataset/src/segment.rs"), evidence("crates/dataset/src/materialize.rs")],
    modes: ["online_http", "online_grpc", "dynamo_offline", "online_mock"],
    contracts: ["SegmentStore", "PromptMaterializer"],
    crateIds: ["crate.aiperf-dataset"],
  },
  {
    id: "component.endpoint-registry",
    kind: "component",
    owner: "rust",
    lifecycleBand: "validation",
    status: "built",
    title: copy("Protocol portfolio", "Open endpoint registry and dialects", "EndpointFactory registry with PreparedEndpoint bindings"),
    summary: copy(
      "Lets one product target multiple inference APIs while keeping each protocol’s rules explicit.",
      "Validates endpoint identity, compiles configuration once, and prepares worker-local HTTP or gRPC bindings.",
      "EndpointId, descriptors, aliases, RawEndpointConfig, readiness policy, and dense EndpointKey values freeze in RunnerApplication.",
    ),
    evidence: [evidence("crates/endpoints/src/registry.rs"), evidence("crates/endpoints/src/endpoints.rs")],
    modes: ["online_http", "online_grpc", "online_mock"],
    contracts: ["EndpointFactory", "PreparedEndpoint", "dialect readiness"],
    crateIds: ["crate.aiperf-endpoints", "crate.aiperf-extensions"],
  },
  {
    id: "component.graph-ir",
    kind: "component",
    owner: "rust",
    lifecycleBand: "execution",
    status: "built",
    title: copy("Branching workload journeys", "Graph-IR dataflow execution", "GraphTracePlan async-dataflow executor"),
    summary: copy(
      "Models multi-step and branching request behavior with explicit admission and failure policy.",
      "Compiles authored DAG, WEKA, and Dynamo traces into one graph executor with firing gates and fan-in/out.",
      "The current runner graph path is chat-shaped HTTP or offline only; it has no raw-token field and rejects token-required endpoints and unsupported multimodal shapes.",
    ),
    evidence: [evidence("crates/graph/src/lib.rs"), evidence("crates/graph/src/input.rs")],
    modes: ["online_http", "dynamo_offline", "online_mock"],
    contracts: ["GraphSink", "GraphTracePlan", "whole-trace admission"],
    crateIds: ["crate.aiperf-graph"],
  },
  {
    id: "component.content-server",
    kind: "component",
    owner: "rust",
    lifecycleBand: "execution",
    status: "built",
    title: copy("Generated media delivery", "Run-owned content sidecar", "SyntheticMediaPublisher backed by confined Axum server"),
    summary: copy(
      "Publishes generated images and video when inline payloads are unsuitable.",
      "Externalizes stable files, serves MIME and range responses, tracks delivery, and shuts down after drain.",
      "Only scheduled, graph, and static-accuracy online HTTP execute the sidecar; gRPC, offline, agentic, and evaluation reject it.",
    ),
    evidence: [evidence("crates/content-server/src/lib.rs"), evidence("crates/content-server/src/server.rs")],
    modes: ["online_http", "online_mock"],
    contracts: ["SyntheticMediaPublisher", "confined range-serving sidecar"],
    crateIds: ["crate.aiperf-content-server"],
  },
  {
    id: "component.exact-token-ids",
    kind: "component",
    owner: "rust",
    lifecycleBand: "validation",
    status: "built",
    title: copy("Exact token replay", "Raw token-ID request path", "Payload::TokenIds and Turn::raw_token_ids"),
    summary: copy(
      "Preserves exact authored token arrays where decoded text would change the experiment.",
      "Carries validated token handles through scheduled online and offline materialization.",
      "vllm_generate advertises requires_raw_token_ids and bypasses text encoders; direct Graph-IR currently lacks this handle.",
    ),
    evidence: [evidence("crates/dataset/src/request.rs"), evidence("crates/endpoints/src/vllm_generate.rs")],
    modes: ["online_http", "dynamo_offline"],
    contracts: ["exact token input and non-text token output"],
    crateIds: ["crate.aiperf-dataset", "crate.aiperf-endpoints"],
  },
];

export const dataPlaneEdges: ArchitectureEdge[] = [
  {
    id: "edge.dataset-segments",
    kind: "dependency",
    from: "component.dataset-pipeline",
    to: "component.segment-store",
    label: "Intern composed content",
    contract: "dense prefix-dependent handles",
    status: "built",
    evidence: [evidence("crates/dataset/src/compose.rs")],
  },
  {
    id: "edge.segments-endpoint",
    kind: "message",
    from: "component.segment-store",
    to: "component.endpoint-registry",
    label: "Materialize endpoint-ready input",
    protocol: "prepared canonical request",
    status: "built",
    evidence: [evidence("crates/dataset/src/materialize.rs")],
  },
  {
    id: "edge.graph-segments",
    kind: "dependency",
    from: "component.graph-ir",
    to: "component.segment-store",
    label: "Share graph content handles",
    contract: "frozen SegmentStore",
    status: "built",
    evidence: [evidence("crates/graph/src/materialize.rs")],
  },
  {
    id: "edge.content-server-dataset",
    kind: "dependency",
    from: "component.content-server",
    to: "component.dataset-pipeline",
    label: "Publish generated media",
    contract: "SyntheticMediaPublisher injection",
    status: "built",
    evidence: [evidence("crates/content-server/src/publisher.rs")],
  },
  {
    id: "edge.tokens-endpoint",
    kind: "message",
    from: "component.exact-token-ids",
    to: "component.endpoint-registry",
    label: "Dispatch exact token arrays",
    protocol: "raw token handles",
    status: "built",
    evidence: [evidence("crates/endpoints/src/vllm_generate.rs")],
  },
];
