// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import type {
  ArchitectureComponent,
  ArchitectureEdge,
  PairSupport,
} from "../domain/architecture";
import { copy, evidence, rangedEvidence } from "./helpers";

export const executionComponents: ArchitectureComponent[] = [
  {
    id: "component.clock-seam",
    kind: "component",
    owner: "rust",
    lifecycleBand: "execution",
    status: "built",
    title: copy("Consistent time model", "Injected execution clock", "Clock with RealClock and SimClock"),
    summary: copy(
      "Keeps real service tests and deterministic simulations comparable without pretending their values are identical.",
      "Scheduling, deadlines, ramps, and observations consume one clock contract.",
      "Clock exposes now_ns, sleep, and is_virtual; SimClock alone owns heap-ordered next_event_time and advance_to controls.",
    ),
    evidence: [evidence("crates/clock/src/clock.rs"), evidence("crates/clock/src/sim_clock.rs")],
    modes: ["online_http", "online_grpc", "dynamo_offline", "online_mock"],
    contracts: ["monotonic nanosecond clock", "deterministic virtual sleepers"],
    crateIds: ["crate.aiperf-clock"],
  },
  {
    id: "component.scheduling",
    kind: "component",
    owner: "rust",
    lifecycleBand: "execution",
    status: "built",
    title: copy("Load policy", "Clock-paced scheduling", "Workload, SlotPool, StopChecker"),
    summary: copy(
      "Turns business load goals into bounded, repeatable request pressure.",
      "Supports paced, request-rate, user-centric, fixed-schedule, and graph admission with explicit stop bounds.",
      "ScheduledRuntime combines workload-local futures with debt-draining session/prefill SlotPool policy and Clock-native intervals.",
    ),
    evidence: [evidence("crates/aiperf/src/scheduled.rs"), evidence("crates/timing/src/slots.rs")],
    modes: ["online_http", "online_grpc", "dynamo_offline", "online_mock"],
    contracts: ["arrival pacing", "session and prefill admission"],
    crateIds: ["crate.aiperf", "crate.aiperf-timing"],
  },
  {
    id: "component.phases-controls",
    kind: "component",
    owner: "rust",
    lifecycleBand: "execution",
    status: "built",
    title: copy("Safe run lifecycle", "Phases and live controls", "ClockPhaseOrchestrator plus adaptive and ancillary drivers"),
    summary: copy(
      "Separates warmup from evidence collection and bounds cancellation and drain risk.",
      "Coordinates warmup, profiling, grace, cancel, drain, ramps, and adaptive SLA control.",
      "PhaseLifecycle escalates duration to grace, cancel, bounded drain, and force completion; controls mutate local slot/rate/user actuators.",
    ),
    evidence: [evidence("crates/timing/src/phase/mod.rs"), evidence("crates/adaptive/src/runtime.rs")],
    modes: ["online_http", "dynamo_offline", "online_mock"],
    contracts: ["phase lifecycle", "adaptive actuator", "ramp and cancellation policy"],
    crateIds: ["crate.aiperf-timing", "crate.aiperf-adaptive"],
  },
  {
    id: "component.http-transport",
    kind: "component",
    owner: "rust",
    lifecycleBand: "execution",
    status: "built",
    title: copy("Web inference path", "Native HTTP and SSE transport", "Clock-injected Hyper transport"),
    summary: copy(
      "Measures production-style web inference with connection and streaming detail.",
      "Supports h1, h2c, Unix sockets, TLS, streaming, reuse, and post-send cancellation.",
      "Low-level Hyper bindings preserve raw SSE line boundaries, aiohttp-style trace facts, SendCompletion, and endpoint-owned lifecycle parsing.",
    ),
    evidence: [evidence("crates/transport-http/src/lib.rs")],
    modes: ["online_http", "online_mock"],
    contracts: ["HttpEndpointBinding", "HTTP trace and SSE lifecycle"],
    crateIds: ["crate.aiperf-transport-http"],
  },
  {
    id: "component.grpc-transport",
    kind: "component",
    owner: "rust",
    lifecycleBand: "execution",
    status: "built",
    title: copy("Native RPC inference path", "KServe and Riva gRPC transport", "Clock-injected Tonic raw RPC transport"),
    summary: copy(
      "Measures typed inference services without routing through Python plugins.",
      "Supports KServe OIP and Riva unary or streaming calls with TLS, metadata, reuse, and cancellation, but rejects readiness retries and every sidecar.",
      "GrpcEndpointBinding factories own codecs; runner validation requires wait_for_model_timeout <= 0, rejects every authored sidecar, and has no graph pair.",
    ),
    evidence: [
      evidence("crates/transport-grpc/src/lib.rs"),
      rangedEvidence("crates/runner/src/grpc_execution.rs", 164, 195),
    ],
    modes: ["online_grpc"],
    contracts: ["GrpcEndpointBinding", "Tonic status and trace mapping"],
    crateIds: ["crate.aiperf-transport-grpc"],
  },
  {
    id: "component.online-mock",
    kind: "component",
    owner: "rust",
    lifecycleBand: "execution",
    status: "built",
    title: copy("Repeatable online target", "Standalone HTTP mock server", "aiperf-mock-rs ordinary network peer"),
    summary: copy(
      "Enables realistic network-path tests without depending on a model deployment.",
      "Exposes ordinary HTTP/SSE endpoint dialects with analytic or batch-scheduler latency.",
      "The mock binary is launched independently and has no dependency edge from runner or transport crates.",
    ),
    evidence: [evidence("crates/mock-rs/src/lib.rs")],
    modes: ["online_mock"],
    contracts: ["ordinary HTTP target"],
    crateIds: ["crate.aiperf-mock-rs"],
  },
  {
    id: "component.dynamo-offline",
    kind: "component",
    owner: "rust",
    lifecycleBand: "execution",
    status: "feature-gated",
    title: copy("Deterministic capacity simulation", "In-process Dynamo offline backend", "dynamo-offline SteppableReplay adapter"),
    summary: copy(
      "Explores timing and topology decisions quickly without sockets or a semantic model.",
      "Runs scheduled and graph workloads against an in-process virtual-clock engine.",
      "The non-default feature requires a sibling Dynamo checkout, one simulator endpoint, single worker placement, no sidecars, and no semantic accuracy.",
    ),
    evidence: [evidence("crates/aiperf/src/dynosim.rs"), evidence("crates/runner/src/offline_execution.rs")],
    modes: ["dynamo_offline"],
    contracts: ["SteppableReplay", "byte-equal common summary"],
    crateIds: ["crate.aiperf"],
  },
  {
    id: "component.worker-placement",
    kind: "component",
    owner: "rust",
    lifecycleBand: "execution",
    status: "built",
    title: copy("Scalable local execution", "Thread-per-core placement", "OS thread current_thread runtime plus LocalSet"),
    summary: copy(
      "Scales request work while avoiding shared per-token contention.",
      "Each worker owns local request state and metrics, then merges once after execution.",
      "Hot paths use Rc, RefCell, !Send futures, spawn_local, and worker-local MetricsAccumulator; Arc/Mutex is excluded from per-token work.",
    ),
    evidence: [evidence("crates/graph/src/runtime.rs"), evidence("crates/graph/src/placement.rs")],
    modes: ["online_http", "online_grpc", "online_mock"],
    contracts: ["worker-local placement and final merge"],
    crateIds: ["crate.aiperf-graph"],
  },
];

export const executionEdges: ArchitectureEdge[] = [
  {
    id: "edge.clock-paces-scheduling",
    kind: "control",
    from: "component.clock-seam",
    to: "component.scheduling",
    label: "Pace arrivals and deadlines",
    control: "Clock sleep and monotonic timestamps",
    status: "built",
    evidence: [evidence("crates/timing/src/intervals.rs")],
  },
  {
    id: "edge.controls-adjust-scheduling",
    kind: "control",
    from: "component.phases-controls",
    to: "component.scheduling",
    label: "Adjust live admission",
    control: "phase ramps and adaptive actuators",
    status: "built",
    evidence: [evidence("crates/adaptive/src/actuator.rs")],
  },
  {
    id: "edge.scheduling-http",
    kind: "message",
    from: "component.scheduling",
    to: "component.http-transport",
    label: "Dispatch prepared HTTP work",
    protocol: "RequestSink<HttpRequest>",
    status: "built",
    evidence: [evidence("crates/aiperf/src/http.rs")],
  },
  {
    id: "edge.scheduling-grpc",
    kind: "message",
    from: "component.scheduling",
    to: "component.grpc-transport",
    label: "Dispatch prepared gRPC work",
    protocol: "RequestSink<GrpcRequest>",
    status: "built",
    evidence: [evidence("crates/aiperf/src/grpc.rs")],
  },
  {
    id: "edge.scheduling-offline",
    kind: "message",
    from: "component.scheduling",
    to: "component.dynamo-offline",
    label: "Dispatch simulated work",
    protocol: "RequestSink over SteppableReplay",
    status: "feature-gated",
    evidence: [evidence("crates/aiperf/src/dynosim.rs")],
  },
];

const pairEvidence = [
  rangedEvidence("crates/runner/src/registry.rs", 2131, 2167),
];

export const executionPairSupport: PairSupport[] = [
  {
    id: "pair.online-http-scheduled",
    mode: "online_http",
    workload: "scheduled",
    status: "built",
    notes: copy("Primary production load path.", "Scheduled HTTP execution is registered.", "Base RunnerApplication installs online_http plus scheduled."),
    evidence: pairEvidence,
  },
  {
    id: "pair.online-http-graph",
    mode: "online_http",
    workload: "graph",
    status: "built",
    notes: copy("Branching request journeys run online.", "Graph-IR dispatches through HTTP.", "Graph transport remains chat-shaped HTTP with no raw-token handle."),
    evidence: pairEvidence,
  },
  {
    id: "pair.online-grpc-scheduled",
    mode: "online_grpc",
    workload: "scheduled",
    status: "built",
    notes: copy("Typed RPC load is available.", "Scheduled gRPC execution is registered.", "Native gRPC has no graph or sidecar pair."),
    evidence: pairEvidence,
  },
  {
    id: "pair.online-grpc-graph",
    mode: "online_grpc",
    workload: "graph",
    status: "unbuilt",
    notes: copy("Branching RPC journeys are not available.", "The registry rejects gRPC plus graph.", "No GrpcRequest GraphSink adapter or executable pair exists."),
    evidence: pairEvidence,
  },
  {
    id: "pair.dynamo-offline-scheduled",
    mode: "dynamo_offline",
    workload: "scheduled",
    status: "feature-gated",
    notes: copy("Deterministic timing studies require a special build.", "Offline scheduled execution is feature-gated.", "dynamo-offline adds the pair only when linked against the sibling mocker."),
    evidence: pairEvidence,
  },
  {
    id: "pair.dynamo-offline-graph",
    mode: "dynamo_offline",
    workload: "graph",
    status: "feature-gated",
    notes: copy("Deterministic branching studies require a special build.", "Offline Graph-IR is feature-gated.", "The pair uses SimClock and SteppableReplay without sockets."),
    evidence: pairEvidence,
  },
  {
    id: "pair.online-http-static-accuracy",
    mode: "online_http",
    workload: "static_accuracy",
    status: "legacy-parallel",
    notes: copy("Established benchmark scoring remains available.", "Rust transport works with Python-owned static semantics.", "AccuracyEvaluator remains a legacy Python worker seam."),
    evidence: pairEvidence,
  },
  {
    id: "pair.online-http-agentic",
    mode: "online_http",
    workload: "agentic",
    status: "legacy-parallel",
    notes: copy("Tool and environment evaluations retain proven providers.", "Agent model turns broker through Rust HTTP scheduling.", "Pinned Harbor, BrowserGym/AgentLab, and MCPMark own loop semantics."),
    evidence: pairEvidence,
  },
  {
    id: "pair.online-http-evaluation",
    mode: "online_http",
    workload: "evaluation",
    status: "runtime-conditional",
    notes: copy("A tightly bounded neutral evaluation preview is available in attested deployments.", "The pair appears only when provider roots and isolation attest.", "Only NeMo 0.4.0 and OpenBench 0.5.3 five-record GSM8K canaries are registered."),
    evidence: [evidence("crates/runner/src/stock_evaluation.rs")],
  },
  {
    id: "pair.online-http-telemetry-watch",
    mode: "online_http",
    workload: "telemetry_watch",
    status: "built",
    notes: copy(
      "Continuous telemetry capture runs without model traffic.",
      "The source-only telemetry watch workload executes over the online HTTP backend.",
      "BuiltinRunnerRegistryFactory registers telemetry_watch and the online_http pair with models, endpoints, metrics, and sidecars forbidden.",
    ),
    evidence: [
      rangedEvidence("crates/runner/src/registry.rs", 873, 883),
      rangedEvidence("crates/runner/src/registry.rs", 2131, 2167),
      evidence("crates/runner/src/telemetry_operation.rs"),
    ],
  },
];
