// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import type { ArchitectureComponent, ArchitectureEdge } from "../domain/architecture";
import { copy, evidence } from "./helpers";

export const observabilityComponents: ArchitectureComponent[] = [
  {
    id: "component.native-metrics",
    kind: "component",
    owner: "rust",
    lifecycleBand: "measurement",
    status: "built",
    title: copy("Performance evidence", "Native metrics and reporting", "MetricsAccumulator, sweep-lines, and Reporter"),
    summary: copy(
      "Converts request timing into latency, throughput, goodput, and scale evidence.",
      "Accumulates sparse request facts, reconciles authoritative usage, computes phase windows and sweep curves, and emits native-v2.",
      "aiperf-metrics is IO-free; worker-local stores merge deterministically and reject non-finite serialization values.",
    ),
    evidence: [evidence("crates/metrics/src/lib.rs"), evidence("crates/metrics/src/accumulator.rs")],
    modes: ["online_http", "online_grpc", "dynamo_offline", "online_mock"],
    contracts: ["RequestObserver facts", "native-v2 report"],
    crateIds: ["crate.aiperf-metrics", "crate.loadgen-core"],
  },
  {
    id: "component.live-telemetry",
    kind: "component",
    owner: "rust",
    lifecycleBand: "measurement",
    status: "built",
    title: copy("System context", "GPU, server, and network telemetry", "DCGM, Prometheus, and TCP-connect producer leaves"),
    summary: copy(
      "Explains performance changes with accelerator, server, and network context.",
      "Collects GPU energy and gauges, server metrics, and fresh connection latency alongside run metrics.",
      "Producer crates depend toward the IO-free metrics seam; aiperf-prometheus supplies the bounded exposition parser used by server telemetry.",
    ),
    evidence: [
      evidence("crates/gpu-telemetry/src/lib.rs"),
      evidence("crates/server-metrics/src/lib.rs"),
      evidence("crates/network-latency/src/lib.rs"),
    ],
    modes: ["online_http", "online_grpc", "online_mock"],
    contracts: ["side-channel accumulator", "phase-boundary snapshots"],
    crateIds: ["crate.aiperf-gpu-telemetry", "crate.aiperf-server-metrics", "crate.aiperf-network-latency", "crate.aiperf-prometheus"],
  },
  {
    id: "component.telemetry-archive",
    kind: "component",
    owner: "rust",
    lifecycleBand: "measurement",
    status: "built",
    title: copy("Durable telemetry history", "Telemetry archive and recovery", "aiperf-telemetry-archive WAL and store seams"),
    summary: copy(
      "Preserves telemetry evidence with explicit durability and loss accounting.",
      "Provides bounded ingest, write-ahead logging, manifests, recovery, projections, and storage abstractions.",
      "The archive owns canonical identities, receipts, loss ledgers, Arrow/Parquet encoding, object/filesystem stores, and clock-aware lifecycle policy.",
    ),
    evidence: [evidence("crates/telemetry-archive/src/lib.rs"), evidence("crates/telemetry-archive/src/wal.rs")],
    modes: ["online_http", "online_grpc", "online_mock"],
    contracts: ["durable telemetry WAL", "loss ledger and manifest"],
    crateIds: ["crate.aiperf-telemetry-archive"],
  },
  {
    id: "component.static-accuracy",
    kind: "component",
    owner: "legacy",
    lifecycleBand: "measurement",
    status: "legacy-parallel",
    title: copy("Established answer quality", "Static benchmark evaluation", "Legacy AccuracyEvaluator worker"),
    summary: copy(
      "Retains benchmark-grounded quality scoring while native transport measures every model request.",
      "Python owns benchmark datasets, prompts, hidden tests, and scoring over an opaque correlated worker protocol.",
      "Rust owns scheduling, endpoint I/O, records, and reporting; ground truth never crosses into Rust.",
    ),
    evidence: [evidence("crates/accuracy/src/protocol.rs"), evidence("crates/aiperf/src/accuracy.rs")],
    modes: ["online_http"],
    contracts: ["opaque evaluator task IDs", "JSONL worker protocol"],
    crateIds: ["crate.aiperf-accuracy", "crate.aiperf"],
  },
  {
    id: "component.agentic-evaluation",
    kind: "component",
    owner: "legacy",
    lifecycleBand: "measurement",
    status: "legacy-parallel",
    title: copy("Environment and tool quality", "Agentic benchmark providers", "AgenticHarnessProvider and Rust inference gateway"),
    summary: copy(
      "Preserves proven tool, browser, terminal, and service evaluation environments.",
      "Pinned Python providers own loops and verifiers while every model turn enters Rust scheduling and transport.",
      "Harbor, AgentLab/BrowserGym, and MCPMark have independent locks; infrastructure failures stay outside score denominators.",
    ),
    evidence: [evidence("crates/aiperf/src/agentic.rs"), evidence("crates/aiperf/src/agentic_gateway.rs")],
    modes: ["online_http"],
    contracts: ["AgenticHarness", "authenticated inference gateway"],
    crateIds: ["crate.aiperf", "crate.aiperf-accuracy"],
  },
  {
    id: "component.provider-evaluation",
    kind: "component",
    owner: "external",
    lifecycleBand: "measurement",
    status: "runtime-conditional",
    title: copy("Bounded neutral evaluation", "Provider-neutral evaluator host", "Attested evaluator protocol v2 and Bubblewrap isolation"),
    summary: copy(
      "Offers a small, controlled path for independently packaged evaluators where deployment attestation succeeds.",
      "Supervises typed host operations, fair inference admission, retries, artifacts, and an isolated compatibility proxy.",
      "Only NeMo Evaluator 0.4.0 and OpenBench 0.5.3 plus Inspect 0.3.141 five-record GSM8K canaries are exposed; roots and Linux isolation must attest.",
    ),
    evidence: [evidence("crates/accuracy/src/provider.rs"), evidence("crates/accuracy/src/isolation.rs"), evidence("crates/runner/src/stock_evaluation.rs")],
    modes: ["online_http"],
    contracts: ["evaluator-worker protocol v2", "quiescence-gated artifact sealing"],
    crateIds: ["crate.aiperf-accuracy", "crate.aiperf"],
  },
];

export const observabilityEdges: ArchitectureEdge[] = [
  {
    id: "edge.runtime-native-metrics",
    kind: "message",
    from: "component.rust-runtime",
    to: "component.native-metrics",
    label: "Record timing, tokens, usage, and terminal state",
    protocol: "RequestObserver callbacks",
    status: "built",
    evidence: [evidence("crates/loadgen-core/src/sink.rs")],
  },
  {
    id: "edge.telemetry-native-metrics",
    kind: "dependency",
    from: "component.live-telemetry",
    to: "component.native-metrics",
    label: "Join side-channel observations",
    contract: "accumulator finalize join",
    status: "built",
    evidence: [evidence("crates/gpu-telemetry/src/accumulator.rs")],
  },
  {
    id: "edge.telemetry-archive",
    kind: "message",
    from: "component.live-telemetry",
    to: "component.telemetry-archive",
    label: "Archive bounded telemetry frames",
    protocol: "versioned archive frames and receipts",
    status: "built",
    evidence: [evidence("crates/telemetry-archive/src/sink.rs")],
  },
  {
    id: "edge.static-metrics",
    kind: "dependency",
    from: "component.static-accuracy",
    to: "component.native-metrics",
    label: "Join quality and performance records",
    contract: "native-v2 accuracy block",
    status: "legacy-parallel",
    evidence: [evidence("crates/metrics/src/accuracy.rs")],
  },
  {
    id: "edge.agentic-runtime",
    kind: "message",
    from: "component.agentic-evaluation",
    to: "component.rust-runtime",
    label: "Broker each model turn",
    protocol: "authenticated agentic inference gateway",
    status: "legacy-parallel",
    evidence: [evidence("crates/aiperf/src/agentic_gateway.rs")],
  },
  {
    id: "edge.provider-runtime",
    kind: "message",
    from: "component.provider-evaluation",
    to: "component.rust-runtime",
    label: "Arbitrate evaluator inference",
    protocol: "typed host operation or scoped Unix proxy",
    status: "runtime-conditional",
    evidence: [evidence("crates/aiperf/src/evaluation.rs")],
  },
];
