# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "aiperf-export-sdk"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aiperf-core.workspace = true
aiperf-plugin-api.workspace = true

[dev-dependencies]
aiperf-plugin-test-support.workspace = true
