# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "aiperf-plugin-conformance"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aiperf-core.workspace = true
aiperf-endpoint-sdk.workspace = true
aiperf-export-sdk.workspace = true
aiperf-plugin-api.workspace = true
aiperf-plugin-host.workspace = true
aiperf-plugin-sdk.workspace = true
aiperf-transport-sdk.workspace = true
