#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Write the commit SHA into src/aiperf/_build_info.py.

Called by CI build workflows (pr, post-merge, nightly) immediately before
`docker buildx`, against a freshly checked-out tree. After install,
`aiperf.__commit_sha__` returns the SHA.

The clickable commit URL is recoverable as
`{[project.urls].Repository}/commit/{aiperf.__commit_sha__}` — Repository
lives statically in pyproject.toml as the canonical repo URL, and is not
mutated here. (Per PEP 621 convention, Repository points at the repo, not
a specific commit.)

This file is intentionally NOT shipped inside the wheel — it lives in
`tools/` so it's a build-time utility, not a runtime dependency of aiperf.
"""

from __future__ import annotations

import sys
from pathlib import Path


def embed(sha: str) -> None:
    build_info = Path("src/aiperf/_build_info.py")
    build_info.write_text(
        "# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.\n"
        "# SPDX-License-Identifier: Apache-2.0\n"
        '"""Build-time metadata. Generated by CI; do not edit."""\n'
        "\n"
        f'COMMIT_SHA = "{sha}"\n'
    )
    print(f"Wrote {build_info} with COMMIT_SHA = {sha}")


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("usage: embed_commit_sha.py <commit_sha>", file=sys.stderr)
        return 2
    embed(argv[1])
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
