# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Generate ``rng_parity/ziggurat_tables.py`` from the ``rand_distr`` source.

The parity RNG (``aiperf.common.rng_parity``) reproduces ``rand_distr``'s ziggurat
sampling byte-for-byte. That requires the exact ziggurat tables shipped by
``rand_distr``. This script parses ``rand_distr-0.5.1/src/ziggurat_tables.rs`` (the
autogenerated table module) and emits an equivalent Python module.

Both Rust and Python parse the decimal float literals with round-to-nearest-even, so
the resulting IEEE-754 ``f64`` bit patterns are identical; the parity tests assert this.

Usage:
    python tools/gen_ziggurat_tables.py [path/to/ziggurat_tables.rs]

If no path is given, the script locates ``rand_distr-0.5.1`` in the cargo registry.
"""

from __future__ import annotations

import glob
import os
import re
import sys

RAND_DISTR_VERSION = "0.5.1"

# Scalars and 257-entry arrays we need for Exp/Normal sampling.
_SCALAR_NAMES = ("ZIG_NORM_R", "ZIG_EXP_R")
_ARRAY_NAMES = ("ZIG_NORM_X", "ZIG_NORM_F", "ZIG_EXP_X", "ZIG_EXP_F")


def _locate_source() -> str:
    """Return the path to ``ziggurat_tables.rs`` in the cargo registry."""
    home = os.path.expanduser("~")
    pattern = os.path.join(
        home,
        ".cargo",
        "registry",
        "src",
        "index.crates.io-*",
        f"rand_distr-{RAND_DISTR_VERSION}",
        "src",
        "ziggurat_tables.rs",
    )
    matches = glob.glob(pattern)
    if not matches:
        raise SystemExit(
            f"could not find rand_distr-{RAND_DISTR_VERSION}/src/ziggurat_tables.rs; "
            "pass the path explicitly"
        )
    return matches[0]


def _parse(text: str) -> tuple[dict[str, str], dict[str, list[str]]]:
    """Parse scalar consts and 257-entry static arrays from the Rust source."""
    scalars: dict[str, str] = {}
    for name in _SCALAR_NAMES:
        match = re.search(rf"const {name}: f64 = ([0-9eE+\-.]+);", text)
        if not match:
            raise SystemExit(f"scalar {name} not found in source")
        scalars[name] = match.group(1)

    arrays: dict[str, list[str]] = {}
    for name in _ARRAY_NAMES:
        # `static ZIG_XXX: [f64; 257] = [ <comma separated literals> ];`
        match = re.search(
            rf"static {name}: \[f64; 257\] =\s*\[(.*?)\];",
            text,
            re.DOTALL,
        )
        if not match:
            raise SystemExit(f"array {name} not found in source")
        literals = [tok.strip() for tok in match.group(1).split(",")]
        literals = [tok for tok in literals if tok]
        if len(literals) != 257:
            raise SystemExit(f"array {name} has {len(literals)} entries, expected 257")
        arrays[name] = literals
    return scalars, arrays


def _format_array(name: str, literals: list[str]) -> str:
    lines = [f"{name}: tuple[float, ...] = ("]
    for start in range(0, len(literals), 4):
        chunk = literals[start : start + 4]
        lines.append("    " + ", ".join(chunk) + ",")
    lines.append(")")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    src = argv[1] if len(argv) > 1 else _locate_source()
    with open(src, encoding="utf-8") as handle:
        text = handle.read()
    scalars, arrays = _parse(text)

    out_dir = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "src",
        "aiperf",
        "common",
        "rng_parity",
    )
    out_path = os.path.join(out_dir, "ziggurat_tables.py")

    parts: list[str] = [
        "# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. "
        "All rights reserved.",
        "# SPDX-License-Identifier: Apache-2.0",
        "",
        '"""Ziggurat tables for the parity RNG — GENERATED, do not hand-edit.',
        "",
        f"Transcribed from rand_distr-{RAND_DISTR_VERSION}/src/ziggurat_tables.rs by",
        "tools/gen_ziggurat_tables.py. The decimal literals parse to the same IEEE-754",
        "f64 bits in Rust and Python (round-to-nearest-even), so ziggurat sampling is",
        'byte-exact across the two implementations.',
        '"""',
        "",
    ]
    for name in _SCALAR_NAMES:
        parts.append(f"{name}: float = {scalars[name]}")
    parts.append("")
    for name in _ARRAY_NAMES:
        parts.append(_format_array(name, arrays[name]))
        parts.append("")

    os.makedirs(out_dir, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(parts))
    print(f"wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
