image:
  repository: nvcr.io/nvidian/dynamo-dev/aiperf
  tag: k8s-multi-20260501-131740-28affb7e0
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: nvcr-imagepullsecret

operator:
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
  nodeSelector:
    kubernetes.io/arch: amd64
    nodeGroup: customer-cpu
  tolerations: []

resultsServer:
  port: 8081
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi

storage:
  enabled: true
  size: 200Gi
  storageClassName: ebs
  accessMode: ReadWriteOnce
  mountPath: /data

benchmarkNamespace:
  create: false
  name: acasagrande-aiperf-bench

benchmarkRbacNamespaces: []

rbac:
  create: true

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false
