apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: customer-cpu
spec:
  nodeLabels:
    nodeGroup: customer-cpu
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: aiperf-bench-cq
spec:
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: acasagrande-aiperf-bench
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: customer-cpu
      resources:
      - { name: "cpu",    nominalQuota: 170 }
      - { name: "memory", nominalQuota: 700Gi }
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: acasagrande-aiperf-bench
  name: aiperf-lq
spec:
  clusterQueue: aiperf-bench-cq
