apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: customer-cpu
spec:
  nodeLabels:
    nodeGroup: customer-cpu
  tolerations:
  - { effect: NoSchedule, key: dedicated, operator: Equal, value: user-workload }
  - { effect: NoExecute,  key: dedicated, operator: Equal, value: user-workload }
  - { effect: NoSchedule, key: team, operator: Equal, value: nemo-ci }
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: system-cpu
spec:
  nodeLabels:
    nodeGroup: system-cpu
  tolerations:
  - { effect: NoSchedule, key: dedicated, operator: Equal, value: user-workload }
  - { effect: NoExecute,  key: dedicated, operator: Equal, value: user-workload }
  - { effect: NoSchedule, key: team, operator: Equal, value: nemo-ci }
  - { effect: NoExecute, key: components.gke.io/gke-managed-components, operator: Equal, value: "true" }
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: aiperf-bench-cq
spec:
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: acasagrande-aiperf-bench
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: system-cpu
      resources:
      - { name: "cpu", nominalQuota: 140 }
      - { name: "memory", nominalQuota: 540Gi }
    - name: customer-cpu
      resources:
      - { name: "cpu", nominalQuota: 22 }
      - { name: "memory", nominalQuota: 80Gi }
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: acasagrande-aiperf-bench
  name: aiperf-lq
spec:
  clusterQueue: aiperf-bench-cq
