apiVersion: aiperf.nvidia.com/v1alpha1
kind: AIPerfJob
metadata:
  name: stress-500k-1m-osl1k
  namespace: acasagrande-aiperf-bench
spec:
  image: nvcr.io/nvidian/dynamo-dev/aiperf:k8s-multi-20260501-131740-28affb7e0
  connectionsPerWorker: 2000
  resourceMode: burstable
  ttlSecondsAfterFinished: 3600
  benchmark:
    models: { items: [{ name: mock }] }
    tokenizer: { name: builtin }
    endpoint:
      streaming: true
      useServerTokenCount: true
      timeout: 600
      urls:
        - http://aiperf-mock-server.acasagrande-aiperf-bench.svc.cluster.local:8000/v1/chat/completions
    datasets:
      - name: main
        type: synthetic
        prompts:
          isl: { mean: 550 }
          osl: 1000
    phases:
      - name: profiling
        type: concurrency
        concurrency: 500000
        requests: 1000000
    runtime:
      ui: none
      workers: 1500
      workersPerPod: 20
      recordProcessorsPerPod: 4
    artifacts: {}
    gpuTelemetry: { enabled: false }
    serverMetrics: { enabled: true }
  podTemplate:
    imagePullSecrets: [nvcr-imagepullsecret]
    nodeSelector: { kubernetes.io/arch: amd64, nodeGroup: customer-cpu }
