apiVersion: aiperf.nvidia.com/v1alpha1
kind: AIPerfSweep
metadata:
  name: sweep-1k-10k-aws-dev-02
  namespace: acasagrande-aiperf-bench
spec:
  ttlSecondsAfterFinished: 86400
  failurePolicy:
    onChildFailure: continue
    maxFailures: 0
  sweep:
    type: scenarios
    runs:
      - name: c1k
        phases:
          - name: profiling
            concurrency: 1000
            duration: 2m
      - name: c2k
        phases:
          - name: profiling
            concurrency: 2000
            duration: 2m
      - name: c3k
        phases:
          - name: profiling
            concurrency: 3000
            duration: 2m
      - name: c4k
        phases:
          - name: profiling
            concurrency: 4000
            duration: 2m
      - name: c5k
        phases:
          - name: profiling
            concurrency: 5000
            duration: 2m
      - name: c6k
        phases:
          - name: profiling
            concurrency: 6000
            duration: 2m
      - name: c7k
        phases:
          - name: profiling
            concurrency: 7000
            duration: 2m
      - name: c8k
        phases:
          - name: profiling
            concurrency: 8000
            duration: 2m
      - name: c9k
        phases:
          - name: profiling
            concurrency: 9000
            duration: 2m
      - name: c10k
        phases:
          - name: profiling
            concurrency: 10000
            duration: 2m
  template:
    spec:
      image: nvcr.io/nvidian/dynamo-dev/aiperf:k8s-multi-20260501-131740-28affb7e0
      connectionsPerWorker: 1000
      resourceMode: burstable
      ttlSecondsAfterFinished: 1800
      benchmark:
        models:
          items:
            - name: mock
        tokenizer:
          name: builtin
        endpoint:
          streaming: true
          useServerTokenCount: true
          urls:
            - http://aiperf-mock-server-rs.acasagrande-aiperf-bench.svc.cluster.local:8000/v1/chat/completions
        datasets:
          - name: main
            type: synthetic
            prompts:
              isl:
                mean: 550
              osl: 2500
        phases:
          - name: profiling
            type: concurrency
            concurrency: 10000
            duration: 2m
        runtime:
          ui: none
          workers: 30
          workersPerPod: 10
          recordProcessorsPerPod: 2
        artifacts: {}
        gpuTelemetry:
          enabled: false
        serverMetrics:
          enabled: false
      podTemplate:
        imagePullSecrets:
          - nvcr-imagepullsecret
        nodeSelector:
          kubernetes.io/arch: amd64
          nodeGroup: customer-cpu
