# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent
serviceAccount:
  create: true
  name: aiperf-k8s-operator
rbac:
  create: true
jobset:
  enabled: true
api:
  port: 8080
  serviceName: aiperf-k8s-operator
persistence:
  size: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClass: ""
