# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
name: Coverage Report

on:
  push:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Set up Python and dependencies with uv
        run: |
          uv venv --python 3.10
          source .venv/bin/activate
          uv pip install -e ".[dev]"

      - name: Run tests and collect coverage
        run: |
          source .venv/bin/activate
            pytest --cov=aiperf --cov-branch --cov-report=xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ai-dynamo/aiperf
