# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
name: "Pre-commit"

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Fetch base commit
      run: |
        git remote add base "${{ github.event.pull_request.base.repo.clone_url }}"
        git fetch --no-tags --depth=1 base ${{ github.event.pull_request.base.sha }}

    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        make setup-venv
        make setup-mkinit

    - uses: pre-commit/action@v3.0.1
      env:
        SKIP: mkinit
      with:
        extra_args: >-
          --from-ref ${{ github.event.pull_request.base.sha }}
          --to-ref   ${{ github.sha }}
