# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: Test Suite
on: push

jobs:
  unit-tests:
    name: Unit Tests (Py ${{ matrix.python-version }} • ${{ matrix.arch_alias }})
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        arch: ["amd64", "arm64"]
        include:
          - arch: amd64
            arch_alias: x86_64
            docker_platform: linux/amd64
          - arch: arm64
            arch_alias: aarch64
            docker_platform: linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install QEMU only when targeting arm64
      - name: Set up QEMU for arm64
        if: matrix.arch == 'arm64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run unit tests in platformed Python image
        run: |
          docker run --rm \
            --platform=${{ matrix.docker_platform }} \
            -v "$PWD":/w -w /w \
            python:${{ matrix.python-version }}-slim \
            bash -lc '
              python -m pip install -U pip
              python -m pip install ".[dev]"
              pytest tests --ignore=tests/integration -v
            '

  # integration-tests:
  #   name: Integration Tests (Python ${{ matrix.python-version }})
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       python-version: ["3.10", "3.11", "3.12", "3.13"]
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #     - name: Install uv
  #       uses: astral-sh/setup-uv@v6
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #         activate-environment: true
  #     - name: Install dependencies
  #       run: |
  #         uv pip install ".[dev]"
  #         uv pip install "./integration-tests[dev]"
  #     - name: Run integration tests
  #       run: pytest tests/integration -v
