# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
########################################################################
## 🚩                     mkinit flags                             🚩 ##
########################################################################
__ignore__ = []
__submodules__ = ["model_endpoint_info"]
########################################################################
## ⚠️        This file is auto-generated by mkinit                 ⚠️ ##
## ⚠️             Do not edit below this line                      ⚠️ ##
########################################################################
from aiperf.inference.model_endpoint_info import (
    EndpointInfo,
    ModelEndpointInfo,
    ModelInfo,
    ModelListInfo,
)

__all__ = ["EndpointInfo", "ModelEndpointInfo", "ModelInfo", "ModelListInfo"]
